### ISSUE TITLE
Download binary instead of building project in Arch Linux

### ISSUE THREAD

**Issue by nikitabobko** [crow-translate/crow-translate#100]
I wish there was an alternative package for Arch Linux called `crow-translate-bin` which would download compiled binaries instead of compiling `crow-translate` from sources like it's done now. If you're too lazy for compiling separate package for Arch then you can download already compiled deb package (you already build such) and unpack it.

**Comment by Shatur95** [comment]
But what is the problem with compilation? The project builds very quickly.

**Comment by nikitabobko** [comment]
Well, not really quick. On my laptop with Intel Core i5-7Y54 compiling takes 2:20 minutes. It brings a little pain when I do system upgrade and I have to wait particular package for more than 2 minutes.

**Comment by Shatur95** [comment]
Did you specify the number of threads when compiling?

**Comment by VolkMilit** [comment]
Did you compile many packages from AUR? I mean, 2 minutes not that bad in one thread compile. On my [old processor](https://ark.intel.com/content/www/us/en/ark/products/35300/intel-pentium-processor-e5300-2m-cache-2-60-ghz-800-mhz-fsb.html?wapkw=E5300) using 1 thread, compile Crow ~7 minutes. Using 4 thread compile it about 1.40 minutes. And, AFAIK, default makepkg settings specify -O2 optimizations, that increase compile time.

If you compile new versions that often, you should use ```MAKEFLAGS="-j4"``` environment variable.

**Comment by nikitabobko** [comment]
Sorry for the delay. 

Multi threading compilation takes on my laptop ~1 min. I still believe that it's too much. It's Arch Linux not Gentoo. If every software I install was installed by compilation then I'd wait forever waiting for system upgrade.

Why not to speedup installation if it's possible in a such cheap way? I don't see any important reasons or maintenance cost for not providing package that uses compiled binaries.

**Comment by Shatur95** [comment]
> I don't see any important reasons or maintenance cost for not providing package that uses compiled binaries.

You are right, this is not a big problem. It just not very convenient to maintain the binary version too, because I will have to upload the built package and update the additional package in AUR every release... I will think about it.
An ideal solution would be to send the package to the official repository. But, unfortunately, I am not know any interested Trusted User :(

**Comment by nikitabobko** [comment]
> I will have to upload the built package and update the additional package in AUR every release

It's better to automate such thing as releasing. DevOps it :)

> I will think about it

Thanks!

**Comment by Shatur95** [comment]
> It's better to automate such thing as releasing. DevOps it :)
I already automated builds via GitHub Actions, bit it not supports Arch. I will look for solution.

**Comment by VolkMilit** [comment]
> It's Arch Linux not Gentoo.

But you keep installing software through AUR? Why? Or if you only installs Crow, 1 minute to compile is not too much. Try to not update system about a week and you will wait for all packages to installs about 10 minutes (depending off HDD).

Arch for people, that want to full control their system, that's include patching and building software by hand. If you want current releases of software, but without compilation, maybe you should look to Fedora? You can also use Debian Testing or Debian Sid, believe me, they're pretty stable nowadays. There is also Puppy Linux (doesn't have Crow, tho, but maybe you can convert from deb or rpm, as Puppy used them both), Open SUSE, they're ship most fresh packages.

Another option: you can help pull Crow to main repositories, there was poll on Reddit.

**Comment by Shatur95** [comment]
@nikitabobko, FYI, crow-translate was added to [chaotic-aur](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#chaotic-aur).

**Comment by Shatur95** [comment]
I decided to leave it as is to simplify maintenance. Next versions will contain .zip packages for Linux, so helping in creating this package is appreciated.
