### ISSUE TITLE
Building failed on Solus

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#102]
Hi! I am trying to build crow-translate for Solus 4.1

I get this error:

```
/usr/bin/lrelease data/translations/crow_uk.ts -qm .qm/crow_uk.qm
make: /usr/bin/lrelease: No such file or directory
make: *** [Makefile:647: .qm/crow_uk.qm] Error 127
Command '['/bin/bash', '--norc', '--noprofile', '/tmp/ypkg-install3PcbW6']' returned non-zero exit status 2
[Build] install failed
ERRO[20:34:27] Failed to build package                       error="exit status 1"
ERRO[20:34:30] Failed to build packages                     
make[1]: Leaving directory '/home/algent/Repository/crow-translate'
make abireport
make[1]: Entering directory '/home/algent/Repository/crow-translate'
abireport -p abi_ -D `dirname package.yml` scan-packages `dirname package.yml`
error locating packages: No packages in directory .
make[1]: *** [../Makefile.common:15: abireport] Error 1
make[1]: Leaving directory '/home/algent/Repository/crow-translate'
make: *** [../Makefile.common:12: complete] Error 
```

More details in this [log](https://hasteb.in/izibegas.sql)
I am using this [package.yml](https://hasteb.in/cizidenu.sql)

**Comment by Shatur95** [comment]
Hello!
The problem in `lrelease`. Do you have it installed?

**Comment by algent-al** [comment]
Oh, I see. It is from `qt5-tools-devel`. I have to try again.

**Comment by Shatur95** [comment]
If the build succeeds, could you provide installation instructions for other users of your distribution?

**Comment by algent-al** [comment]
If the build succeeds, it is going to in official repo for all Solus users.

**Comment by Shatur95** [comment]
Nice to hear!

**Comment by algent-al** [comment]
Hi! The building succeeded. Thank you!

**Comment by Shatur95** [comment]
Cool! Let me know if Crow Translate appears in the official repository, I will update the information in [README.md](https://github.com/crow-translate/crow-translate#installation).

**Comment by algent-al** [comment]
Hi! 
crow-translate has just been added in [Solus Repository](https://dev.getsol.us/source/crow-translate/)

**Comment by Shatur95** [comment]
Hello, great!
What dependencies are used for building? It's for [Dependencies](https://github.com/crow-translate/crow-translate#dependencies) section.

**Comment by algent-al** [comment]
For building it I used these dependencies:
`qt5-tools-devel qt5-multimedia-devel qt5-svg-devel qt5-x11extras-devel`
and one rundependency: `gstreamer-1.0-plugins-good`.
Maybe there are other files as build (make) and run dependency, but I didn't notice any other.
My [tests](https://dev.getsol.us/D8176) were fine.

**Comment by algent-al** [comment]
There are a lot of packages in system.devel component so i installed what extra devel packages are needed to build this package.
```
Name: system.devel
LocalName: Base development tools
Summary: Base development tools
Description: Development utilities - base system
Group: system
Maintainer: Name: Solus Team
Email: root@solus-project.com
Packages: abireport autoconf automake bash-completion-devel binutils bison bison-devel catbox cmake dbus-devel diffstat diffutils expat-devel fakeroot file-devel flex flex-devel g++ gcc gettext-devel gfortran glibc-devel gmp-devel gobject-introspection-devel intltool libarchive-bin libffi-devel libgpg-error-devel libgudev-devel libtool-devel libxml2-devel linux-headers m4 make meson mpc-devel mpfr-devel nano nasm ncurses-devel openssl-devel pam-devel patch pkg-config polkit-devel python-devel quilt readline-devel systemd-devel texinfo util-linux-devel xz-devel ypkg zlib-devel 
```

**Comment by Shatur95** [comment]
Thank you!

**Comment by Shatur95** [comment]
> and one rundependency: gstreamer-1.0-plugins-good.

I think that you may also need Qt5 library installed to run because the app uses dynamic linking.

**Comment by algent-al** [comment]
This is what info is`eopkg` giving about dependencios for this package:
` eopkg info crow-translate`
`Dependencies        : libstdc++ qt5-multimedia libgcc qt5-base glibc libx11 qt5-x11extras `

and later only for `qt5-multimedia`
`eopkg info qt5-multimedia`
`Dependencies        : libstdc++ openal-soft qt5-base gstreamer-1.0 alsa-lib glibc pulseaudio gstreamer-1.0-plugins-base  qt5-declarative glib2 libglvnd`

Who knows how far can this go.

**Comment by Shatur95** [comment]
>  Dependencies : libstdc++ qt5-multimedia libgcc qt5-base glibc libx11 qt5-x11extras 

Thanks, top-level dependencies are exactly what I need.
