### ISSUE TITLE
Error transferring when "Automctically translate" checkbox is checked

### ISSUE THREAD

**Issue by Katarn** [crow-translate/crow-translate#105]
**Bug description**
I get this error after some time of entering of the text.

**Steps to reproduce**

1.  Check the box "Automatically translate".
2.  Select Google translate service.
3.  Enter text for some time in the original text box.
4.  See error.

**Expected behavior**
I expect to see a translation of the entered text.

**Screenshots**
![image](https://user-images.githubusercontent.com/6339978/74825013-3912a600-531a-11ea-99db-ac1e5bbafbc6.png)

**Environment**

-   OS: Windows 8.1
-   Crow Translate version: (e.g. 2.3.1)

**Comment by Shatur95** [comment]
Unfortunately, this is not a bug. Since the API is free, all translation providers have limited number of requests. When "Automatically translate" is enabled, Crow sends more requests than without this option and use see this error message.

**Comment by Katarn** [comment]
There is no way to mimic the Google Translate web-site? There are no such restrictions on the site.

**Comment by Shatur95** [comment]
Currently, not. Crow use public API instead of parsing website directly.

**Comment by azjio** [comment]
Make an adjustable timeout in the settings, for example 2 seconds, before accessing the API.
I enter the text, and the program translates without waiting end of input.

**Comment by Shatur95** [comment]
> Make an adjustable timeout in the settings

This is a good idea. The already exists, but not configurable. I currently out of time, but PR's are welcome.

**Comment by azjio** [comment]
When an error occurs, you can detect the text and return a readable version, for example: "Sorry, an error has occurred. Google is blocking multiple requests."

**Comment by Sentero-esp12** [comment]
New thread (looking for a C++ programmer to help with implementing unlimited Google Translate): https://github.com/crow-translate/QOnlineTranslator/issues/17#ref-issue-567463369
