### ISSUE TITLE
Add ability to launch GUI with source and target language selected

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#106]
**Is your feature request related to a problem? Please describe**
The GUI always defaults to using auto for both the source and target language. This is problematic in some cases. For example, when highlighting the kanji 本 (book in Japanese) and translating it, crow interprets it as Chinese instead. Of course, this is a valid Chinese character, but I always want it to be interpreted as Japanese for my usage.

**Describe the solution you'd like**
Make crow launch the GUI with the correct settings when called like this `crow -s ja -t en`.

**Describe alternatives you've considered**
I currently manually set the languages when I launch the GUI. It's not a big deal, but it seems like an extra step that could easily be removed.

It looks like #88 might be somewhat related, but I use the i3 window manager on Arch Linux without a login manager or system tray, so that doesn't work for my use case.

**Comment by Shatur95** [comment]
Hello! Crow Translate always remember last selected languages. If you select languages, then Crow will remember them at the next start. But this will only work if the program is closed correctly. So, I think that this is a bug.

Could you try the following? Are languages saved after the following steps?
1. Run the program.
2. Select the desired languages.
3. Exit the program completely (click on the tray icon and select close).

**Comment by LiteracyFanatic** [comment]
Following the steps you listed worked. While this technically fixes my problem, it would be nice if crow saved it's settings at shutdown.

I use the standard `systemctl poweroff` command to shutdown my system. Could you please clarify what constitutes a correct shutdown of crow? Not all linux systems have a system tray. Since crow basically runs in the background as a daemon, it could be started as a systemd user unit which would allow custom logic to be run to stop the service when the machine shutsdown. I'd just need to know what happens when you click exit from the tray. Is a particular signal or dbus message sent to crow?

**Comment by VolkMilit** [comment]
> it could be started as a systemd user unit 

It couldn't. Even if we use 'daemon' word here, Crow is user space daemon. It should launch in user mode with your desktop environment and should die, when Xorg is sending signal. Also, it will be force killed, if Xorg dies.

**Comment by LiteracyFanatic** [comment]
Systemd user services run in the same scope as the user who starts them. There are actually a number of existing pieces of graphical software on linux which provide user services e.g. blueman-applet.service or dunst.service. There are lots of reasons for this: making use of cgroups, setting limits on memory or cpu consumption, automatic restart on failure, or custom startup or shutdown logic. In fact, Xorg itself can be started as a Systemd user unit and other graphical services can be made to depend on X running as a prerequisite.

That being said, my main question remains whether there is any way to correctly shut down crow without access to its tray icon.

**Comment by Shatur95** [comment]
> I use the standard systemctl poweroff command to shutdown my system.

Unfortunately, this is the expected behavior :( This command forces termination of all applications. For example, if you have a document with unsaved changes, it will not asked before saving, the application will just terminated.

> I'd just need to know what happens when you click exit from the tray. Is a particular signal or dbus message sent to crow?

It uses internal call to close application. But I can just export it to D-Bus as [other functions](https://github.com/crow-translate/crow-translate#d-bus-api) if you want.

**Comment by VolkMilit** [comment]
> use of cgroups, setting limits on memory or cpu consumption

You know, that cgroup was used before systemd, right? I mean, there was, at least, consolekit and now polkit. You can access to cgroup without being a daemon of uselessd. And, again, it makes no sense making Crow as s-d service.

**Comment by LiteracyFanatic** [comment]
@Shatur95 Yes, it would be great if you could export the D-Bus function; then I can just make that call from the terminal before shutting down. You are right that `systemctl poweroff` kills regular processes. The whole reason I mentioned running it as a service was that you can specify how you want the processes associated with the service to be shutdown. So long as you don't pass the `--force` flag, `systemctl poweroff` would then wait for crow.service to be properly shutdown (in this case by a dbus call from ExecStop).

@VolkMilit Yes, I am aware that cgroups exist separately from Systemd. My intention was not to start a debate over the merits of different init systems or service managers. There are things I like about Systemd but I certainly wish it was less bloated. Regardless, my distro uses it so I do as well. The great thing is that as long as crow publicly exposes a way to shut itself down, a Systemd service, a runit service, or even just a plain old shell script are all equally valid approaches to making sure that dbus call gets made.

**Comment by Shatur95** [comment]
Okay, I'll add it. Stay tuned for updates.

**Comment by LiteracyFanatic** [comment]
Great! Thanks a bunch.

**Comment by Shatur95** [comment]
Done, now you can use D-Bus comand to tell the application to shut down.:
```bash
qdbus io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow quit
```
You can read more about it [here](https://github.com/crow-translate/crow-translate#d-bus-api).
