### ISSUE TITLE
Processing of line breaks in sentences

### ISSUE THREAD

**Issue by TheGentleChen** [crow-translate/crow-translate#110]
**Is your feature request related to a problem? Please describe**
When I use PDF reader to view documents, I often need to translate multiple lines, but there will be some line breaks in the copied sentences, which affects the normal translation, so I have to manually adjust the sentences.

**Describe the solution you'd like**
Remove line breaks from sentences so that they can be translated normally.

**Describe alternatives you've considered**
When preprocessing sentences, remove line breaks。

**Additional context**
This is a very useful tool. Thank you for your work.

**Comment by Shatur95** [comment]
Hello! Crow already have such option, try the following:
![изображение](https://user-images.githubusercontent.com/22453358/79065403-b0c8d580-7cb8-11ea-8e03-0b4ff15a2e65.png)

>  This is a very useful tool. Thank you for your work.

You are welcome :)

**Comment by TheGentleChen** [comment]
Oh, I was careless. Thanks.

**Comment by mustifanci** [comment]
it is not work from me. What can i do ?
![Ekran görüntüsü 2021-12-18 00-10-52](https://user-images.githubusercontent.com/40540308/146608626-2119426c-9da8-4dfa-93d7-6f5dff95dd61.png)
![Ekran görüntüsü 2021-12-18 00-11-25](https://user-images.githubusercontent.com/40540308/146608656-4683642e-dcd1-4f4c-bfaf-5c07ec8d3837.png)
