### ISSUE TITLE
Popup window should have a settings icon

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#111]
**Is your feature request related to a problem? Please describe**
If you set crow to use the popup translation window, there is no icon to launch the settings window so you can switch it back to always showing the main window.

**Describe the solution you'd like**
The settings icon should appear on the popup window.

**Describe alternatives you've considered**
You can get to the main window and thus the settings menu using the ShowMainWindow keybinding. I always use the TranslateSelectionKeybinding, so I had to look in the configuration file to figure out how to show the main window again.

**Comment by Shatur95** [comment]
Do you know that you can click on tray icon to show open settings from context menu?

**Comment by LiteracyFanatic** [comment]
Ah, that makes sense. I don't have a system tray because there is an unresolved bug that screws up the rendering of polybar. As long as it's easily accessible for most people, that's fine. I can use the keyboard shortcut.
