### ISSUE TITLE
DBus errors

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#112]
**Bug description**
I get the following error messages when I run crow. Aside from printing out this error, everything still works fine.

```
propsReply "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
nmReply "Method \"GetDevices\" with signature \"\" on interface \"org.freedesktop.NetworkManager\" doesn't exist\n"
"Object path cannot be empty"
```
**Steps to reproduce**
Run any crow command from a terminal.

**Environment**
-   OS: Arch Linux
-   Desktop environment: i3
-   Crow Translate version: 2.3.1

**Comment by Shatur95** [comment]
Can't reproduce :(
This errors generated by Qt itself. Something wrong with D-Bus. Could you test any [D-Bus command](https://github.com/crow-translate/crow-translate#d-bus-api)?

**Comment by LiteracyFanatic** [comment]
I use the following lines in one of my scripts and it was still working fine.

```
    busctl --user call \
        io.crow_translate.CrowTranslate \
        /io/crow_translate/CrowTranslate/MainWindow \
        io.crow_translate.CrowTranslate.MainWindow \
        translateSelection
```

The issue has been happening for several days, but after doing a system update this morning, it no longer occurs. I guess it must have been an issue in another package as you suggested. It looks like `qt5-tools` was among the upgraded packages.
