### ISSUE TITLE
Return nonzero exit code when translation fails

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#113]
**Is your feature request related to a problem? Please describe**
It would be useful to be able tell if a translation was completed successfully or not so that a script using crow could respond appropriately.

**Describe the solution you'd like**
Return a nonzero exit code on failure.

**Describe alternatives you've considered**
I could parse the output to see if it matches the expected format, but that's more brittle than just using an exit code.

**Additional context**
I have a script that displays the translation of a highlighted word in my status bar. After extended use, crow will fail with an error message like this:

```
"Error: Error transferring https://translate.googleapis.com/translate_a/single?client=gtx&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&dt=rw&dt=rm&dt=ss&dt=t&dt=at&dt=qc&sl=auto&tl=en&hl=en&q=旅行 - server replied: Too Many Requests" 
```

I'd like to have the script detect this scenario and try again with a different provider.

**Comment by Shatur95** [comment]
Thanks, fixed. Now it should return 1 on translation error.

**Comment by LiteracyFanatic** [comment]
Awesome, thanks for the quick fix!
