### ISSUE TITLE
Popup window immediately disappears under Ubuntu Budgie with Pixel Saver applet

### ISSUE THREAD

**Issue by hiddenman** [crow-translate/crow-translate#115]
**Bug description**
Ubuntu Budgie desktop environment + Pixel Saver applet causes Crow Translate to immediately hide a popup window (shown by shortcut Ctrl-Alt-E).

**Steps to reproduce**

1.  Run Crow Translate on Ubuntu Budgie DE + Pixel Saver applet
2.  Select a text and press Ctrl-Alt-E to t
3.  Popup window appears and immediately disappears 

**Expected behavior**
It should not disappear.

**Screenshots**
Link to the video: https://youtu.be/E_3gk1QQ45M

**Environment**

-   OS: Ubuntu Budgie 20.04
-   Crow Translate version: (e.g. 2.3.1-1)

**Additional context**
Here is the link with issue i reported to Ubuntu Budgie: https://discourse.ubuntubudgie.org/t/crow-translate-popup-windows-disappears/3506
Not sure why this happens and what should be fixed: Pixel Saver applet or/and Crow Translate.

**Comment by Shatur95** [comment]
Thanks for the report, but I think that the problem in Pixel Saver applet. Pop-up window will disappear if it loses focus. So, it looks like the applet causes window focus to lose for a second. I can't fix this :(
