### ISSUE TITLE
Include submodules in tagged releases

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#116]
**Is your feature request related to a problem? Please describe**
This is not exactly a problem, but to package crow-translate by using source code, I have to add the links of sub modules too, in [package.yml](https://dev.getsol.us/source/crow-translate/browse/master/package.yml) file, which it makes more annoying to package.

**Describe the solution you'd like**
The solution I would like is to have tagged releases with sub modules included in tarball.
This will make it more simple to update.

**Comment by Shatur95** [comment]
Hello! Sorry, but as I know GitHub does not allow to include submodules into release tarball with sources. I do the [same thing](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=crow-translate) for Archlinux.

**Comment by algent-al** [comment]
Sorry, I didn't know that. I asked this because for example this repo already does this:
[budgie-extras](https://github.com/UbuntuBudgie/budgie-extras) for [budgie-quickchar](https://github.com/UbuntuBudgie/budgie-extras/tree/master/budgie-quickchar) and [budgie-network-manager](https://github.com/UbuntuBudgie/budgie-extras/tree/master/budgie-network-manager)

**Comment by Shatur95** [comment]
This repository simply creates a complete archive manually. If you click on [Source Code](https://github.com/UbuntuBudgie/budgie-extras/releases), you will not see submodules in this archive.

**Comment by algent-al** [comment]
Yes that is true. They use `.gitmodules` and `mkrelease.sh` to do that.

**Comment by Shatur95** [comment]
Honestly, I would like to avoid scripting. But I will think about solution.

**Comment by Shatur95** [comment]
I found the best solution. Now CMake will automatically download all external libraries via built-in [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) functionality.

**Comment by algent-al** [comment]
Thank you!
