### ISSUE TITLE
No icon at all

### ISSUE THREAD

**Issue by authmane512** [crow-translate/crow-translate#117]
**Bug description**
There is no icon at all:

**Steps to reproduce**
Just open the program

**Expected behavior**
...

**Screenshots**
![image](https://user-images.githubusercontent.com/9754140/81398522-9f44e300-9129-11ea-8ffd-e32bf6409eb3.png)

**Environment**

-   OS: Linux Mint 19.3
-   Desktop environment: regolith i3
-   Crow Translate version: 2.3.1

**Additional context**
if I run crow with command line, I get:
```
$ crow
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: yes
QSystemTrayIcon::setVisible: No Icon set
inotify_add_watch("/home/authmane512/.config/qt5ct") failed: "No such file or directory"
```

**Comment by Shatur95** [comment]
The problem is in configuration of your DE. Please, configure `qt5ct` or `qt5-styleplugins`. This is needed for all Qt applications.
