### ISSUE TITLE
Error: Dependency is not satisfiable: libgcc-s1 (>= 3.0)

### ISSUE THREAD

**Issue by the81kid** [crow-translate/crow-translate#119]
Hello
Thanks for the translator app! It's been very useful. I'm receiving this error when I try to install: Error: Dependency is not satisfiable: libgcc-s1 (>= 3.0) . I'm running the latest Linux Mint (19.3) and it's fully updated. I've tried using Synaptic Package Manager to install it manually, but I can't find it. Is this Crow Translate update for another Linux version/distro?

**Comment by Shatur95** [comment]
Hello!
Is the problem present only in the latest version?

**Comment by the81kid** [comment]
Yes. I've never had that message in any of the previous versions. That file (driver?) doesn't even seem to be available to my OS.

**Comment by Shatur95** [comment]
Confirmed, something wrong with packaging :(
I will try to fix it ASAP.

**Comment by the81kid** [comment]
Thanks a lot!

**Comment by linhnd1303** [comment]
mine as the same error here, please make it fix

**Comment by Shatur95** [comment]
Fixed! Please, re-download the latest version.

**Comment by the81kid** [comment]
Hi, many thanks! Have a good day!
    On Tuesday, 12 May 2020, 21:57:45 CEST, Hennadii Chernyshchyk <notifications@github.com> wrote:  
 
 


Fixed! Please, re-download the latest version.

**Comment by linhnd1303** [comment]
> Fixed! Please, re-download the latest version.

Legend, appreciate that
