### ISSUE TITLE
Version 2.3.2 cannot detect selected text

### ISSUE THREAD

**Issue by linhnd1303** [crow-translate/crow-translate#123]
**Bug description**
I'm using google docs and some another type on web-based text editing website and crowtranslate version 2.3.2 cannot detected and translate selected text from that web-based application. It's just translated from clipboard source

**Steps to reproduce**

1.  Selected Text wit mouse on Google Docs (and another type of ediiting web-based)
2.  Shortcut Ctrl + Alt + E to quick translate select text
3.  the crowtranstae immediately appear but it just translate the text from clipboard it had been copied and Not translate selected from step 01

**Expected behavior**
it's would translate selected text from web-based website application.

**Screenshots**
This screenshots to help explain your problem:
1. See my clipboard first: [sreenshot1](http://i.imgur.com/R6iXxQB.png)
2. Selected text from google docs [Screenshot2](http://i.imgur.com/EzqQNKH.png) with Crowtranslate running on  background.
3. Ctrl + Alt + E
4. Just from clipboard source to be translated [Screenshot3](http://i.imgur.com/iOe00nk.png)

**Environment**

-   OS: KDE NEON
-   Desktop environment: KDE
-   Crow Translate version: 2.3.2

**Additional context**
That's all about this problem. Please help fix. Thank you a lot for this awesome app.

**Comment by Shatur95** [comment]
This is known issue, but this is not related with Crow. Crow uses Linux selection buffer but some aplications do not update selection correctly. I already have a request to add "compatibility mode" to just send `Ctrl+C` and read clipboard. This will solve the issue.

**Comment by linhnd1303** [comment]
Hi @Shatur95, 
That's clear enough, hopefully this will be soon upgrade. 
I close this topic here.
Thank you.

**Comment by CtrlPy** [comment]
another problem is there in this 2.3.2 software version with the pose of the software window itself, for example I put the program in the desktop itself but after the rollback of the software deployment it is moved on the screen center.

**Comment by Shatur95** [comment]
Closing in favor of #99
