### ISSUE TITLE
Hola, la aplicación para Debian se demora para pronunciar una traducción.

### ISSUE THREAD

**Issue by herwinux** [crow-translate/crow-translate#125]
**Bug description**

**Steps to reproduce**

1.  Go to '...'
2.  Click on '...'
3.  Scroll down to '...'
4.  See error

**Expected behavior**

**Screenshots**

**Environment**

-   OS: (e.g. Arch Linux, Ubuntu, Windows)
-   Desktop environment: (only for Linux, e.g. KDE, Gnome)
-   Crow Translate version: (e.g. 2.3.0)

**Additional context**

**Comment by Shatur95** [comment]
Please, fill the issue in English with clear description of your problem.
