### ISSUE TITLE
Error translate

### ISSUE THREAD

**Issue by CtrlPy** [crow-translate/crow-translate#126]
hello there! I ask you to forgive me for my poor English, I only teach it, but I think everything will be clear to you, I will try to briefly and easily explain the essence of the problem, and it is as if very simple, everything is visible in the photo. but if in detail, at the beginning the program works well, but some time after the launch I will get this error: 

![image](https://user-images.githubusercontent.com/65983392/83810192-65cbad00-a6c0-11ea-9ab1-235b02a0be40.png)

My system config:

![image](https://user-images.githubusercontent.com/65983392/83810683-39646080-a6c1-11ea-9f70-9f0264dbb6a2.png)

version program CrownTranslate:

![image](https://user-images.githubusercontent.com/65983392/83810823-6f094980-a6c1-11ea-8807-e457a9b60df3.png)

I hope you fix this problem since your application is very good and I like to use it, I really hope for your help. Regards CtrlPy

**Comment by Shatur95** [comment]
Hello!
Thank for the report but this is known issue. Google have requests limit for free API use and can "ban" you for a time. The solution is just change the engine temporary (select Bing or Yandex under the translation field).
Sorry, but I can't fix this because the issue not on the Crow side.
