### ISSUE TITLE
Problem chortcuts

### ISSUE THREAD

**Issue by CtrlPy** [crow-translate/crow-translate#127]
I wanted to change the keycombination to the translation as a result now the key combination doesn't work and in the translation location I get the text I wrote deleted. and this problem is not only me but my friend, a lot of problems, please deal with it.  

![image](https://user-images.githubusercontent.com/65983392/83885356-e9cc7600-a74e-11ea-9b46-23edd88e089f.png)

in the settings everything is the default but it all exactly doesn't work, the combination of ctrl alt E simply removes everything

**Comment by Shatur95** [comment]
Please fill the issue according to the issue template. I can't fix the issue without all information (System, steps etc.).

Also, try to clear settings by removing `~./config/crow`.
