### ISSUE TITLE
yandex dictionary, Bing translate: unencrypted clear text http

### ISSUE THREAD

**Issue by lazyletucce** [crow-translate/crow-translate#128]
requests to dictionary.yandex.net are using unencrypted  http, can you do something about that? or maybe an option to disable the dictionary if it's not possible? it leak the whole copied text in plain text.
thanks for this fantastic software!
![Untitled](https://user-images.githubusercontent.com/61092559/84039460-cb55bd00-a990-11ea-80ec-d847bf9e00cf.png)

**Comment by Shatur95** [comment]
Wow, yes, it's my fault. I will fix ASAP, stay tuned,

**Comment by lazyletucce** [comment]
similar problem with Bing, it use http instead of https

**Comment by Shatur95** [comment]
Done, check the latest master. Now all requests will use https.
