### ISSUE TITLE
No .rpm package of version 2.3.2

### ISSUE THREAD

**Issue by Joselpdj** [crow-translate/crow-translate#130]
**Bug description**
In the latest version I can't find package in rpm.

**Steps to reproduce**
Steps to reproduce the behavior: Cannot find rpm package of the latest version 2.3.2

**Comment by Shatur95** [comment]
If you want to see it at Fedora Copr, you need to contact the maintainer.
BTW, next version of Crow will have `.rpm` provided by me on GitHub Releases page.

**Comment by Joselpdj** [comment]
I use Mageia 7 Plasma, and install the package .rpm from GitHub directly, and I have raised adding the app to Mageia's blogdrake rep

**Comment by Shatur95** [comment]
It would be nice. Please, let me know if the app will be added to the repo, I will update description.

**Comment by Joselpdj** [comment]
Hi! we have already added the application to Mageia's Blogdrake repo. Could you make any mention of it in the description?

Greetings!!

**Comment by Joselpdj** [comment]
Would it be possible to add the deepl.com translation engine?

**Comment by Shatur95** [comment]
> Hi! we have already added the application to Mageia's Blogdrake repo. Could you make any mention of it in the description?

Could you send a PR to README?

> Would it be possible to add the deepl.com translation engine?

See #24

**Comment by Joselpdj** [comment]
Hi!

I will send you the text shortly.
Greetings!

**Comment by Joselpdj** [comment]
Hi!
I am sending you the modified readme for you to add.
Greetings
[README.zip](https://github.com/crow-translate/crow-translate/files/4800659/README.zip)
!!

**Comment by Shatur95** [comment]
I meant to send a Pull Request to the repository, but okay.

**Comment by Joselpdj** [comment]
Very thanks!!
Greetings!

**Comment by CarlosEkisde** [comment]
I've managed to fork an upgrade the original COPR for Fedora if anyone is interested https://copr.fedorainfracloud.org/coprs/carlis/crow-translate/

I won't make any promises since I'm n00b at packaging but I'll try to keep it updated as I'm using this program daily.

**Comment by Shatur95** [comment]
@CarlosEkisde, Could you replace older link in README?

**Comment by CarlosEkisde** [comment]
> @CarlosEkisde, Could you replace older link in README?
Sure 
[README.tar.gz](https://github.com/crow-translate/crow-translate/files/4803281/README.tar.gz)

**Comment by Shatur95** [comment]
@CarlosEkisde, Why are you sending archives? :) You can just press "Edit" button below README. But okay, I merged you changes manually.

**Comment by CarlosEkisde** [comment]
> @CarlosEkisde, Why are you sending archives? :) You can just press "Edit" button below README. But okay, I merged your changes manually.

Trying to edit the Readme file forces the creation of a fork. I'm also new on github so I may missing something.

**Comment by Shatur95** [comment]
Yes, this how git works: you creating a fork, making changes and then sending Pull Request to the main repo.
