### ISSUE TITLE
Is an AppImage version planned?

### ISSUE THREAD

**Issue by picrochole** [crow-translate/crow-translate#138]
Hello,
I'm very pleased with Crow-Translate and use it a lot on my home computer. It is however impossible to use it at work because we still are on LinuxMint 18 (= Ubuntu 16.04). QT5 upgrading to version > 5.9 is not possible because of all other applications working with QT5 v. 5.5.1 which would have to be deleted. The best solution, until April 2021 at least ;-) would be to pack Crow-Translate into an .AppImage with all its dependencies.
Is there any plan for this possibility?
Thanks in advance.

**Comment by Shatur95** [comment]
Unfortunately I not planning it :(
But any help in this direction is welcome!

**Comment by picrochole** [comment]
OK! Thanks for the quick answer.

**Comment by picrochole** [comment]
Hello, me again!
Flickering through the web, I read one mail from you, from May 24, '19 where you wrote: "Но я постараюсь в следующей версии еще добавить AppImage чтобы не было таких проблем." Translated with "Crow_Translate" ;-) it looks like you had also planned such a possibility. I have been trying these last days to produce myself an AppImage but the calls for QT5 libraries seem to be hardcoded and all point to real /usr/lib/. I have not yet been able to have them point to AppImage internal folders.
I keep you informed if I succeed to convince Crow to use local QT5 libraries. Any idea how I could manage that?
Cheers. Francis

**Comment by Shatur95** [comment]
Hi!  Yes, I planned it previosly, but currently not planning it now because of a lack of time. So, help is very appreciated.
Take a look at [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) or at [linuxdeployqt](https://github.com/probonopd/linuxdeployqt). This tools can allow to automate such things.

**Comment by picrochole** [comment]
That's what I'm using! :-)
I keep you informed in case of any progress.

**Comment by Shatur95** [comment]
Thanks! If you will succeed, please, provide a small guide, I will try to integrate this commands into build system and produce appimages automatically.

**Comment by Shatur95** [comment]
Probably can be added, but I need help with the corrent automation with GitHub Actions and CMake.
