### ISSUE TITLE
Missing icons in crow translate UI on WMAKER

### ISSUE THREAD

**Issue by dadoprom** [crow-translate/crow-translate#148]
Missing icons in crow translate UI on WMAKER

**Screenshots**
![wmaker](https://user-images.githubusercontent.com/19377506/86064259-e8038300-ba6c-11ea-8f3a-d4f6085b68dd.jpg)

**Environment**

-   OS: Kde Neon  5.19.2
-   Desktop environment: WMAKER 0.95.9
-   Crow Translate version: 2.3.2

**Comment by Shatur95** [comment]
You need to configure Qt environment. Do you have icons in other Qt applications?

**Comment by dadoprom** [comment]
Ok, I will try that, thank you!

**Comment by Shatur95** [comment]
You need `qt5-ct` or `qt5-styleplugins` installed with specific environment variables. Read more about it [here](https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma) (this is not for your distro, but should help anyway).
