### ISSUE TITLE
crow-translate restore defaults after cliking OK on settings without doing any change.

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#149]
**Bug description**
crow-translate restore defaults after cliking OK on settings without doing any change.

**Steps to reproduce**

1. Add prefered languages.
2. Go to "Settings"
3.  Click on 'OK'
4.  See error

**Peek video**

![settings](https://user-images.githubusercontent.com/46356616/86164014-64e83880-bb11-11ea-8853-5241f8c39102.gif)

**Expected behavior**
Settings should not be restored to defaults if the user didn't click "Restore Defaults".

**Environment**

-   OS: Solus 4.1
-   Desktop environment: Budgie
-   Crow Translate version: 2.4.0

**Comment by Shatur95** [comment]
Can't reproduce... Could you try to clear the configuration and try to reproduce again?

**Comment by algent-al** [comment]
Found that there are two folders in `.config`, `crow` and `Crow Translate`. Deleted them both, but the problem is still there.

**Comment by algent-al** [comment]
These are some messages that I get in terminal:
```
QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)
QHotkey: Failed to unregister hotkey. Error: BadAccess (attempt to access private resource denied)
QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)
QHotkey: Failed to unregister hotkey. Error: BadAccess (attempt to access private resource denied)
QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)
QHotkey: Failed to unregister hotkey. Error: BadAccess (attempt to access private resource denied)
```

**Comment by Shatur95** [comment]
> These are some messages that I get in terminal:

Could you check if there is another launched instance of Crow?

**Comment by algent-al** [comment]
> Could you check if there is another launched instance of Crow?
No there is only one.
```
QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)
QHotkey: Failed to unregister hotkey. Error: BadAccess (attempt to access private resource denied)
```
Are present also in 2.3.2. I didn't have noticed those before.
Folder `Crow Translate` is created from version 2.4.0, and folder `crow` is created for version 2.3.2.

**Comment by Shatur95** [comment]
> QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)

This usually mean that global shortcut already registered in system (probably I should print which shortcut.

**Comment by algent-al** [comment]
> So, is all Crow global shortcuts work?

Only <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>S</kbd> for "Speak selected text" is not working.

**Comment by Shatur95** [comment]
> Only Ctrl + Alt + S for "Speak selected text" is not working.

But you had a lot of `QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)`?

**Comment by algent-al** [comment]
Hi! I am not in my Linux PC right now, but this message `QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)` is only one time, and it is repeated every time I open Settings and click OK.

**Comment by Shatur95** [comment]
Hm... Yes, this is expected too because you after saving settings Crow tries to re-register shortcut, but for some reason just can't register <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>S</kbd>. If you remap it - the message is gone.

But I have a good news. I reproduced the issue and will fix it after work today. Stay tuned.

**Comment by Shatur95** [comment]
Done, now must work as expected. Thank you for the report!

**Comment by algent-al** [comment]
Found why "Ctrl + Alt + S" wasn't working. The same shortcut is used by `budgie-window-shuffler`.

![shuffler](https://user-images.githubusercontent.com/46356616/86404362-c6460e00-bcaf-11ea-961f-30cf07da99f1.png)

Another thing worth noting is that. Updating from 2.3.2 to 2.4.0 and then running `crow` from terminal, I get `Segmentation Fault`. The solution is to remove `crow` folder from `.config`

**Comment by Shatur95** [comment]
> Found why "Ctrl + Alt + S" wasn't working. The same shortcut is used by budgie-window-shuffler.

Yes, will work if you change this shortcut in Crow settings.

> Another thing worth noting is that. Updating from 2.3.2 to 2.4.0 and then running crow from terminal, I get Segmentation Fault. The solution is to remove crow folder from .config.

This is weird. New version do not use old `crow` folder. New version use `Crow Translate` folder in `.config`.
