### ISSUE TITLE
Error: Dependency is not satisfiable: libgcc-s1 (>= 3.0)

### ISSUE THREAD

**Issue by the81kid** [crow-translate/crow-translate#152]
Hi, thanks for the great application. I can't install the latest 2 versions. They both give me this error message: Error: Dependency is not satisfiable: libgcc-s1 (>= 3.0)

I'm running Linux Mint 19.3. I can't install libgcc-s1 through synaptic package manager. Are the latest version of Crow Translate only for Linux Mint 20? Thanks.

**Comment by Shatur95** [comment]
This is weird. I used Ubuntu [18.04 on CI](https://github.com/crow-translate/crow-translate/runs/835721749?check_suite_focus=true)(compatible with Linux Mint 19.3) to provide build packages. But for some reason the app requires `libgcc-s1` that used only in Ubuntu 20.04. I do not know why Microsoft provides this package on Ubuntu 18.04.
Could you try to build it yourself.

**Comment by the81kid** [comment]
Do you mean build Crow Translate, or libgcc-s1, myself? Libgcc-s1 isn't available in the synaptic package manager in Linux Mint 19.3, so I suppose I can't manually install libgcc-s1. But I'm not an expert Linux user, so maybe I'm missing something.

**Comment by Shatur95** [comment]
I meant to build Crow Translate :)

**Comment by Shatur95** [comment]
I done it by myself. Try to re-download the latest `.deb`. I think that the problem on the GitHub Actions.

**Comment by the81kid** [comment]
Hi, thanks very much! The last time I tried to build Crow Translate was last year, with an earlier version of the program. It didn't work when I did it, but maybe I know more now to be able to do it better.

**Comment by Shatur95** [comment]
Just re-download the latest version, is it worked for you?

**Comment by the81kid** [comment]
Yes, I downloaded it and it worked fine. Thanks a lot!
