### ISSUE TITLE
Segmentation fault with latest Ubuntu

### ISSUE THREAD

**Issue by thiagoa** [crow-translate/crow-translate#154]
**Bug description**

I'm not sure if this is a bug with crow translate, but under latest Ubuntu 20.04 and latest updates (`apt-get upgrade`) I'm getting the following error:

```
$ crow
[1]    415949 segmentation fault  crow
```

Previously I was getting other errors:

```
$ crow
Qt: Session management error: Could not open network socket
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
[1]    415949 segmentation fault  crow
```

I solved the Session management error with `unset SESSION_MANAGER`, and `defaultServiceProvider` with `apt-get install libqt5multimedia5-plugins`. Now there's only the segmentation fault left.

That's very strange because the app was working perfectly before. Either some update broke it or a new version since I update crow translate automatically with a script by fetching the `.deb` from GitHub if a new one exists.

**Expected behavior**

The app would start as expected.

**Environment**

-   OS: Ubuntu 20.04
-   Desktop environment: Gnome Shell (Gnome's default)
-   Crow Translate version: (e.g. 2.4.1)

**Comment by Shatur95** [comment]
I think that the issue was in your environment Qt settings and not related to the Crow Translate. Try to install `libqt5network5`.

**Comment by thiagoa** [comment]
@Shatur95 Thank you, but this one was already installed. I still get segmentation fault.

**Comment by Shatur95** [comment]
Could you try to build the app from scratch and test is it work?
Build instruction available in README.md.

**Comment by thiagoa** [comment]
@Shatur95 I've just compiled from scratch and got segmentation fault as well :( Tried to run the `crow` binary from the `build` directory, and also tried to install the generated deb package and got the same error on both. I've installed a few dev packages before compiling:

```
$ apt-get install cmake qtbase5-dev libqt5x11extras5-dev qtmultimedia5-dev qttools5-dev extra-cmake-modules
```

Versions:

- cmake 3.16.3-1ubuntu1
- qtbase5-dev 5.12.8+dfsg-0ubuntu1
- libqt5x11extras5-dev 5.12.8-0ubuntu1
- qtmultimedia5-dev 5.12.8-0ubuntu1
- qttools5-dev 5.12.8-0ubuntu1
- extra-cmake-modules 5.68.0-0ubuntu1

**Comment by thiagoa** [comment]
@Shatur95 And now another update: I've managed to run it with a clean environment:

```
env -i XDG_RUNTIME_DIR=/run/user/1000 DISPLAY=:1 crow
```

So it must be some environment variable causing the problem :thinking: I'll investigate.further.

**Comment by Shatur95** [comment]
Interesting... What do you use for Qt theming? Maybe the problem in qt5ct? It uses environment variable to set theme.
Are other Qt applications work?

**Comment by thiagoa** [comment]
@Shatur95 Yes, other QT applications work fine. I have 4 QT env variables set:

```
QT4_IM_MODULE=ibus
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
QT_STYLE_OVERRIDE=kvantum
```

I've tested now real quick and I'm able to launch crow with all of them together (and the theming is indeed applied as expected), so it doesn't seem to be a problem with QT theming. As soon as I have some time I'll debug and will let you know what I find :slightly_smiling_face:

**Comment by c29r3** [comment]
Got same problem, Ubuntu 20.04. Installed from deb file
`Segmentation fault (core dumped)`
`kernel: crow[7845]: segfault at 8 ip 00007f1f89b578c8 sp 00007fffccec0688 error 4 in libQt5Gui.so.5.12.8[7f1f89b00000+41d000]`

**Comment by Shatur95** [comment]
@c29r3, does the following work for you?

```bash
$ env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
```

**Comment by c29r3** [comment]
> @c29r3, does the following work for you?
> 
> ```shell
> $ env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
> ```

Yes, this works with version 2.4.1

**Comment by Shatur95** [comment]
Thanks. Could you try debugging which environment variable is causing the crash?

**Comment by c29r3** [comment]
> Thanks. Could you try debugging which environment variable is causing the crash?
I do not quite understand how this can be done. If I give you the strace file, will that be useful?

**Comment by Shatur95** [comment]
Unfortunately, the trace file will not helpful :(
You need to print a list of all environment variables and try to detect which causes crash by binary search.

**Comment by Shatur95** [comment]
>  You need to print a list of all environment variables and try to detect which causes crash by binary search.

I'm sorry, but that’s all I have to suggest. I cannot reproduce the problem myself. It seems to me that the problem may be related to the configuration of your environment.

Other Qt applications works for you, right?

**Comment by c29r3** [comment]
> Other Qt applications works for you, right?

Correct. Even if i install crow-translate version 2.3.2 - it's works properly

**Comment by Shatur95** [comment]
Have you tried deleting settings?

**Comment by c29r3** [comment]
> Have you tried deleting settings? You need to delete `~/.config/Crow Translate/Crow Translate.conf`
It's works after deleting config file :))
I think I figured out what happened. I was migrating from Manjaro to Ubuntu 20.04. I had a backup of my home folder and it looks like I moved the old crow-translate config file there
![image](https://user-images.githubusercontent.com/52304443/87858272-64370b00-c935-11ea-9e57-b85428118022.png)

**Comment by Shatur95** [comment]
You mean that you copied settings from the old location (`~/.config/crow/Crow Translate.conf`) to new (`~/.config/Crow Translate/Crow Translate.conf`)?

**Comment by c29r3** [comment]
> You mean that you copied settings from the old location (`~/.config/crow/Crow Translate.conf`) to new (`~/.config/Crow Translate/Crow Translate.conf`)?

yep

**Comment by Shatur95** [comment]
Yes, this why I changed the location :)

BTW, you have not configured Qt applications look. without this Qt apps will look ugly in GTK environment. I suggest you to play with `qt5ct` or `qt5-styleplugins` to specify style for Qt applications.

@thiagoa, could you try to remove settings?

**Comment by thiagoa** [comment]
@Shatur95 Hey! Sorry, I had a few issues lately and I hadn't been able to debug. Just deleted the configurations from:

- `rm -f ~/.config/Crow\ Translate`
- `rm -f ~/.config/crow`

Then I'm able to launch it! However, as soon as the app creates a new config, it segfaults when I try opening it again. Here's my new problematic config from `~/.config/Crow Translate`:

```
[General]
AutoTranslate=true
CurrentEngine=0
WindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x96\0\0\0\x65\0\0\x3p\0\0\x1\xa6\0\0\0\x96\0\0\0\x8a\0\0\x3p\0\0\x1\xa6\0\0\0\0\0\0\0\0\xf\0\0\0\0\x96\0\0\0\x8a\0\0\x3p\0\0\x1\xa6)

[Buttons]
Source=pt
Translation=en
```

P.S.: It seems that the env vars were a red herring; the problem seems to be with the config file :thinking:

**Comment by Shatur95** [comment]
> After that I'm able to launch it! However, as soon as the app creates a new config, it segfaults when I try opening it again. Here's my new problematic config from ~/.config/Crow Translate:

I tested this configuration on my machine, but it does not crash. Could you debug which environment variable is causing the problem?

**Comment by dadoprom** [comment]
Hi, I have this issue as well. I get "segmentation fault" after I configured languages. 

When I removed these settings from config file the application is running:

[Buttons]
Source=sk, de
Translation=sk, de

When I leave it in config file I get "segmentation fault" and the app is not launched. 

version: 2.4.1
distro: KDE Neon 5.19

**Comment by Shatur95** [comment]
> [Buttons]
> Source=sk, de
> Translation=sk, de

I tried to start with these lines, but the application works... Could you send full configuration file? Maybe the issue caused by the combination of different settings?

**Comment by dadoprom** [comment]
with this config I get segmentation fault...
config is in zip file...

[Crow Translate.conf.zip](https://github.com/crow-translate/crow-translate/files/4955529/Crow.Translate.conf.zip)

**Comment by Shatur95** [comment]
Still can't reproduce on my side...
Could you build the app in something like QtCreator and launch in Debug mode? I can help you with this.

**Comment by dadoprom** [comment]
I do not know how to build it with QtCreator...

**Comment by Shatur95** [comment]
It's easy:

```bash
git clone --recursive git@github.com:crow-translate/crow-translate.git
```

Then just open CMakeLists.txt in QtCreator. Then press F5. The application will be launched.

**Comment by Shatur95** [comment]
Hm... Maybe it will be easier to me to download KDE Neon and try to reproduce in live USB. I will try today later.

**Comment by dadoprom** [comment]
I did try it, but there is something missing and it is not wroking for now... but I did not have had time to tinker with it more. Will try it latter.


> Hm... Maybe it will be easier to me to download KDE Neon and try to reproduce in live USB. I will try today later.

maybe yes actually


Thanx for your help :)

**Comment by thiagoa** [comment]
@Shatur95 I've compiled the app using Qt Creator and got to reproduce the error. How can I get useful information for you? It's been a long time since I last used such a GUI but I think the debugger has stopped where the error happened:

<img width="887" alt="2020-07-22_12-41" src="https://user-images.githubusercontent.com/746384/88197414-d9962a80-cc18-11ea-9dd5-056b3d35036b.png">

**Comment by thiagoa** [comment]
And just to reinforce, I'm able to launch the application if I remove the following section from the config file:

```
[Buttons]    
Source=pt    
Translation=en    
```

**Comment by thiagoa** [comment]
Another update: if I do the following code change it compiles and launches successfully with the above settings:

```c++
-    return window()->frameGeometry().width() <= window()->windowHandle()->screen()->availableGeometry().width();
+    return true;
```

**Comment by thiagoa** [comment]
It seems there's no `screen()` in this method call chain: `window()->windowHandle()->screen()`. My QT version is:

```
❯ qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```

**Comment by Shatur95** [comment]
Done! Now should work. Could you try?
Just open terminal in the cloned folder and execute the following:

```bash
git reset --hard # To reset all local changes
git pull # To update the local repo
```
And then just run the project through Qt Creator.

**Comment by thiagoa** [comment]
@Shatur95 It works! Thank you for this awesome project and for coming up with such a quick fix :tada:

**Comment by Shatur95** [comment]
Thanks everyone for submitting the issue and investigation :) I will draft a new release today.

**Comment by dadoprom** [comment]
Oh wow, thank you all...
