### ISSUE TITLE
Add option to use only the language flag in the UI

### ISSUE THREAD

**Issue by aksnes** [crow-translate/crow-translate#155]
Trying to set five languages on each side of the translator will give you a window that uses more than half of the horizontal size of a 1920x1080 screen and you can't change it without removing languages.

A setting allowing to use only the flags would be, in my opinion, the best aesthetically way of having a smaller and functionable window which would allow people to set up to 10 languages in each side without compromissing the entire screen.

It could alternatively be possible to use only abbreviations like EN, ES, PT, RU (something like ISO 639-1) but I think this would be actually harder than implement than just using the flags since they are already there, and it would be also possible to use a combination of the flags and the abbreviations and still have a smaller window size (flag + 2 or 3 letters).
The last option that I have in mind is just allowing them to be squeezed when resizing the window, maybe setting a minimum size that would limit the view to only the flag so resizing could be done without ruining the UI.

Screenshot of the problem in a 1920x1080 display using Manjaro-KDE with the AUR package (version 2.4.1), I also use it on Windows 10 and the "problem" persists in the same way there
![crow-translate](https://user-images.githubusercontent.com/62793870/87210941-c36d9d80-c2ed-11ea-9afc-7770fc55e75e.png)

**Comment by Shatur95** [comment]
Yes, I thought about the same thing! I will definitely add an option for it. I prefer abbreviations with flags because only flags do not always represent the language (the same country can have several languages). But I will add several combinations.
