### ISSUE TITLE
Some icons are missing under Ubuntu 20.04

### ISSUE THREAD

**Issue by Amr-Ibra** [crow-translate/crow-translate#156]
**Bug description**
Some icons are missing under Ubuntu 20.04.

**Steps to reproduce**
Install "crow-translate_2.4.0_amd64.deb" in Ubuntu 20.04.

**Expected behavior**
All icons appear.

**Screenshots**
![Bildschirmfoto vom 2020-07-16 10-21-41](https://user-images.githubusercontent.com/45657128/87645787-465b8180-c74e-11ea-8962-bae83191be72.png)
![Bildschirmfoto vom 2020-07-16 10-22-09](https://user-images.githubusercontent.com/45657128/87645796-4b203580-c74e-11ea-9736-802d2adfd9b8.png)

**Environment**
- OS: Ubuntu 20.04
- Desktop environment: GNOME 3.36
- Crow Translate version: 2.4.0

**Additional context**
Ubuntu 20.04 is using Yaru icons by default:
https://github.com/ubuntu/yaru/tree/master/icons

**Comment by Shatur95** [comment]
You need to configure Qt application in your environment via `qt5ct` or `qt5-styleplugins`. This is not the application issue.
