### ISSUE TITLE
Yandex: "Session is invalid" OR "Error: Unable to parse Yandex SID"

### ISSUE THREAD

**Issue by lazyletucce** [crow-translate/crow-translate#159]
Hello, since few days Yandex translate return "Session is invalid" error OR "Error: Unable to parse Yandex SID." 

using 2.4.0, 2.4.1, windows.

**Comment by lazyletucce** [comment]
well i found that you fixed it already https://github.com/crow-translate/QOnlineTranslator/commit/6226231c5c65afaf9d67bcaee1546c0bd81d25db

**Comment by Shatur95** [comment]
Yes, release will be available in few days :)
Yandex just changed API a bit.
