### ISSUE TITLE
How exactly is used -t option using cli

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#160]
**Bug description**

Hi! Can you explain please how to use the `-t` using cli.

For example translating into italian.

Edit: Sorry for the "bug" label.

**Comment by Shatur95** [comment]
`-t` is the argument to specify language code. For example, `crow -t es hello` will translate `hello` to Spanish.

**Comment by algent-al** [comment]
Oh! Thank you! I had tried `crow -t Italian text` and `crow -t It text`. I see now it was simpler.

**Comment by Shatur95** [comment]
Yes, you can also use `crow -c` to see all language codes.
