### ISSUE TITLE
Add language support for translation

### ISSUE THREAD

**Issue by Abdusalamstd** [crow-translate/crow-translate#161]
Google Translate already supports Uyghur translation. The Uyghurs belong to China and speak Uyghur language. I hope this translation application can add Uyghur language. Uyghur language ISO 639-1 Code is "ug" , ISO 3166-1 alpha-2 language code is "CN".

**Comment by Shatur95** [comment]
Hello! Yes, I will add Uyghur and other 4 missing languages today after work.

**Comment by Abdusalamstd** [comment]
> Hello! Yes, I will add Uyghur and other 4 missing languages today after work.
Thank you so much!
But,It seems that you used the wrong flag for Uyghur language.Uyghur language also use  the Chinese flag.We are also Chinese.

**Comment by Shatur95** [comment]
>  But,It seems that you used the wrong flag for Uyghur language.Uyghur language also use the Chinese flag.We are also Chinese.

Are you talking about Crowdin? Crowdin selects flag automatically and it is not related to the Crow Translate. In the app Uyghurs will have Chinese flag.

**Comment by Abdusalamstd** [comment]
> > But,It seems that you used the wrong flag for Uyghur language.Uyghur language also use the Chinese flag.We are also Chinese.
> 
> Are you talking about Crowdin? Crowdin selects flag automatically and it is not related to the Crow Translate. In the app Uyghur will have Chinese flag.

OK . I understand, thank you.

**Comment by Shatur95** [comment]
Done! Not sure that you noticed, but you leave some strings untranslated in Uighur localization. If you want to fix this, you can do it [on the website](https://crowdin.com/project/crow-translate) or via another PR.
Thanks for the report.
