### ISSUE TITLE
Yandex: Unable to parse SID

### ISSUE THREAD

**Issue by Joselpdj** [crow-translate/crow-translate#166]
Crow-translate: 2.5

I can't translate with Yandex engine. This error appears.

Error: No se puede analizar Yandex SID.

**Comment by Shatur95** [comment]
Can't reproduce on my machine. Please, fill the issue template.

**Comment by Joselpdj** [comment]
Here a screenshot
![Screenshot_20200803_091251](https://user-images.githubusercontent.com/65603208/89155801-d6c8fd00-d569-11ea-830a-02f3b6e1f018.png)

**Comment by Joselpdj** [comment]
![Screenshot_20200803_091355](https://user-images.githubusercontent.com/65603208/89155861-f7915280-d569-11ea-98ad-ae82d205e48a.png)

**Comment by Shatur95** [comment]
I see, but I mean feel issue template with full steps to reproduce.

**Comment by Joselpdj** [comment]
**Bug description**
I can't translate texts with the Yandex engine.

**Steps to reproduce**
Steps to reproduce the behavior:

1.  Go to Open the application and select Yandex translation engine
2.  Click on translate window for introduce the text
3.  Click on traduction button
4.  See error

**Expected behavior**
After initially selecting the Yandex translation engine and trying to translate any text, the correct translation should appear in my language, which in this case is Spanish.

**Screenshots**
![Screenshot_20200803_091251](https://user-images.githubusercontent.com/65603208/89156933-e3e6eb80-d56b-11ea-8f3b-3557babb162e.png)


**Environment**

-   OS: Mageia 7.1
-   Desktop environment: Plasma Kde
-   Crow Translate version: 2.5

**Additional context**
Add any other context about the problem here.

**Comment by Shatur95** [comment]
Thanks!
Tested with different languages including Spanish, translation works for me. Previously Yandex worked for you in 2.5? If so, have you translated a lot of text before (Yandex may have temporarily blocked the service for your IP address)?

**Comment by Joselpdj** [comment]
Thank you for your attention!!

I just started the application again and now if I work the translation with Yandex engine. 

It may have been what he comments by blocking the IP address.

We can close the bug.

Greetings!!

**Comment by Shatur95** [comment]
Nice to read that the problem is solved, but it's strange that it works after restart. I will leave it open currently. Please, let me know if you encounter the issue again.

**Comment by Shatur95** [comment]
The parsing algorithms have been improved, the bug should no longer be reproduced.
