### ISSUE TITLE
Export swapping languages to D-Bus

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#168]
**Is your feature request related to a problem? Please describe**
I have a primarily keyboard driven workflow. It would be nice if I didn't have to use the mouse to swap the input and output language.

**Describe the solution you'd like**
1. I'd like to be able to configure a keyboard shortcut for swapping languages like you can for some of the other buttons. 
2. Exposing the functionality through D-Bus would be nice as well. Then I could write a script to swap languages automatically when I change my keyboard input method between English and Japanese.

**Comment by Shatur95** [comment]
> I'd like to be able to configure a keyboard shortcut for swapping languages like you can for some of the other buttons.

There is a shortcut for it. <kbd>Ctrl</kbd>+<kbd>R</kbd>by default.

**Comment by LiteracyFanatic** [comment]
Ah, looks like this was added recently and I was a couple versions behind. I should have checked that first. Thanks! The second point would still be useful for integrating with CJK input methods.

**Comment by Shatur95** [comment]
I don't have time right now, but yes, it is possible. If anyone is interested, help is appreciated.
