### ISSUE TITLE
Selected languages not saved

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#170]
**Bug description**
Crow doesn't save the selected languages across restarts.

**Steps to reproduce**

1.  Open crow.
2.  Use the UI to and source and target languages.
3.  Close crow properly using the tray icon or D-Bus method.
4.  Restart crow. The selected languages will still be present, but auto will be selected instead.

**Expected behavior**
Crow should remember which source and target languages were selected.

**Screenshots**

![2020-08-14T05:38:51-05:00](https://user-images.githubusercontent.com/18249574/90241371-831fa480-ddf0-11ea-98ca-501a8dd2f369.png)
*Before closing.*

![2020-08-14T05:33:52-05:00](https://user-images.githubusercontent.com/18249574/90241369-831fa480-ddf0-11ea-8dc0-070887baf12e.png)
*After restarting.*

**Environment**

-   OS: Arch Linux
-   Desktop environment: i3
-   Crow Translate version: 2.5.0

**Additional context**

I believe this may be a regression related to the configuration file. It seems that at some point the config folder moved from `~/.config/crow/` to `~/.config/Crow Translate`. The old file had properties to remember the selected buttons but the new one does not.

**Comment by LiteracyFanatic** [comment]
I bisected and it looks like this broke in commit 151ef1e6b5e2a68870c9b89fa5100901de67b2fe.

**Comment by Shatur95** [comment]
Reproduced. Thanks, especially for bisect. Working on a fix.

**Comment by Shatur95** [comment]
Done, just forgot to call save and load methods after languages rework.

**Comment by LiteracyFanatic** [comment]
I'm getting a segfault with this commit. It's crashing right away at launch. Maybe an issue with default values not being defined in the absence of an existing config file? Let me know if there's any other useful info I can provide for debugging.

```
Stack trace of thread 462310:
#0  0x00007f4488cbe47b _ZN15QAbstractButton10setCheckedEb (libQt5Widgets.so.5 + 0x24f47b)
#1  0x000055edf6a94995 n/a (/home/jordan/src/crow-translate/build/crow + 0x2f995)
#2  0x000055edf6a99a6d n/a (/home/jordan/src/crow-translate/build/crow + 0x34a6d)
#3  0x000055edf6a98248 n/a (/home/jordan/src/crow-translate/build/crow + 0x33248)
#4  0x000055edf6a97f92 n/a (/home/jordan/src/crow-translate/build/crow + 0x32f92)
#5  0x00007f44876d7002 __libc_start_main (libc.so.6 + 0x27002)
#6  0x000055edf6a8292e n/a (/home/jordan/src/crow-translate/build/crow + 0x1d92e)
```

**Comment by Shatur95** [comment]
Hm... Can't reproduce on my side, works just fine for me. Could you send me your configuration and also try with clean config?

**Comment by LiteracyFanatic** [comment]
It only crashes when there is no config. If I generate a config using a working version and then run the new version is doesn't crash. This is the config it works with just for reference.

```
[Buttons]
Source=ja, en
Translation=en, ja

[MainWindow]
AutoTranslate=true
CurrentEngine=0
WindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2K\0\0\x1\x9f\0\0\x5G\0\0\x2\xbd\0\0\x2M\0\0\x1\x9f\0\0\x5\x45\0\0\x2\xbb\0\0\0\0\0\0\0\0\a\x80\0\0\x2M\0\0\x1\x9f\0\0\x5\x45\0\0\x2\xbb)
```

**Comment by Shatur95** [comment]
Oh, my mistake, not should work :)

**Comment by LiteracyFanatic** [comment]
Works perfectly now. Thanks for the quick fix. I really appreciate this piece of software; I use it every day in my language studies!

**Comment by Shatur95** [comment]
You are welcome :) Thanks for the report.

**Comment by dadoprom** [comment]
Yes, I agree, I also use Crow Translate every day and I just love it! Thank you!

**Comment by Shatur95** [comment]
Nice to read!

**Comment by VolkMilit** [comment]
> Still doesn't work for me, Linux

This issue is from 2020. Works for me on Arch Linux perfectly.
