### ISSUE TITLE
[False Positive]VirusTotal report Gen:Variant.Ursu.719387

### ISSUE THREAD

**Issue by boromyr** [crow-translate/crow-translate#172]
VirusTotal reports 11/68 Variant.Ursu.719387 malware detections for the crow.exe file, is this an error or are there any risks?
https://www.virustotal.com/gui/file/c6a84bb4f2ba6ea2c1f872ecc1c29244695dcd2fd2340e80eb2dc765b404e9b0/detection
Version 2.5.1 on Windows 10

**Comment by Shatur95** [comment]
I suppose it's false-positive. I do not build binary by myself, it [automated via CI](https://github.com/crow-translate/crow-translate/actions/runs/209099845). You can try to build Crow from source and check binary yourself, it should have the same results.

**Comment by Shatur95** [comment]
I meant I didn't change the binary in any way :) The source code is 100% safe, anyone can check it.
Perhaps VirusTotal detects [editing the registry for autostart settings](https://github.com/crow-translate/crow-translate/blob/79640e026d4cdc6133af07eba25309cfa13fb452/src/settings/appsettings.cpp#L168) as a sign of malware. It used only to let user the ability to start Crow automatically at startup in the app settings and [disabled by default](https://github.com/crow-translate/crow-translate/blob/79640e026d4cdc6133af07eba25309cfa13fb452/src/settings/appsettings.cpp#L178).

If you have any other questions about this, let me know.

**Comment by boromyr** [comment]
Perfect thanks, I have no worries about it, it was just to report it. Also up to version 2.4 it was 100% successful, so it will certainly be a problem in the latest updates.
Thank you.

**Comment by Shatur95** [comment]
> Also up to version 2.4 it was 100% successful

Hmm, this is interesting. I looked deeply and 2.5 (portable) passed check [successfully](https://www.virustotal.com/gui/file/6048f524e7161c89269c07b097b9e2f3e71ee3f44ec769097e65b1ff3e7c5e83/detection). But 2.5.1 fails.
[Here](https://github.com/crow-translate/crow-translate/compare/2.5.0...2.5.1) is the full diff between them, but I do not see anything that can cause positive malware detection...

**Comment by boromyr** [comment]
Here, surely it is a detection error with the latest changes.
Do I change the title by adding "false positive"? Maybe some users who read only the title worry unnecessarily.

**Comment by Shatur95** [comment]
> Here, surely it is a detection error with the latest changes.

Yes, I really wonder why :) I initially assumed that the problem was in all versions, but if the problem is in the latest version, then I can easily find out what the reason is. I will try to bisect the commits.
Of course there is no real problem here, but I'm wondering what change causes false-positive malware detection.

> Do I change the title by adding "false positive"? Maybe some users who read only the title worry unnecessarily.

Yes, that's a good idea :)

**Comment by lucas-jsvd** [comment]
Today Microsoft Security dropped Crow Translate from my computer for the same reason.

**Comment by Shatur95** [comment]
Strange, but I was unable to reproduce the problem on my computer. Local build passes VirusTotal. It looks like it's either the Qt version or the compiler used in GitHub Actions caused the issue.
I've rebuilt Crow manually and updated the binaries in the [Releases section](https://github.com/crow-translate/crow-translate/releases). Please re-download from there if you have problems with your antivirus.
