### ISSUE TITLE
Transliterated text instead of translated by copy-paste

### ISSUE THREAD

**Issue by qg0** [crow-translate/crow-translate#176]
Linux KDE verson 2.5.1.

I had some strange behavior when copied translated text by right click and choose the option "copy":
Text in Russian:  "**Какой-то текст для перевода**".
Translated text in English or other language: "**Some text for translation**".
When I copy and paste the text in other app, for example Telegram, I've got **transliterated** text "**Kakoj-to tekst dlya perevoda**".
But if I copy the text with the button in right bottom corner, then it's normal translated text.
The problem occurs sometimes. Most of the time the copied text is normal.

**Comment by Shatur95** [comment]
> I had some strange behavior when copied translated text by right click and choose the option "copy":

Perhaps you have selected transilteration before the copy? `Right mouse button -> Copy` allows you to copy the selected text.

**Comment by qg0** [comment]
Yeah, I guess I had selected the transliterated text because there was a big text, so I didn't notice the translated text above. But the question is why the transliterated text even there?
I've just noticed the options to turn off a transliteration in the settings.
It wasn't so obvious. Maybe some background or the hint on this text is needed? Because it looks like this:

![image](https://user-images.githubusercontent.com/919099/92845613-5d96b280-f411-11ea-895d-8f4051393bde.png)

I don't know, maybe some line is needed with the title "transliterated text below" in the input or the different textarea and the button to show and hide this area?

e.g.:
```
Translated text
<hr>
### SEE THE TRANSLATED TEXT ABOVE
<hr>
### SEE THE TRANSLITERATED TEXT BELOW
<hr>
transliteration text

```

or like this:
_____________________________________________
original.............| translated text textarea.2........|
text....................|______________________________|
textarea..1.......| transliterated text textarea..3|
____________________________________________|

Maybe the hint is needed on the mouse hover "it's the transliterated text, see translated text above".

The problem is that you could work quickly and copy-paste the wrong text in the document and you couldn't notice this if you are sleepy working at night with no coffee.

Maybe it's a good way to turn off this transliteration options by default?

**Comment by Shatur95** [comment]
Usually all translators show transliteration. I made it a different color to make it stand out visually. It seems to me that if I separate it more explicitly, then it will still not solve your problem (it will still be difficult to select). It is best to use the hotkey (<Kbd>Ctrl</Kbd> + <Kbd>Shift</Kbd> + <Kbd>C</Kbd>) to copy the translation. Also you can use copy button by mouse. Or just turn off the display of transliteration, which you did.

**Comment by qg0** [comment]
> Usually all translators show transliteration. 

As you see Google Translate has a space between translated text and transliterated text and the different font size and text is hidden (show more/show less):

![image](https://user-images.githubusercontent.com/919099/92929625-0c1b1180-f46b-11ea-84e4-d848940906d8.png)

But in crow translate it right after the translated text:

![image](https://user-images.githubusercontent.com/919099/92930731-ab8cd400-f46c-11ea-8b9f-42b11410d5dd.png)

There are no transliterated text at all:

Bing:

![image](https://user-images.githubusercontent.com/919099/92929910-821f7880-f46b-11ea-8eb9-2e4f93b4d703.png)

Yandex:
![image](https://user-images.githubusercontent.com/919099/92929962-95324880-f46b-11ea-9a9e-3da232939484.png)

I understand now that I could turn off this but new users could not know this possibility or even won't notice.

**Comment by Shatur95** [comment]
Got your point. Add a newline is a reasonable.
And I will make transliteration disabled by default. Never need it :)
