### ISSUE TITLE
"Play text" is not working on Linux Mint

### ISSUE THREAD

**Issue by j41rj** [crow-translate/crow-translate#177]
I'm using Linux Mint 19.3.
I've already installed gstreamer1.0-fluendo-mp3
Translation works fine, but when i click "play source text", it does not work.

**Comment by Shatur95** [comment]
Hello! Could you try to install `qtgstreamer-plugins-qt5 gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-pulseaudio libqt5multimedia5-plugins`?

**Comment by j41rj** [comment]
It works! Thanks

**Comment by Shatur95** [comment]
Will add this packages as recommended dependency.

**Comment by sikmir** [comment]
@Shatur I have the same problem on NixOS, I've tried to add  `gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad` as dependencies, but it doesn't help. On NixOS we don't have something like `qtgstreamer-plugins-qt5` or `libqt5multimedia5-plugins` and audio just works in another `qtmultimedia`-based apps. Have you any idea how to troubleshoot it to figure out what exactly missed? Maybe some logging could help?

**Comment by Shatur** [comment]
I would suggest to take a look at the files in the mentioned Ubuntu packages and find similar for NixOS.

**Comment by sikmir** [comment]
> I would suggest to take a look at the files in the mentioned Ubuntu packages and find similar for NixOS.

Oh, I've managed to get it work on NixOS!

**Comment by Shatur** [comment]
Nice to hear!
