### ISSUE TITLE
Add the ability to set translation notification display time

### ISSUE THREAD

**Issue by Shatur95** [crow-translate/crow-translate#184]
Currently, notifications with translation are displayed for 3 seconds ([code](https://github.com/crow-translate/crow-translate/blob/ce7b93531b77ca6491ddb5781d3401ebc6103e9f/src/mainwindow.cpp#L386)). It would be nice to add the ability to configure it. There is a [AppSettings](https://github.com/crow-translate/crow-translate/blob/master/src/settings/appsettings.h) class and [SettingsDialog](https://github.com/crow-translate/crow-translate/blob/master/src/settings/settingsdialog.h) for configuration UI.

**Comment by Shatur95** [comment]
@rainbowhxch, you have sent notification mode, maybe you want to look into it?

**Comment by rainbowhxch** [comment]
> @rainbowhxch, you have sent notification mode, maybe you want to look into it?

I'm very happy to help. I'll start tomorrow.

**Comment by rainbowhxch** [comment]
@Shatur95 PR has been submitted, please check.
