### ISSUE TITLE
Doesn't recognize Hebrew

### ISSUE THREAD

**Issue by JonMagon** [crow-translate/crow-translate#187]
**Bug description**
The application doesn't auto translate any text in Hebrew via Google and Yandex, it says "Ошибка: Не удается разобрать автоопределенный язык". With other right-to-left languages like Arabic seems to be working fine.

**Steps to reproduce**

1. Select the text below:
`עברִית היא שפה שמית, ממשפחת השפות האפרו-אסיאתיות, הידועה כשפתם של היהודים ושל השומרונים`
2. Press Ctrl + Alt + E

**Environment**

-   OS: KDE neon
-   Desktop environment: KDE
-   Crow Translate version: 2.5.1

**Comment by Shatur95** [comment]
Reproduced. Looks like an encoding problem...

**Comment by JonMagon** [comment]
Hm, Yandex engine works if remove spaces from the text.
Also spaces break Persian translation, but Google can translate it:
`فارسی یا پارسی یکی از زبان‌های هندواروپایی در شاخهٔ زبان‌های ایرانی جنوب غربی است که در کشورهای ایران`

**Comment by Shatur95** [comment]
Thanks for the report. Google was returning a different API for Hebrew.

> Hm, Yandex engine works if remove spaces from the text.
> Also spaces break Persian translation, but Google can translate it:

So, spaced at the end breaks Yandex translation?

**Comment by JonMagon** [comment]
I don't know for sure, but when I try to translate the text above via Yandex, I got
```
Error transferring https://dictionary.yandex.net/dicservice.json/lookupMultiple?text=فارسی یا پارسی یکی از زبان‌های هندواروپایی در شاخهٔ زبان‌های ایرانی جنوب غربی است که در کشورهای ایران&ui=ru&dict=fa-ru - server replied: Bad Request
```

**Comment by Shatur95** [comment]
Thanks, fixed too!
