### ISSUE TITLE
OCR Does not work on W7

### ISSUE THREAD

**Issue by toprak** [crow-translate/crow-translate#193]
**Bug description**
When I tried to capture the screen to the learn a vocabulary program stops itself.
**Steps to reproduce**

Use OCR's shortcut and select the are and see the result.
**Expected behavior**

**Screenshots**

**Environment**

-   OS: W7
-   Crow Translate version: 2.6.0

**Additional context**
I tried to find the bug, and opened the visual studio I found out that "Unhandled exception at 0x000000013F674D1F in crow.exe: 0xC000001D: Illegal Instruction." Also when I installed the translator I found out there were no traineddata I had to install by myself

**Comment by toprak** [comment]
Also tried to open disasembly on vs it directed me to that "000000013FE24D1F  vmovaps     xmmword ptr [rsp+20h],xmm6  
"

**Comment by Shatur95** [comment]
Can't reproduce on my Windows 10 :( Do you have Visual C++ Redistributable packages installed?

**Comment by toprak** [comment]
Yes, I guess all of them already installed.

**Comment by Shatur95** [comment]
Hmm... I noticed that the latest version does not have a system tray icon because of symbolic links (Windows doesn't handle them the same way Linux does). This worked with `git config --global core.symlinks true`, but it doesn't work in the new version. I changed the icon folder structure and used [Qt resource aliases](https://doc.qt.io/qt-5/resources.html#resource-collection-files-op-op-qrc) (I need exact name of the icon). So, I re-uploaded the release for Windows manually. Could you download the app again, maybe this will solve your problem?

**Comment by toprak** [comment]
It did not work as well.

**Comment by Shatur95** [comment]
Could you try to download [Tesseract CLI application](https://digi.bib.uni-mannheim.de/tesseract/) (v4.1, stable) and check if it works for you with [this](https://tesseract-ocr.github.io/tessdoc/Command-Line-Usage) commands?

**Comment by toprak** [comment]
I installed tesseract and cd into its directory and opened tesseract.exe on cmd it worked but still does not work the ocr in crow

**Comment by toprak** [comment]
Also I did install all trained data etc. it still does not work

**Comment by Shatur95** [comment]
So, the tesseract itself (`tesseract.exe`) can recognize characters from images, but Crow doesn't?
I suggested downloading the Tesseract to check if it works itself on your machine.

**Comment by Shatur95** [comment]
> Also when I installed the translator I found out there were no traineddata I had to install by myself

Yes, trained Tesseract models take about 300MB, so the application comes without them. I thought to add the ability to download from the application, but wanted to provide the first working version as soon as possible. Added #194.

> Also I did install all trained data etc

Yes, the app shouldn't crash at all. If your languages ​​are not downloaded, then Crow displays a message when trying to run OCR.

**Comment by toprak** [comment]
I tried to use it tesseract itself I screenshotted your comment and told to extract it to a txt file. "So, the tesseract itself ( tesseract.exe ) can recognize characters from images, but Crow doesn't?
I suggested downloading the Tesseract to check if it works itself on your machine.
" it gave this so it works

**Comment by Shatur95** [comment]
> it gave this so it works

Thanks. So, the problem in Crow, okay.

> Unhandled exception at 0x000000013F674D1F in crow.exe: 0xC000001D: Illegal Instruction."
> "000000013FE24D1F vmovaps xmmword ptr [rsp+20h],xmm6"

It looks like Crow executes AVX instructions for OCR. What's your processor?

**Comment by toprak** [comment]
Pentium g3260

**Comment by Shatur95** [comment]
Hm... It look like [your CPU](https://ark.intel.com/content/www/ru/ru/ark/products/87356/intel-pentium-processor-g3260-3m-cache-3-30-ghz.html) simply does not support AVX instructions set :(
I will try to provide a build [with disabled AVX instructions](https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)#disabling-avx-optimisations).

**Comment by toprak** [comment]
Pff, Why do I have such a bad luck every time and everywhere

**Comment by toprak** [comment]
Will you do that today or tommorrow according to your answer will go sleep :D

**Comment by Shatur95** [comment]
Could you try [this ](https://drive.google.com/file/d/1QJCte6jf1JzG1bOOuEuEyV0xBs9uGrRb/view?usp=sharing) version?

**Comment by toprak** [comment]
There you fucking go bro it fucking worked thank you

**Comment by Shatur95** [comment]
:D
I looked at the source code and it looks like Tesseract can detect instructions at runtime. I think they are not checked correctly in 4.1. This is probably why it is recommended to use 5.0 alpha for Windows. I will try to build it with 5.0.

**Comment by toprak** [comment]
Thank you so much bro finally!!! It was really worth to wait! Should I close it?

**Comment by Shatur95** [comment]
Could you also try [this](https://drive.google.com/file/d/1bNsUfM677UHxfiDlOOG5PG20iCoZq4K4/view?usp=sharing)?

**Comment by toprak** [comment]
Previous one is working I am using it right now but the latest one that you have sent did not work

**Comment by toprak** [comment]
Maybe it because I have installed tesseract 4.1?

**Comment by Shatur95** [comment]
> Previous one is working I am using it right now but the latest one that you have sent did not work

Thanks. I will upload cpu-independend version.

> Maybe it because I have installed tesseract 4.1?

I do not think so. The app was compiled with 5.0.
I will ask Tesseract developers about the issue. Could you also provide `tesseract --version`? To check detected CPU instructions.

**Comment by toprak** [comment]
tesseract v4.0.0.20190314
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.2.0
 Found SSE

**Comment by Shatur95** [comment]
Thanks!

**Comment by Shatur95** [comment]
The last check :) Could you download reuploaded binaries from[ the releases](https://github.com/crow-translate/crow-translate/releases/) page? Just to check if I uploaded the right version.

**Comment by Shatur95** [comment]
> tesseract v4.0.0.20190314

Could you provide this output on the latest ([0.5](https://digi.bib.uni-mannheim.de/tesseract/)) version?

**Comment by toprak** [comment]
I was afk let me check

**Comment by toprak** [comment]
> The last check :) Could you download re-uploaded binaries from[ the releases](https://github.com/crow-translate/crow-translate/releases/) page? Just to be sure that I uploaded the right version.

It is the correct one at least it worked on me,


> > tesseract v4.0.0.20190314
> 
> Could you provide this output on the latest ([0.5](https://digi.bib.uni-mannheim.de/tesseract/)) version?

tesseract v5.0.0.20190623
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libope
njp2 2.3.0
 Found SSE

**Comment by Shatur95** [comment]
Thank you!
