### ISSUE TITLE
Speech synthesis does not work - no sound

### ISSUE THREAD

**Issue by c29r3** [crow-translate/crow-translate#195]
**Bug description**
Speech synthesis does not work (no sound when click to play button)

**Steps to reproduce**

1.  Run `crow` via terminal  
2.  Settings --> Spech synthesis --> click  "Speak"  
3.  In terminal you may see error: `defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"` 

**Environment**

-   OS: Ubuntu 20.04.1 LTS x86_64
-   Desktop environment: Gnome
-   Crow Translate version: 2.6.0

**How to fix**
`sudo apt-get install libqt5multimedia5-plugins -y`

**Comment by Shatur95** [comment]
Hello! Yes, this package is necessary for speech synthesis. Crow Translate already have `libqt5multimedia5-plugins` in recommended dependencies.
