### ISSUE TITLE
Segmentation fault after OS update

### ISSUE THREAD

**Issue by wokawoka** [crow-translate/crow-translate#196]
**Bug description**
Yesterday I upgraded my Pop Os installation from 20.04 to 20.10 and, since then, crow refuses to start. Translating with crow from the command line correctly works.
I did try to remove the crow config file and also launch it in a clean environment ( $ env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow ) as suggested in this old issue https://github.com/crow-translate/crow-translate/issues/154 but in all cases I still get the same segmentation fault.
Other QT apps regularly work.
Any hint about how to solve this problem? Thank you very much!

**Steps to reproduce**
```
$ crow
Segmentation fault (core dumped)
```

**Expected behavior**
Crow interface runs normally like it always did

**Environment**

-   OS: Pop Os 20.10
-   Desktop environment: KDE 5.19.5
-   Crow Translate version:  2.6.0

**Comment by Shatur95** [comment]
Are you using Wayland after update to 20.10?

**Comment by wokawoka** [comment]
No, I'm still on Xorg

**Comment by Shatur95** [comment]
Hm... Very strange. Could you try to build Crow manually from scratch and launch in debugger?

You need to install QtCreator (`sudo apt install qtcreator`), clone this repo (`git clone https://github.com/crow-translate/crow-translate.git`), open project in QtCreator and press <kbd>F5</kbd>.

**Comment by wokawoka** [comment]
Thank you very much for replying.
I'm not familiar with QT building... Which of the many files in the repo should I open in QtCreator in order to open the project?
Thank you for your patience and for the extremely work you are doing with crow translate!

**Comment by Shatur95** [comment]
>  I'm not familiar with QT building... Which of the many files in the repo should I open in QtCreator in order to open the project?

Feel free to ask me any questions about it.
Open QCreator, navigate to `File->Open File or Project`. Then select [CMakeLists.txt](https://github.com/crow-translate/crow-translate/blob/master/CMakeLists.txt) file from the root of the repo. And then press <kbd>F5</kbd>.

>  Thank you for your patience and for the extremely work you are doing with crow translate!

No problem, always happy to help :)

**Comment by wokawoka** [comment]
This is the output that comes out in the General Messages section as soon as I load the CMakeLists.txt file (without pressing F5):

```
Running /usr/bin/cmake -S /home/looka/Downloads/crow/crow-translate -B /tmp/QtCreator-mpyCtu/qtc-cmake-wjYNJdPU '-GUnix Makefiles' -DCMAKE_BUILD_TYPE:String=Debug -DQT_QMAKE_EXECUTABLE:STRING=/usr/lib/qt5/bin/qmake -DCMAKE_PREFIX_PATH:STRING=/usr -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ in /tmp/QtCreator-mpyCtu/qtc-cmake-wjYNJdPU.
-- The CXX compiler identification is GNU 10.2.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Tesseract (missing: Tesseract_LIBRARY Tesseract_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTesseract.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:48 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/QtCreator-mpyCtu/qtc-cmake-wjYNJdPU/CMakeFiles/CMakeOutput.log".
CMake process exited with exit code 1.
Elapsed time: 00:01.
```

**Comment by Shatur95** [comment]
He cannot find Tesseract library. Let's install the dependencies: `sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev qtmultimedia5-dev libtesseract-dev`

**Comment by wokawoka** [comment]
Thank you.
Unfortunately I'm getting the same segmentation fault also in Qt Creator

```
Signal name : | SIGSEGV
-- | --
Signal meaning : | Segmentation fault

```

**Comment by Shatur95** [comment]
It's okay, could you show me QtCreator screenshot with segfault?

**Comment by wokawoka** [comment]
Sure

![image](https://user-images.githubusercontent.com/7824587/97453161-6134b900-192d-11eb-8eb9-6f2beeee69da.png)

**Comment by Shatur95** [comment]
Could you scroll to the beginning?
![изображение](https://user-images.githubusercontent.com/22453358/97453436-6817f780-193e-11eb-950f-e0c98f2473b0.png)

**Comment by wokawoka** [comment]
Thanks

![image](https://user-images.githubusercontent.com/7824587/97454362-97266d00-192e-11eb-8a6e-89960118a448.png)

**Comment by Shatur95** [comment]
QMediaPlayer? Hm...

Could you click on `<More>`?

**Comment by Shatur95** [comment]
Thanks. it looks like this is not the application issue.
You cannot create a new instance of `QMediaPlayer`. I'm pretty sure that if you run a program that uses it, you'll have the same problem. Could you try to install packages that can be related to the Qt Multimedia module? I think you are missing the runtime dependency.

**Comment by wokawoka** [comment]
I did try to look for qt multimedia packages but they look to be already installed. Strange, crow translate was perfectly working before the OS update yesterday .
Is QMediaPlayer used by crow for text to speech functions?

```
libqt5multimedia5-plugins is already the newest version (5.14.2-3).
qml-module-qtmultimedia is already the newest version (5.14.2-3).
```

**Comment by Shatur95** [comment]
>  Is QMediaPlayer used by crow for text to speech functions?

Yes.

Maybe you missing gstreamer plugins (QMediaPlayer use them internally)?

**Comment by wokawoka** [comment]
I did try to install every single gstreamer plugin package I could find in the repo but they all were already installed.
I'll wait and see if someone will come out with a solution after having experienced the same problem or I'll evaluate the idea of a clean reinstallation.
In the meanwhile I will miss crow translate a lot.
Thank you very much for the very useful job you are doing

**Comment by Shatur95** [comment]
>  I did try to install every single gstreamer plugin package I could find in the repo but they all were already installed.

Strange... I am using ArchLinux so I have all latest versions of packages. So, the problem can't be in library update. I think the problem is either in the system configuration or in the installed packages.

>  Thank you very much for the very useful job you are doing

You are welcome :)

**Comment by wokawoka** [comment]
I've noticed an error in Qt5 Configuration Tool.
It's showing this error "The QT_QPA_PLATFORMTHEME environment variable is not set (required value: qt5ct)." which I'm not sure was there before the OS upgrade.
I don't know if this last error could be related to my problem with crow translate. If so, then the QMediaPlayer problem should be a minor issue and not the root cause, or am I wrong?

![image](https://user-images.githubusercontent.com/7824587/97497734-e090af80-1962-11eb-965c-9df253eb5b77.png)

**Comment by Shatur95** [comment]
Worth a try. Set `QT_QPA_PLATFORMTHEME` to `qt5ct`.

**Comment by wokawoka** [comment]
Unfortunately setting QT_QPA_PLATFORMTHEME=qt5ct strangely introduced a lot of visual artifacts but didn't solve the segmentation fault. 

I just hope that the package updates in the following period will fix the qmediaplayer problem

**Comment by hiddenman** [comment]
Hi,

Just upgraded Ubuntu 20.04 to 20.10 and got mostly the same problem in the KDE DE. Crow doesn't even start.

I'm attaching the strace.log, not sure if it helpful.

Thank you.
[strace.log](https://github.com/crow-translate/crow-translate/files/5514121/strace.log)

**Comment by Shatur95** [comment]
@wokawoka even built the project from source and got the same thing. So, the problem not in the compiled binary.
Maybe the problem in missing dependency?

**Comment by Shatur95** [comment]
@hiddenman, could you install `qtgstreamer-plugins-qt5 gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-pulseaudio libqt5multimedia5-plugins`?

**Comment by yura04** [comment]
Similar behavior at Debian 10 xfce
Updated from 2.5.1 to 2.6.0

![image](https://user-images.githubusercontent.com/46564852/98657147-36455e80-234a-11eb-9835-73017aa5b3e8.png)

https://github.com/crow-translate/crow-translate/issues/196#issuecomment-724558311 installed new packages but didn't help

Feel free to ask for additional information

**Comment by hiddenman** [comment]
> @hiddenman, could you install `qtgstreamer-plugins-qt5 gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-pulseaudio libqt5multimedia5-plugins`?

Hi,

They are already installed:

gstreamer1.0-alsa is already the newest version (1.18.0-2).
gstreamer1.0-plugins-good is already the newest version (1.18.0-1ubuntu1).
gstreamer1.0-pulseaudio is already the newest version (1.18.0-1ubuntu1).
libqt5multimedia5-plugins is already the newest version (5.14.2-3).
qtgstreamer-plugins-qt5 is already the newest version (1.2.0-5ubuntu1).

**Comment by Shatur95** [comment]
@yura04, I think that this is another issue. Try to run in clean environment:

```bash
env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
```

@hiddenman, strange, at the moment I do not know what this may be connected with :(
I will try to reproduce on Live image later.

**Comment by hiddenman** [comment]
> @yura04, I think that this is another issue. Try to run in clean environment:

> @hiddenman, strange, at the moment I do not know what this may be connected with :(
> I will try to reproduce on Live image later.

Neither do i :(  I even tried to remove the config - didn't help.

**Comment by Shatur95** [comment]
I tried Ubuntu 20.10 and Kubuntu 20.10 live images and everything works from PPA and from the releases page.

**Comment by yura04** [comment]
it works with this output in the terminal 

![image](https://user-images.githubusercontent.com/46564852/98712597-2ac85680-238f-11eb-9dec-ff9522c1bb22.png)

There're also missing icons
![image](https://user-images.githubusercontent.com/46564852/98712493-0d938800-238f-11eb-8b31-201a630790ce.png)

**Comment by Shatur95** [comment]
@yura04, It starts in clean environment, so this means that the issue in your system configuration and not related to the app. To enable icons you need to set either `QT_QPA_PLATFORMTHEME=gtk2` or `QT_QPA_PLATFORMTHEME=qt5ct` (if you have qt5ct configured and installed) environment variables.

**Comment by hiddenman** [comment]
> I tried Ubuntu 20.10 and Kubuntu 20.10 live images and Crow works from PPA and from the releases page.

If i run it as:
`sudo -u another_user crow`
then it works (however, without icons as in the message above). So i suppose it's related to the theme or KDE/gstreamer settings somehow.

**Comment by hiddenman** [comment]
> @hiddenman, could you install `qtgstreamer-plugins-qt5 gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-pulseaudio libqt5multimedia5-plugins`?

Btw, this in the dmesg:

crow[3376]: segfault at 0 ip 00007f9c5fa8abc5 sp 00007ffc666aa800 error 4 in iHD_drv_video.so[7f9c5f971000+348000]

**Comment by hiddenman** [comment]
@Shatur95 It's definitely related to the gstreamer. For example, when i delete ~/.cache/gstreamer-1.0 and then launch the "crow", it takes some time to regenerate the cache and then it again fails.
Btw, it fails in this call:

_ZN12QMediaPlayerC1EP7QObject6QFlagsINS_4FlagEE(0x55f8dcfd5e20, 0, 0, 0x55f8dcfe4b40 <no return ...>


Not sure how to debug/configure the gstreamer nowadays.  Tried to remove bad/ugly plugins - didn't help.

**Comment by Shatur95** [comment]
@hiddenman, yeah, it's related to the gstreamer that used by `QMediaPlayer`. But I can't do anything about it :(
The problem is in gstreamer / Qt bug that caused by the system configuration. Try to debug which setting causes the issue.

**Comment by hiddenman** [comment]
> @hiddenman, yeah, it's related to the gstreamer that used by `QMediaPlayer`. But I can't do anything about it :(
> The problem is in gstreamer / Qt bug that caused by the system configuration. Try to debug which setting causes the issue.

I even tried to remove all dconf settings - didn't help.   Not sure where it stored its settings, so many places nowadays.

**Comment by Shatur95** [comment]
I would create a new user and start copying the settings from the home folder to it.

**Comment by batikanor** [comment]
Same problem for me. Purged and re-installed it multiple times but no good. 
```

$ crow -> 
Segmentation fault (core dumped)

$ sudo crow ->
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
error: XDG_RUNTIME_DIR not set in the environment.
Segmentation fault

$env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
Segmentation fault (core dumped)

$sudo env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
No protocol specified
qt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted



```

**Comment by Shatur95** [comment]
@batikanor, the issue with your system configuration. Try to run as a new user.

**Comment by hiddenman** [comment]
@Shatur95 Hi, Still trying to find the root cause.  Playing with config files didn't help at all. I tried to copy everything.
Looks like it's related to the DRI somehow.

Found this post:
https://askubuntu.com/questions/1287450/viber-executable-crashes-on-ubuntu-20-10

Viber crashes with exactly the same error for this guy:

`Oct 27 19:04:42 xxx kernel: [ 3782.065767] Viber[25573]: segfault at 0 ip 00007ff5e4804bc5 sp 00007fff2e7dc3b0 error 4 in iHD_drv_video.so[7ff5e46eb000+348000]`

I always have this:

`crow[3518687]: segfault at 0 ip 00007fa2585bbbc5 sp 00007fffe39a8d90 error 4 in iHD_drv_video.so[7fa2584a2000+348000]
`

Not sure how to debug it further.

**Comment by hiddenman** [comment]
@Shatur95 Just found a workaround:

LIBVA_DRIVER_NAME=vdpau  crow

That helps and crow works.

These are possible values (from ArchLinux wiki):

Intel graphics:

- For libva-intel-driver use i965.
- For intel-media-driver use iHD.

NVIDIA:

- For Nouveau use nouveau.
- For NVIDIA use vdpau.

ATI/AMD:

- For AMDGPU driver use radeonsi.
- For AMD Catalyst use fglrx.

**Comment by Shatur95** [comment]
Nice to hear! But it's really strange that it requires manual intervention after the OS update.

**Comment by wokawoka** [comment]
I confirm that this solution works!
The strange thing is here crow starts with any of the above values:
LIBVA_DRIVER_NAME=vdpau crow
LIBVA_DRIVER_NAME=i965 crow
LIBVA_DRIVER_NAME=ihd crow
LIBVA_DRIVER_NAME=noveau crow
they all launch crow correclty without any difference.

with just "crow" via command line I just continue to get:
Segmentation fault (core dumped)


> @Shatur95 Just found a workaround:
> 
> LIBVA_DRIVER_NAME=vdpau crow
> 
> That helps and crow works.
> 
> These are possible values (from ArchLinux wiki):
> 
> Intel graphics:
> 
>     * For libva-intel-driver use i965.
> 
>     * For intel-media-driver use iHD.
> 
> 
> NVIDIA:
> 
>     * For Nouveau use nouveau.
> 
>     * For NVIDIA use vdpau.
> 
> 
> ATI/AMD:
> 
>     * For AMDGPU driver use radeonsi.
> 
>     * For AMD Catalyst use fglrx.

**Comment by toprak** [comment]
[fuchi@weeb ~]$ crow
Error: LSTM requested, but not present!! Loading tesseract.
After attemption of OCR
Error opening data file /usr/share/tessdata/tur.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'tur'
Error: LSTM requested, but not present!! Loading tesseract.
Segmentation fault (core dumped)

**Comment by Shatur95** [comment]
Which version of Tesseract are you using?

**Comment by toprak** [comment]
Here you go
```
[fuchi@weeb ~]$ tesseract -v
tesseract 4.1.1
 leptonica-1.80.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.0.5) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 1.1.0
 Found SSE
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.5

```

**Comment by Shatur95** [comment]
This is not related to the issue. Could you open a new one with detailed information (see template)?

**Comment by Shatur95** [comment]
I believe that the issue can be closed, since nothing can be done from the Crow side.
