### ISSUE TITLE
Can't load/start GUI

### ISSUE THREAD

**Issue by 7954ever** [crow-translate/crow-translate#197]
Hi. I'm a new user to this and I can use the shell commands without issues. But when I try to start the GUI I get this:

crow
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209
Segmenteringsfel (minnesutskrift skapad)

(Segment error log created)

Any idea what this could be? //B

(Installed the .deb file on Linux Mint Debian Edition 4 (debbie) which is based on Debian 10 Buster)

**Comment by Shatur95** [comment]
Try to run in clean environment:

```bash
env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
```

**Comment by 7954ever** [comment]
Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

**Comment by toprak** [comment]
Did you install tesseract language packages?

**Comment by 7954ever** [comment]
I just installed the required dependencies and the recommends and suggests. But I will now. :)

**Comment by Shatur95** [comment]
So, it runs in clean environment? It means that something wrong in your system configuration. I'm pretty sure that other Qt application will behave the same.

> I just installed the required dependencies and the recommends and suggests. But I will now. :)

Yes, OCR languages ​​are optional and should be installed manually.

**Comment by 7954ever** [comment]
When I installed the tesseract-ocr everything runs smoothly (GUI) so you maybe should make the tesseract to a required dependency?

**Comment by 7954ever** [comment]
And no. No other qt problems.

**Comment by Shatur95** [comment]
> When I installed the tesseract-ocr everything runs smoothly (GUI) so you maybe should make the tesseract to a required dependency?

We already have `libtesseract4` as a required dependency. 

The error `Tesseract couldn't load any languages!` just says that you do not have any language packs, the application will continue working.
`tesseract-ocr` is just a command line tool that Crow doesn't need, but has` tesseract-ocr-eng` as a required dependency, so this fixed the error after installation.

Your crash with `!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209` was related to your system configuration.
