### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by emmegamma** [crow-translate/crow-translate#198]
**Bug description**
All icons are missing: in the main window, in the system tray, and in the dock (the main window appears as a non-iconed window even if the app launcher is docked).

**Screenshots**
Overwiew: the main app only shows language icons; the tray icon is substituted by the default triple dots; the docker shows no icon.
![crow_icons_missing](https://user-images.githubusercontent.com/36104032/97801153-0b1c8a00-1c3b-11eb-8ac1-1fcab3b219d0.png)

Detail: though the Crow Translate launcher is docked, the Crow window is not attached to it, and appears as a separate window with no icon
![crow_dock](https://user-images.githubusercontent.com/36104032/97801157-1cfe2d00-1c3b-11eb-8919-790ff51f8bc3.png)

**Environment**

-   OS: Ubuntu 20.04 focal
-   Desktop environment: default Gnome, any theme (dark or light)
-   Crow Translate version: 2.6.0 (from the jonmagon/crow-translate PPA)

**Additional context**

When launching from terminal, I see a `QSystemTrayIcon::setVisible: No Icon set` message:

    $ crow  
    qt5ct: using qt5ct plugin
    qt5ct: D-Bus system tray: yes
    defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
    defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
    QSystemTrayIcon::setVisible: No Icon set
    Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
    Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
    Failed loading language 'eng'
    Tesseract couldn't load any languages!

**Comment by Shatur95** [comment]
Could you try to install `libqt5svg5`?

**Comment by emmegamma** [comment]
I tried, but I already have `libqt5svg5` installed.

I just noticed [after googling a little](https://github.com/keepassxreboot/keepassxc/issues/683) that the issue is somehow related to the `QT_QPA_PLATFORMTHEME` environmental variable, which is by default set to `qt5ct` on my system

However, if I launch
 `$ QT_QPA_PLATFORMTHEME=kde crow` 
the result looks much more similar to what expected (icons show), though the theme does not follow the desktop theme and the main window is still undocked from the launcher:
![crow_icons_kde](https://user-images.githubusercontent.com/36104032/97801621-584e2b00-1c3e-11eb-9e12-e43c4f0ac972.png)

**Comment by Shatur95** [comment]
Yes, this is a possible solution. I think you can also try `QT_QPA_PLATFORMTHEME=gtk2` to make it follow your desktop theme.

But the best solution for you is to fix `qt5ct` settings. Could you open `qt5ct` and play around with its settings?

**Comment by emmegamma** [comment]
Alright! That seems to solve it!

I changed the icon theme in qt5ct, so I suppose it must have been unset or set to an old theme. Oddly, I didn't notice issues with any other app: VLC and Kdenlive do not follow qt5ct's icon theme?

As another option, `QT_QPA_PLATFORMTHEME=gtk2` also works.

Only the issue of the main window not docking to the launcher remains.

Anyway, now it is more than usable! Thanks

**Comment by Shatur95** [comment]
Nice to read :)

> Oddly, I didn't notice issues with any other app: VLC and Kdenlive do not follow qt5ct's icon theme?

Probably. Qt applications can also hardcode it's style.

> Only the issue of the main window not docking to the launcher remains.

Hm... Could you check if VLC/Kdenlive have the same issue?

**Comment by emmegamma** [comment]
> Hm... Could you check if VLC/Kdenlive have the same issue?

Well, I tried: Kdenlive does have the same issue, whereas VLC does _not_. I have looked at their .desktop files, but I could not find any useful difference..

(as for Crow, the icons are imperfect with all themes: Adwaita has no icons for the "copy to clipboard" buttons and "settings", and in the settings window only shows icons for 'OCR' and 'Speech synthesis'; Breeze only misses a 'Speech synthesis' icon in settings, but is not really integrated with Ubuntu/Gnome themes; GNOME has no icon for "copy all translation data to clipboard" and "settings", though the settings window and everything else looks ok; Humanity has no "settings" icon, and in the settings window the icons have different sizes. I can help finding adequate icons in the default Ubuntu theme, anyway)

**Comment by Shatur95** [comment]
> Well, I tried: Kdenlive does have the same issue, whereas VLC does not. I have looked at their .desktop files, but I could not find any useful difference..

Could you copy VLC's desktop file to the `~/.local/share/applications/` and replace `Name` and `Exec` with crow for testing?

> I can help finding adequate icons in the default Ubuntu theme, maybe?)

Yes, could you provide names for all missing icons?

**Comment by emmegamma** [comment]
> Could you copy VLC's desktop file to the `~/.local/share/applications/` and replace `Name` and `Exec` with crow for testing?

I did: no success, still works the same way (no matter if `Icon` is set to `vlc` or `crow-translate`: the main window shows separately with the correct icon; just to exclude an icon format issue..)

> > I can help finding adequate icons in the default Ubuntu theme, maybe?)
> 
> Yes, could you provide names for all missing icons?

I'll try that

**Comment by Shatur95** [comment]
> I did: no success, still works the same way (no matter if Icon is set to vlc or crow-translate: the main window shows separately with the correct icon; just to exclude an icon format issue..)

Interesting. Probably VLC have some custom workarounds for it...
Could you also try something like `qbittorrent`?

**Comment by emmegamma** [comment]
> Could you also try something like `qbittorrent`?

qbittorrent works fine, as did VLC. It also follows the qt5ct icon theme

> Yes, could you provide names for all missing icons?

I found these for Yaru: 

Settings: system-settings.png
(Alternative names for the same icon: preferences-system.png, preferences-desktop.png )

In the settings window:
Interface: 
![preferences-desktop-wallpaper](https://user-images.githubusercontent.com/36104032/97803698-5343a880-1c4b-11eb-9e1f-2cc8f6489f7d.png) preferences-desktop-wallpaper.png is probably the best. Otherwise, 
![preferences-color](https://user-images.githubusercontent.com/36104032/97803744-9a319e00-1c4b-11eb-933f-304531054c36.png) preferences-color.png
Shortcuts: input-keyboard.png


However, as a suggestion, in the main window you could use symbolic icons (only B/W, scalable, somewhat more elegant):
media-playback-start-symbolic.svg
media-playback-stop-symbolic.svg
edit-copy-symbolic.svg
edit-select-all-symbolic.svg (for "copy all translation data"?)
system-settings-symbolic.svg

and for the clear button: edit-clear-all-symbolic.svg (or edit-clear-symbolic.svg alternatively)

**Comment by Shatur95** [comment]
> qbittorrent works fine, as did VLC. It also follows the qt5ct icon theme

Perhaps this is because Crow uses an API to display playback progress, while qBitorrent and VLC do not.

> Settings: system-settings.png

Breeze (KDE default) and Papirus do not have this icon.
`preferences-system.png`, `preferences-desktop` do not have symbolic variants. Is there any other symbolic settings icon?

>  Interface:

`preferences-desktop-wallpaper` and `preferences-color` looks worse than `preferences-desktop-theme` (current). Maybe this icon should be requested in the [yaru](https://github.com/ubuntu/yaru/find/master) repo?

> However, as a suggestion, in the main window you could use symbolic icons (only B/W, scalable, somewhat more elegant):

Agree.

**Comment by emmegamma** [comment]
> Perhaps this is because Crow uses an API to display playback progress, while qBitorrent and VLC do not.
I do not know..

As for the theme, it took me a while to understand the issue of the KDE-Gnome (Ubuntu's version) crosstalk. If I understood correctly, Breeze is KDE-based, so it has `preferences-desktop-theme` but not `system-settings`. Viceversa, Yaru has the latter and not the former because it is (Ubuntu's) Gnome 3-based (no theme selection in Gnome!).
So the challenge is to find icon names that exist in both versions, and that look acceptably nice as well. Right?

> `preferences-system.png`, `preferences-desktop` do not have symbolic variants. Is there any other symbolic settings icon?

I guess the simple answer is: they do have symbolic variants, `preferences-system-symbolic.svg` and `preferences-desktop-symbolic.svg` .  If I understood the crosstalk issue correctly, I'm not sure how to solve it here.

> `preferences-desktop-wallpaper` and `preferences-color` looks worse than `preferences-desktop-theme` (current). Maybe this icon should be requested in the [yaru](https://github.com/ubuntu/yaru/find/master) repo?

That's a possibility. Maybe they can simply import/inherit that of Ubuntu-Mono:
![image](https://user-images.githubusercontent.com/36104032/97811583-d2e96b80-1c7b-11eb-9c97-66db14033507.png)

(oddly, I noticed that it is the icon of qt5ct. In fact, in qt5ct.desktop, `Icon=preferences-desktop-theme`. So it seems that Yaru actually inherits icons from Ubuntu-Mono, but then I'm not sure why it cannot find it for Crow..)

**Comment by Shatur95** [comment]
>  So the challenge is to find icon names that exist in both versions, and that look acceptably nice as well. Right?

Exactly :)

> If I understood the crosstalk issue correctly, I'm not sure how to solve it here.

Yes... Maybe Ubuntu-Mono have such icon? How about `configure` icon?

> (oddly, I noticed that it is the icon of qt5ct. In fact, in qt5ct.desktop, Icon=preferences-desktop-theme. So it seems that Yaru actually inherits icons from Ubuntu-Mono, but then I'm not sure why the icon cannot be found for Crow..)

This is a `qt5ct` issue. Could you try with `QT_QPA_PLATFORMTHEME=gtk2`

**Comment by Shatur95** [comment]
> Maybe Ubuntu-Mono have such icon? How about configure icon?

I figured it out. I can use `settings-configure` icon that available in KDE and will fallback to `settings` on Gnome themes.

**Comment by emmegamma** [comment]
> This is a `qt5ct` issue. Try with `QT_QPA_PLATFORMTHEME=gtk2`

Nop, still no Interface icon..

> Yes... Maybe Ubuntu-Mono have such icon? How about `configure` icon?

Ok, I should have checked but Yaru actually inherits Humanity, not Ubuntu-Mono. Anyway, Humanity has both preferences-system and preferences-desktop. Notice they are colourful rather than symbolic.

`preferences-system`:
![image](https://user-images.githubusercontent.com/36104032/97846302-17adea80-1cee-11eb-973a-d3b6dee6bc95.png)

`preferences-desktop`:
![image](https://user-images.githubusercontent.com/36104032/97846239-01079380-1cee-11eb-929b-770a397513a1.png)

> I figured it out. We can use `settings-configure` icon that available in KDE and it will fallback to `settings` on Gnome themes.

There is not an icon named `settings` in either Yaru, Ubuntu-Mono or such, but I guess you meant `system-settings` right?

**Comment by Shatur95** [comment]
> Nop, still no Interface icon..

Strange, the icon should be inherited. This is definitely not an application issue. All this thing managed by Qt and your `qt5ct` styling.

> Yaru actually inherits Humanity

Oh, got it. But we should find symbolic variant or just request a new icon for it.

> There is not an icon named settings in either Yaru, Ubuntu-Mono or such, but I guess you meant system-settings right?

Sorry, I just overlooked. `system-settings` does not exists in all other non-Gnome themes.

**Comment by emmegamma** [comment]
> Strange, the icon should be inherited. This is definitely not an application issue. All this thing managed by Qt and your `qt5ct` styling.

There is something weird, as I can see an icon if I change the theme in qt5ct _while_ the settings window is opened. However, it's not the correct one (it's the system-settings/preferences-system/preferences-desktop or however you may call it), and if I close and open the settings again, it's gone.
![image](https://user-images.githubusercontent.com/36104032/97852964-bee34f80-1cf7-11eb-893d-426404151a8a.png)
Conversely, if I change the icon theme to Breeze while the settings are open, no icon shows for "Interface". I must close and open the settings to see it.
I will do some testing with a clean profile ASAP, anyway, to confirm where the issue comes from.

> Oh, got it. But we should find symbolic variant or just request a new icon for it.

Well, there IS a symbolic variant (see [previous comment](https://github.com/crow-translate/crow-translate/issues/198#issuecomment-720135210)), so the request would likely be rejected. But asking is for free!
Possible solution: `emblem-system-symbolic` exists in both Yaru and Breeze.
As far as I understand, symbolic icons exist and only need to be... called! 
Though I do see that using Breeze, symbolic icons are used..so I'm not getting it :)

**Comment by Shatur95** [comment]
>  I will do some testing with a clean profile ASAP, anyway, to confirm where the issue comes from.

It would be awesome.

> Well, there IS a symbolic variant (see previous comment), so the request would likely be rejected. But asking is for free!

But missing in Breeze. It's okay to request the same icon with a different name. It will be done via symlink as all other themes do.

>  Possible solution: emblem-system-symbolic exists in both Yaru and Breeze.

Unfortunately, `emblem-system-symbolic` is emblem and have a bit different meaning in other themes.

>  Though I do see that using Breeze, symbolic icons are used..so I'm not getting it :)

Yeah, Breeze use symbolic-like icons for small icons on buttons by default. And Papirus too. That's why I did not know about colored icons in other users. However, I already fixed it in master :) But need to decide that to do with settings icon.

**Comment by Shatur95** [comment]
[Requested](https://github.com/ubuntu/yaru/issues/2471) :)

**Comment by emmegamma** [comment]
Great! Let's see what happens :)
Thank you

**Comment by Shatur95** [comment]
Do you expect the same behavior with `QT_QPA_PLATFORMTHEME=gtk2`? If yes, the issue could be in Qt itself.

How it look in my system:

Breeze:
![изображение](https://user-images.githubusercontent.com/22453358/97962535-13e99900-1dbe-11eb-8360-2db85e56d98c.png)

Suru:
![изображение](https://user-images.githubusercontent.com/22453358/97966917-20bdbb00-1dc5-11eb-8350-83fa7bbf1341.png)

Yaru:
![изображение](https://user-images.githubusercontent.com/22453358/97966841-0be12780-1dc5-11eb-8874-d5823ff53d63.png)

**Comment by emmegamma** [comment]
Okay, so on your system (KDE-based, I assume) it does look ok!

> Do you expect the same behavior with `QT_QPA_PLATFORMTHEME=gtk2`? If yes, the issue could be in Qt itself.

Yes, or well: I tried, and the result is the same.

**Comment by Shatur95** [comment]
> Yes, or well: I tried, and the result is the same.

Hm... So, the issue not in `qt5ct`. `gtk2` here is a style provided by Qt itself.
I also asked a friend who uses XFCE, he said that everything looks good too.
I will check it on the other distro with Gnome.

**Comment by Shatur95** [comment]
I've tested Manjaro Gnome, Ubuntu Gnome 20.04, and Manjaro XFCE. They all have this problem. But in KDE, all icons are present.

I digged deeper and found that KDE uses different icon matching algorithm. For example, I used `audio-speakers` for sound. There is no such icon in Breeze, so it result is missing icon on GTK-based environments, but KDE fallbacks to `audio-x-generic`. In latest master I replaced `audio-speakers` with more common `preferences-desktop-sound`. So, with Breeze all icons will exists even in GTK-based environments.

Another issue is that in GTK-based environments, icons are not inherited for themes. For example, the Yaru icons that exist in the Humanity theme are missing in Qt applications.

The only solution is to bundle an icon theme with the application and use it as a fallback to provide more out of the box experience. I will try it do it later.
As a temporary solution for now I suggest you to try [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme. This theme have icons literally for everything. Or you can try any other theme that just have more icons.

**Comment by Shatur95** [comment]
I also noticed that the symbolic icon variants break the dark themes. So this change will have to be reverted :(

**Comment by emmegamma** [comment]
I see, so there's not really a solution there, only workarounds. I would think that this has to be considered a bug, anyway, to be reported to Yaru (or Gnome or Qt, I'm not sure which - but somebody will be).

> I also noticed that the symbolic icon variants break the dark themes. So this change will have to be reverted :(

Well, there's -dark variants for most themes. Not sure how they are selected, especially in case of inheritance (Yaru does not have a dark variant and inherits Humanity, not Humanity-Dark...yet I use a dark theme just fine), but well...

**Comment by Shatur95** [comment]
> Well, there's -dark variants for most themes. Not sure how they are selected, especially in case of inheritance (Yaru does not have a dark variant and inherits Humanity, not Humanity-Dark...yet I use a dark theme just fine), but well...

Yeah, not sure how GTK applications handle this, but with the dark theme Yaru symbolic icons will look in the following way:

![изображение](https://user-images.githubusercontent.com/22453358/98138539-e2f78a00-1ecb-11eb-9d68-93e4749e5620.png)

**Comment by emmegamma** [comment]
Well I kinda like it! :)  But I see the issue, yes.
And Papirus seems to have some troubles too (play and stop are more greyish than the other buttons)...
Dark themes have always been known to break everything!

I guess that reverting to plain icons is the easiest, surely, unless you want to become an expert in DE-based theming :) (I don't!)

**Comment by Shatur95** [comment]
>  And Papirus seems to have some troubles too (play and stop are more greyish than the other buttons)...

No, no, this buttons just disabled because there is not text for playback :)

> I guess that reverting to plain icons is the easiest, surely, unless you want to become an expert in DE-based theming :) (I don't!)

Yeah, this is a huge pain :D There is also Windows...

**Comment by emmegamma** [comment]
Hehe, well...great then, thanks for looking into it!

**Comment by toprak** [comment]
Well, I switched W7 to Arch Linux with i3-gaps but some icons are working some are not.
![2020-12-15-222644_1366x768_scrot](https://user-images.githubusercontent.com/43301560/102262925-b7cd7500-3f24-11eb-9a0e-fa6ade2db6e8.png)
![2020-12-15-222757_1366x768_scrot](https://user-images.githubusercontent.com/43301560/102262992-cf0c6280-3f24-11eb-98be-03ef3de9b503.png)

**Comment by Shatur95** [comment]
@toprak, this is a different issue :) You need to configure style for Qt applications. Check [this](https://wiki.archlinux.org/index.php/qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma) article on wiki or try to set `QT_QPA_PLATFORMTHEME=gtk2`.

**Comment by toprak** [comment]
It is still same let me try with xfce. I have lack of time so will try tomorrow and give the result to you

**Comment by Shatur95** [comment]
> It is still same

For i3 you also need to setup GTK theme to make `QT_QPA_PLATFORMTHEME=gtk2` work for you. Or try `qt5ct` as suggested in wiki (you should set theme icon and style in qt5ct settings and set `QT_QPA_PLATFORMTHEME=qt5ct`).

> I have lack of time so will try tomorrow and give the result to you

No problem. It's known "issue" and suggested steps should 100% work.

**Comment by toprak** [comment]
It works good now with XFCE. Thank you

**Comment by toprak** [comment]
I want to give a try again with i3, will give a shot on advancing hours of the day. I will give you feedback bro, stay tuned :D

**Comment by toprak** [comment]
QT_QPA_PLATFORMTHEME=gtk3 crow worked instead of gtk2. How can I use this command automatically?

**Comment by Shatur95** [comment]
There is a [wiki](https://wiki.archlinux.org/index.php/environment_variables) for such questions :)

**Comment by toprak** [comment]
I have to learn how to use wiki :D

**Comment by Shatur95** [comment]
Fixed by 78d7f6fb89031b370364eb19207a67b33603d261.

**Comment by emmegamma** [comment]
Great! Can't wait to try it out :)
