### ISSUE TITLE
Add DeepL Engine

### ISSUE THREAD

**Issue by studiosusmed** [crow-translate/crow-translate#199]
It would be very nice if deepl.com would be supported. It is such a high quality translator, that would really enrich crow translate. Thanks for your consideration!

**Comment by toprak** [comment]
Yup! Totally agree with @studiosusmed , it works as charm for jp->en also ru->en

**Comment by Shatur95** [comment]
The feature is already submitted, but just on the [QOnlineTranslator](https://github.com/crow-translate/QOnlineTranslator/issues/6) side. This would be a very nice addition, but currently I'm out of time for it, just polishing recently implemented OCR functionality. But if someone want to help with it - PR's are welcome :)
