### ISSUE TITLE
Network acces disable

### ISSUE THREAD

**Issue by toprak** [crow-translate/crow-translate#200]
**Bug description**
Program starts itself at starting of windows, and when you translate something this error shows up.

**Steps to reproduce**

1.  Go to tray
2.  Click on crow's icon
3.  type something to translate
4.  See error

**Expected behavior**
Succesful translation of written text

**Environment**

W7, latest crow.
**Additional context**
If you do shut down crow at task manager, and re-open crow and type something it would work.

**Comment by Shatur95** [comment]
Do you have any VPN enabled after startup?

**Comment by toprak** [comment]
No

**Comment by Shatur95** [comment]
Can reproduce on my machine too. Weird issue. I think that this can be a Qt bug. Will try to check.

**Comment by Shatur95** [comment]
Yes, this is a Qt / OpenSSL issue. But it works with the latest versions of them. This issue will not appear in the next release.

**Comment by Shatur95** [comment]
A new version has been released :)

**Comment by toprak** [comment]
I got it in 2.6.1 too

**Comment by toprak** [comment]
guess it is solved dunno :D

**Comment by Shatur95** [comment]
I do not quite understand you, is the problem present in 2.6.1?

**Comment by toprak** [comment]
Guess the 2.6.0 stayed open that's why I got it
