### ISSUE TITLE
Display full language in "Auto" button tooltip

### ISSUE THREAD

**Issue by VolkMilit** [crow-translate/crow-translate#207]
**Describe the solution you'd like**
When you move mouse cursor to "Auto" button, there is language code displaying into tooltip. I think it will be more clear, if full language name will be displaying.

**Comment by AlbertoFabbri93** [comment]
Maybe change the labels depending on the size of the tooltip?

**Comment by VolkMilit** [comment]
@AlbertoFabbri93, I'm not sure what you're talking about.
![image](https://user-images.githubusercontent.com/10182587/103257626-ed666980-49cc-11eb-93d5-93977cff300f.png)
What I meant was change `en` from tooltip (black square) to `English`.

**Comment by AlbertoFabbri93** [comment]
Oh ok, I agree, changing the tooltip makes a lot of sense
