### ISSUE TITLE
2 out of 8 cores 100% CPU usage bug

### ISSUE THREAD

**Issue by lazyletucce** [crow-translate/crow-translate#208]
**Bug description**
yesterday crow translate had a bug while running in background and started to use 100% of 2 cores (100% on one core and 90% on the 2nd) on my 8 cores cpu for no reason, i had to kill the process, there a way to find the cause? i'm using CopyQ clipboard manager, can it interfere? 

**Steps to reproduce**
idk it appeared randomly

**Environment**
-   OS: win 2004
-   Crow Translate version: 2.6.0

**Comment by toprak** [comment]
Did you try update crow to 2.6.1?

**Comment by Shatur95** [comment]
Yes, some race conditions were fixed in 2.6.1. Please try updating and let me know if the problem exists.

> i'm using CopyQ clipboard manager, can it interfere?

No, I use it on Windows too without any issues.

**Comment by Shatur95** [comment]
Feel free to reopen or ping me if the issue still exists on the latest version.
