### ISSUE TITLE
VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#209]
**Bug description**
The install process shows that the installation succeded, but it doesn't show in the Menu.

I did go to installation folder `C:\Program Files\Crow Translate\` and run directly the `crow.exe` file and I get an error:
![crow-error](https://user-images.githubusercontent.com/46356616/101061310-a84b4500-3590-11eb-87e5-57bbbb8097a9.png)

Downloaded again `crow-translate-2.6.1-win64.exe` and then tried the reinstall, but still it didn't fix the problem. I still get the same error.

**Comment by algent-al** [comment]
Also same result with `crow-translate-2.6.0-win64.exe`.

**Comment by Shatur95** [comment]
You should install [Visual C++ runtime](https://support.microsoft.com/ru-ru/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by algent-al** [comment]
Thank you. Installing  `Visual C++ runtime` fixes the issue of running it directly from the installation folder. The app doesn't add a shortcut to Menu.

**Comment by algent-al** [comment]
At least I add it to autostart.

**Comment by Shatur95** [comment]
Most likely you have not checked the add icon to the start menu in the installer.

**Comment by algent-al** [comment]
The check is to not create Shortcut
![shortcut](https://user-images.githubusercontent.com/46356616/101067898-5c9c9980-3598-11eb-8a49-5a02c5ebbf29.png)

**Comment by Shatur95** [comment]
But your screenshot already has a Crow Translate folder.
Is it empty?

**Comment by algent-al** [comment]
![crow-uninstall](https://user-images.githubusercontent.com/46356616/101068482-11cf5180-3599-11eb-8953-12d6b8237c44.png)

There is only the uninstall icon.

**Comment by Shatur95** [comment]
Thanks! Could you open a separate issue to let me track it?

**Comment by algent-al** [comment]
Ok.
