### ISSUE TITLE
Missing icon in Start Menu.

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#210]
**Bug description**
Missing icon in Start Menu to launch crow. The folder get created correctly but there is only the uninstall icon.

**Expected behavior**
Normally it should be at least an icon in Start Menu if not in Desktop.

**Screenshots**
![crow-uninstall](https://user-images.githubusercontent.com/46356616/101069120-de40f700-3599-11eb-9633-62e55ac0b859.png)

**Environment**
-   Windows 10 Pro build 19042
-   Crow Translate version: 2.6.1

**Comment by Shatur95** [comment]
Thanks for the report. I also re-uploaded the installer.

**Comment by algent-al** [comment]
Icon is installed successfully, but now the app is complainig about missing other four `dll` files:
`MSVCP140D.dll`
`VCRUNTIME140D.dll`
`VCRUNTIME140_1D.dll`
`ucrtbased.dll`

**Comment by algent-al** [comment]
The issue is fixed by installing again the old `crow-translate-2.6.1-win64.exe` that I had saved before.
Runs perfectly without any errors.

**Comment by Shatur95** [comment]
> Icon is installed successfully, but now the app is complainig about missing other four dll files:

Sorry, I accidentally uploaded the debug version :)
Re-uploaded.
