### ISSUE TITLE
Auto translate clipboard.

### ISSUE THREAD

**Issue by toprak** [crow-translate/crow-translate#211]
I think it would be great because sometimes ocr and selected text translation could not help you. For instance translating words from subtitle, ocr wont help you also you can not select words but with potplayer you can click words and send them to clipboard. Hope it is clear to understand :D. You can add it as an option that changeable from settings menu.

**Comment by Shatur95** [comment]
Sounds unclear to me :) Could you provide an example?

**Comment by toprak** [comment]
Sure, I recommended it because it would be really great feature for foreign language learners. 
![ex1](https://user-images.githubusercontent.com/43301560/101286144-f3b45c00-37f9-11eb-9c5e-8c0eb2d8b464.PNG)
If you try to ocr this sentence with crow, crow will give this "form yo ‘thatavoulwillinowibeginraimnew lifes" as result. 
But If the auto translate clipboard translation were added, the user could get the translation because of Pot Players word selection feature and if the user did the special setting on it like "copy the word the clipboard"
![ex2](https://user-images.githubusercontent.com/43301560/101286274-910f9000-37fa-11eb-9ba8-1eecdbc56cef.png)
If I do click the red box it will copy it my clipboard and I can translate it.

**Comment by Shatur95** [comment]
I do not think that automatically translating everything that is copied to the clipboard would be convenient even as an option. You will have to go into the settings every time and turn it off when you finish watching anime :)

Instead, you can simply use "Translate selected text shortcut" just now. If there is no selected text, the sentence from the clipboard will be translated automatically. I think that this is what you need.

**Comment by toprak** [comment]
Yes I was trying to use it but could not use it, it does not work with pot player I guess and as far as I know pot player is one video player that can select  text from subtitles

**Comment by Shatur95** [comment]
This is strange. Do you use Windows? Try copying some text to the clipboard. Then remove any selection. Then use the "Translate selected text" shortcut. Will you get a translation of the previous text that you copied to the clipboard?

**Comment by toprak** [comment]
Translating selected text is working, Yes I do use windows. It is probably because of pot player. it does not just work on pot player will try find some solution. Thanks

**Comment by toprak** [comment]
Guess found a solution, pot player has subtitle translation and it is able to show two subtitle at the same time, guess I can figure it out which words what it does mean.

**Comment by Shatur95** [comment]
Okay :)
