### ISSUE TITLE
Add support for structured output

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#213]
**Is your feature request related to a problem? Please describe**
If you translate a single word rather than a sentence, the output has a lot of useful extra information. I have some scripts that parse this information and format a subset of it in a more compact way. It would be convenient if the CLI had a `--json` flag or similar so I didn't have to do the parsing myself. My primary use case is quickly grabbing and translating any words I don't know from a line of subtitles. I then display the list in a popup window.

**Describe the solution you'd like**
Looking at sample output from the Google Translate backend, there are several pieces of information the structured output should make easy to access:

1. The search term
2. Pronunciation info
3. Primary definition
4. List of alternative translations grouped by part of speech (although having a flat list with the part of speech as a property of each word would probably be more convenient)
5. List of usage examples (not present in the example I posted)

```
私
(Watashi)

[ Japanese -> English ]

I

私 - translation options:
adjective
	private: 個人, 非公開, 私立, 私的, 私, 内聞

noun
	private affairs: 私

pronoun
	I: 私, 僕, 俺, 我, あたし, 小生
	myself: 自分, 私, 我が身, 私自身
```

A possible example JSON schema:

```jsonc
Translation
{
    translationProvider: string, // the caller should probably already know what this is, but it could be convenient if the schema ends up varying by provider
    search: string,
    pronunciation: string. // or possibly an array of strings, Google only seems to provide one pronunciation for Japanese even if there are multiple possibilities, I'm not sure if this varies by language or for the other backends though
    meaning: string,
    translationOptions: TranslationOption array,
    examples: string array
}

TranslationOption
{
    partOfSpeech: string,
    meaning: string,
    synonyms: string array
}
```

I haven't used the other providers very much, but as far as I can tell all three would fit this schema with `null` for the fields they lack.

**Describe alternatives you've considered**
- It's possible to pull out the required information manually in a script, but it's a bit of a hassle and likely to break if the output formatting ever changes.

- An alternative to JSON output would be accepting a format string of some type. I think this would probably be harder to implement though, especially as far as specifying the formatting for items nested in a list goes.

**Comment by Shatur95** [comment]
Hi! This is definitely possible, but I do not think that this is a best solution. Are you not satisfied with the popup / main window / notification modes? Maybe we can improve it?

**Comment by LiteracyFanatic** [comment]
## Background
I apologize in advance for the wall of text. I use crow a lot and once I started brain storming I came up with quite a few potential improvements. :smile: I can open separate issues for each suggestion if you would like.

In my language practice, I find that my focus and comprehension is much better if I can minimize context switching as much as possible. crow's different modes actually help a lot with that. I use the popup mode to check words I don't know while reading. This is a lot better than constantly switching to another tab with a translator open. When I'm writing, I keep the main window open to the side. As for the notification mode, I honestly forgot it existed until you mentioned it.

I also use the CLI tool from scripts quite a bit, mostly because of some oddities related to CJK languages. It can be quite annoying to select individual words with the cursor because Japanese doesn't have spaces between the characters. Browsers handle this pretty well; double clicking will usually select the part you want. Other programs like text editors leave you selecting by individual character. There is a command line program that can help with this called `mecab` which will automatically segment a sentence into individual parts.

And when watching a video, regardless of language, you can't simply highlight the subtitles to copy and paste them into crow. I use `mpv` as my video player, which is fortunately very easy to customize with lua scripts. I can get access to the current subtitle from within a lua script, pipe it to `mecab`, filter out a list of particles and common words, and then launch `rofi` in multiselect mode with a list of words that I'm likely to be interested in translating. Then I use crow's CLI tool to translate each selected word and display it with `rofi` in message mode. This is the part where I'd like to have access to translations in an easy way to format. I can do what I want with `awk` but it's ugly.

![2020-12-13T05:22:45-06:00](https://user-images.githubusercontent.com/18249574/102010956-f2f25d00-3d06-11eb-86f1-7be535ad3532.png)
![2020-12-13T05:23:12-06:00](https://user-images.githubusercontent.com/18249574/102010961-00a7e280-3d07-11eb-963d-3562ba313c44.png)

As far as I can tell, there currently isn't any way to launch crow's GUI with an arbitrary term for translation. The closest thing would be using a tool like `xclip` to simulate selecting the text and then calling `io.crow_translate.CrowTranslate.MainWindow.translateSelection` from D-BUS. That's a bit convoluted, but it works. However, I either have to watch the movie windowed, or switch back and forth between fullscreen mode every time I want to make a translation because the popup and main window can't show themselves on top of a fullscreen window. Again, it works, but it's extra button presses for an action I take frequently. I'm not sure why (it probably sets some sort of window hints for X) but `rofi` can display the list of translations even when the video is fullscreen.

Since you mentioned it, I tried out the notification mode and it worked with the video in fullscreen. However, the default display time of ~3 seconds is too short to be very useful for me.

## Potential Improvements
- Add window hints to make the popup and/or main window display over fullscreen windows
- Add a D_BUS method `io.crow_translate.CrowTranslate.MainWindow.translate` which accepts the text to translate as an argument and displays the result in the GUI window
- Add a paramater or option to control the window type from D-BUS
- Allow configuring a longer notification display time or ideally make notifications sticky until the user clears them by default (`notify-send -t 0` from the command line, I assume there is an equivalent D-BUS option)

**Comment by Shatur95** [comment]
Well, very impressive workflow :)

So, you need json output to have custom formatting in `rofi` messages? Maybe it will be better and easier if we improve the CLI output?

> Add window hints to make the popup and/or main window display over fullscreen windows

This is definitely should be added. Qt have [windows flags](https://doc.qt.io/qt-5/qt.html#WindowType-enum) that can used [here](https://github.com/crow-translate/crow-translate/blob/86e1cccc9e28929af443c2368f8ca707e9b4037e/src/popupwindow.cpp#L39). Are you familiar with C ++? Could check if `Qt::Popup` instead of `Qt::Window | Qt::FramelessWindowHint` works for you? If yes, I think it worth to add a setting for it instead of a D-Bus command. 

> Since you mentioned it, I tried out the notification mode and it worked with the video in fullscreen. However, the default display time of ~3 seconds is too short to be very useful for me.

You can specify notification display time in settings. Take a look at the interface settings.

**Comment by LiteracyFanatic** [comment]
> Well, very impressive workflow :)

Haha, thanks. The curse of programming is suddenly wanting to automate everything.

> So, you need json output to have custom formatting in rofi messages? Maybe it will be better and easier if we improve the CLI output?

Sure I think modifying the CLI output would be a valid approach too. "Better" probably depends on who you ask, but I'd like if it where more compact. I'd remove the parentheses from around the pronunciation. I already know the source and target languages, so this information is redundant. Maybe it could be displayed only when autodetecting the source language. If it is displayed, I think it would make more sense to put it at the top so it doesn't interrupt the flow of reading when you move from the pronunciation to the translation. The two trailing newlines at the end could be reduced to a single one and I'd remove the blank lines except for the one between the main and alternate translations. I'd also delete the `translation options:` line. That almost cuts the line count in half. Again, some people might prefer having the extra spaces and information. To me it's more important to be able to fit several translations back to back with a large text size for easy reading.

```
私
(Watashi)

[ Japanese -> English ]

I

私 - translation options:
adjective
	private: 個人, 非公開, 私立, 私的, 私, 内聞

noun
	private affairs: 私

pronoun
	I: 私, 僕, 俺, 我, あたし, 小生
	myself: 自分, 私, 我が身, 私自身

```

```
私
Watashi
I

adjective
	private: 個人, 非公開, 私立, 私的, 私, 内聞
noun
	private affairs: 私
pronoun
	I: 私, 僕, 俺, 我, あたし, 小生
	myself: 自分, 私, 我が身, 私自身
```

> Could check if Qt::Popup instead of Qt::Window | Qt::FramelessWindowHint works for you?

`Qt::Popup` does the trick. I love it when things are easy.

> If yes, I think it worth to add a setting for it instead of a D-Bus command.

I think I might not have been clear enough before, I was suggesting exposing the existing Translation Mode (popup/main window/notification) through the D-BUS interface. Something like `io.crow_translate.CrowTranslate.MainWindow.getTranslationMode` and `io.crow_translate.CrowTranslate.MainWindow.setTranslationMode` could be used in conjunction with `io.crow_translate.CrowTranslate.MainWindow.translate` to display a translation in the desired window type. Otherwise the script would be nondeterministic because the result would depend on the user's preferred window type for interactive use.

> You can specify notification display time in settings. Take a look at the interface settings.

Woops, I completely missed the notification time setting.

**Comment by Shatur95** [comment]
Got your point. Yes, this is very personal. Probably json output will be better.

> Qt::Popup does the trick. I love it when things are easy.

Thanks, I will use this flag instead.

> I think I might not have been clear enough before, I was suggesting exposing the existing Translation Mode (popup/main window/notification) through the D-BUS interface.

Got it. But I think it will be better to just add an additional argument to `void io.crow_translate.CrowTranslate.MainWindow.translateSelection();` with translation mode. What do you think?

**Comment by LiteracyFanatic** [comment]
Yeah, I think that'd be better too. That's less effort than saving, modifying, and restoring a setting.

**Comment by Shatur95** [comment]
Okay, set `Qt::Popup` is and an additional optional argument is easy. Will add it.

But adding `--json` requires a real testing. Could you try to implement and test it? It's easy:

1. Clone [QOnlineTranslator](https://github.com/crow-translate/QOnlineTranslator).
2. Go to `qonlinetranslator.h` and add a new method called `toJson` [here](https://github.com/crow-translate/QOnlineTranslator/blob/c7f920963cfedb42bc854c9439e65b1fd964427f/src/qonlinetranslator.h#L207). Use [QJsonDocument](https://doc.qt.io/qt-5/qjsondocument.html) (don't be afraid, the API is very simple!) to just generate json from [these](https://github.com/crow-translate/QOnlineTranslator/blob/c7f920963cfedb42bc854c9439e65b1fd964427f/src/qonlinetranslator.h#L344) variables.
3. Try any example from the README.md and use newly added function to test the result.

**Comment by LiteracyFanatic** [comment]
Sure, I'd be glad to give it a shot. Thanks for the guidance.

**Comment by Shatur95** [comment]
Thank! Feel free to ask me any questions about it.

**Comment by Shatur95** [comment]
Unfortunately, `Qt::Popup` hint do not allow open dialog to edit languages. But `Qt::Tool` did the trick (works for fullscreen windows and allows to select languages from dialog without closing the pop-up).
