### ISSUE TITLE
Ubuntu 20.10 could not start version 2.6.1

### ISSUE THREAD

**Issue by linhnd1303** [crow-translate/crow-translate#214]
**Bug description**
Ubuntu 20.10 could not start version 2.6.1. Even I tried to install in many way 

**Environment**

-   OS: Ubuntu
-   Desktop environment: KDE
-   Crow Translate version: 2.6.1

**Comment by Shatur95** [comment]
I think it's duplicate of #196. The issue related to the system configuration.
