### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by toprak** [crow-translate/crow-translate#215]
**Bug description**
After an attemption of ocr to scan something, it gave Segmentation fault (core dumped).
**Steps to reproduce**
Steps to reproduce the behavior: o

1.  open app
2.  try to ocr.

**Expected behavior**
Work as normal as always

**Environment**

-   OS: Arch Linux
-   Desktop environment: XFCE
-   Crow Translate version: Latest

**Additional context**
i love u

**Comment by toprak** [comment]
by the way normal translation works.

**Comment by Shatur95** [comment]
Strange, I even just tried to update the system (I also use Arch), but everything works correctly.
What OCR settings are you using? How did you install the OCR language packs (from the repository or downloaded from GitHub)?

**Comment by toprak** [comment]
Here these are ocr settings, I installed everything via pacman (also tried with yay) ![Screenshot_2020-12-16_03-22-23](https://user-images.githubusercontent.com/43301560/102288675-05120c80-3f4e-11eb-91d2-9e8e4ec66082.png)

**Comment by toprak** [comment]
Deleted everything on /usr/share/tessdata and installed by hand and it gives
```
fuchi@weeb ~]$ crow
Error opening data file /usr/share/tessdata/osd.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'osd'
Error opening data file /usr/share/tessdata/chi_tra_vert.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'chi_tra_vert'
Segmentation fault (core dumped)

```

**Comment by Shatur95** [comment]
Copying files manually using root rights to `/usr/ share/tessdata` is not a good idea. Better use packages from the repository.
Could you try to uncheck all languages?

**Comment by toprak** [comment]
Did not work. :/

**Comment by Shatur95** [comment]
How you installed the program?

**Comment by toprak** [comment]
Installed releases and extracted it blank folder. After then it did move to files according to their name like /usr/share/applications/

**Comment by Shatur95** [comment]
This is the root of the problem :) Never install applications this way on Linux. Remove all files installed this way.
And then install it simply using `yay -S crow-translate`.

**Comment by toprak** [comment]
Thanks it works now :D
