### ISSUE TITLE
Error alerting of missing file after first creating portable copy

### ISSUE THREAD

**Issue by sine-w** [crow-translate/crow-translate#219]
**Bug description**

System alerting that the file MSVCP140_1.dll is missing after first launch

**Steps to reproduce**
1. downloaded crow-translate-2.6.2-win64.7z and extract using 7z
2. run the crow.exe
3. an alert pop up displaying an error alert as my system is not English, I here quote the error message it shown
crow.exe - 系統錯誤 程式碼執行無法繼續，因為找不到 MSVCP140_1.dll。重新安裝程式或許可以修正此問題
 

**Expected behavior**
Expected that the application can be launched 
**Screenshots**

**Environment**

-  OS: Windows 10 20h1(e.g. Arch Linux, Ubuntu, Windows)
-   Crow Translate version: 2.6.2 (e.g. 2.3.0)

**Comment by Shatur95** [comment]
This is not a Crow issue, try to install [Visual C++ Redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=48145).

**Comment by romanbaranovic** [comment]
i have to support this error. i have the Visual C++ installed but i get the same message, with exe as well as with 7z file. when i try to install Visual C++ again, i get an error that Visual C++ is already installed.

**Comment by Shatur95** [comment]
@romanbaranovic, what version of windows do you have? Can you send a screenshot of the error?

**Comment by romanbaranovic** [comment]
sure. i have 

Windows 10 Pro
20H2
Zostava operačného systému	19042.685
Windows Feature Experience Pack 120.2212.551.0

**Comment by romanbaranovic** [comment]
![image](https://user-images.githubusercontent.com/1682008/103437437-1c2c4c00-4c28-11eb-8ddb-dfa9a906a78c.png)

**Comment by romanbaranovic** [comment]
after i try to reinstall i get this error 
![image](https://user-images.githubusercontent.com/1682008/103437457-3a924780-4c28-11eb-9958-e2a25fd7b5c5.png)

**Comment by romanbaranovic** [comment]
i am on windows insider program

**Comment by Shatur95** [comment]
Hm... Try to install [other editions](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) too. The problem has nothing to do with Crow Translate.

**Comment by romanbaranovic** [comment]
hi, ok, i can survive without crow translate, you as developer should check, if it works with another version of windows, im just telling you, there is a problem :)

**Comment by Shatur95** [comment]
There is no problem here. The issue is in missing DLLs in **your** Windows machine, not in the app. If you tried [googling at least](https://www.google.com/search?q=MSVCP140_1.dll+is+missing), you would be know that many applications require this library. You just need to install Visual C++ Redistributable packages (2015 and 2019).

I also can confirm that it works in Windows 10 20H2.

**Comment by romanbaranovic** [comment]
i do understand, how this works, but it looks like, there is problem - i have the Visual C++ packages installed but somehow, when your application calls the dll, it doesnt find it. look here, i have that dll file many, many times on my comp - 
![image](https://user-images.githubusercontent.com/1682008/103438397-1ee06e80-4c33-11eb-9134-ae50ce3ccfb2.png)

**Comment by romanbaranovic** [comment]
maybe the file is not what your executable is looking for, or maybe the dll is not properly registered on my system, i dont know, that much, here is the previous screenshot with all the directories 
![image](https://user-images.githubusercontent.com/1682008/103438446-7d0d5180-4c33-11eb-8461-d0546199e901.png)

**Comment by romanbaranovic** [comment]
ok, i have an update, after i have installed this package - https://aka.ms/vs/16/release/vc_redist.x64.exe which is labeled Visual Studio 2015, 2017 and 2019 it works now

**Comment by romanbaranovic** [comment]
maybe this one was the missing one 
![image](https://user-images.githubusercontent.com/1682008/103438660-56e8b100-4c35-11eb-8df1-42bc4e3eb0c2.png)

**Comment by toprak** [comment]
I have all of vc runtime you should have installed 2015-2019 package or will not work.

**Comment by Shatur95** [comment]
> ok, i have an update, after i have installed this package - https://aka.ms/vs/16/release/vc_redist.x64.exe which is labeled Visual Studio 2015, 2017 and 2019 it works now

> I have all of vc runtime you should have installed 2015-2019 package or will not work.

Thanks. For some reason I thought that `MSVCP140_1.dll` exists in Visual C++ Redistributable 2015. But yes, 2015-2019 version is required.
I can't get rid of this dependency because it how Windows applications compiled by the MSVC works :(

**Comment by romanbaranovic** [comment]
i am glad we have found the solution and it will help future users. thank you for the conversation

**Comment by toprak** [comment]
By the way, I have figured it out early but I forgot to tell it, nowadays it is hard to use pc for me.
