### ISSUE TITLE
Icon not displayed Windows 10 Start Menu

### ISSUE THREAD

**Issue by AlbertoFabbri93** [crow-translate/crow-translate#223]
**Bug description**
In the start menu of Windows 10 a general icon is displayed instead of the app's one.

**Screenshots**
![Screenshot 2020-12-29 025756](https://user-images.githubusercontent.com/51910894/103253600-22010380-4982-11eb-9658-61a7374f748a.jpg)

**Environment**
- Microsoft Windows 10 Home Version 10.0.19042 Build 19042
- Crow Translate version: (e.g. 2.6.2)

**Comment by Shatur95** [comment]
How did you install the app?

**Comment by boromyr** [comment]
Same problem with version 2.6.1 and 2.6.2
![image](https://user-images.githubusercontent.com/52782032/103412235-63590500-4b74-11eb-9f84-d5119de12d1f.png)
Opening the crow.exe file contains only compiled files and the MANIFEST folder, no .ico files

**Comment by Shatur95** [comment]
@boromyr, how did you install the app? I just tested on my machine by downloading from releases page and the icon exists.

>  Opening the crow.exe file contains only compiled files and the MANIFEST folder, no .ico files

It's okay, the icon just bundled into executable.

**Comment by AlbertoFabbri93** [comment]
> How did you install the app?

I didn't do anything unusual, just downloaded and installed the win64.exe package.

**Comment by Shatur95** [comment]
Can't reproduce. I uninstalled the app, downloaded and installed it again. The icon exists.

**Comment by AlbertoFabbri93** [comment]
Good to know, I didn't have time to try to reinstall Crow Translate
