### ISSUE TITLE
No text voiceover

### ISSUE THREAD

**Issue by azjio** [crow-translate/crow-translate#225]
Linux Mint 19.3 x64

No text voiceover.
Installed package festival
additionally executed: sudo apt install festival festvox-ru

I can't change the voice engine in the settings. When I open the settings again, it remains by default in the "speech synthesis" section.

**Comment by Shatur95** [comment]
> I can't change the voice engine in the settings.

I'm not sure if I understand the issue correctly (please use the template I provided), but you can't change voice engine in settings. The voice engine depends on the selected translation engine in the main window. In the settings, you can only check the voice acting and select its parameters.

**Comment by azjio** [comment]
No sound is played when the button is pressed
https://a.radikal.ru/a06/2101/7f/10b50158a8d6.png

**Comment by Shatur95** [comment]
Have you tried installing the package recommended dependencies?
`qtgstreamer-plugins-qt5 gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-pulseaudio libqt5multimedia5-plugins`

**Comment by azjio** [comment]
this package is installed now: qtgstreamer-plugins-qt5
these were installed: gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-pulseaudio
this one was not found in the repository: libqt5multimedia5-plugins

now it gives out "Bing engine does not support TTS"
google first worked now gives an error in both translation and playback
Yandex doesn't react in any way

**Comment by Shatur95** [comment]
> now it gives out "Bing engine does not support TTS"

It means that "Bing engine does not support TTS".

>  google first worked now gives an error in both translation and playback

#105?

>  Yandex doesn't react in any way

Just checked, it works on my machine. Is Yandex available for your country?

**Comment by azjio** [comment]
google stopped giving the error, but the sound did not appear. Yandex is available.

**Comment by Shatur95** [comment]
> google stopped giving the error, but the sound did not appear.

Just wait, probably you made a lot of requests.
