### ISSUE TITLE
the result window is not editable

### ISSUE THREAD

**Issue by azjio** [crow-translate/crow-translate#226]
1. I sometimes press Ctrl + X, in this case I do not get the text in the clipboard
2. If there is a possibility of editing, then you can correct the result before copying it

**Comment by Shatur95** [comment]
In all translators, the translation result is not editable because it's just confusing. You can simply edit the text in destination or move it to the source using "swap" button.

**Comment by azjio** [comment]
> "swap" button

will immediately translate an unprepared text
It is always obvious that the source text is on the left or above, that is, the first one.
Editing adds flexibility to the program

**Comment by Shatur95** [comment]
> will immediately translate an unprepared text

You can disable this behavior:
![изображение](https://user-images.githubusercontent.com/22453358/103556188-1352a900-4eba-11eb-9f51-dca629570e8b.png)

I still think this is not a good idea since you can correct the text in the place where you want to insert it. Usually with spellchecking and other nice things.

**Comment by azjio** [comment]
>  not a good idea

affected by the editing ban think there will be more. Those who don't want to edit in the destination window may not do so.
toggle checkbox - unnecessary body movement.

Editing is available in QTranslate, I often have to correct the translation in 3-window mode with a reverse check of the result. But unfortunately in Linux this program has no flexibility, hotkeys do not work, WINE is used.

**Comment by Shatur95** [comment]
> Those who don't want to edit in the destination window may not do so.

I think this is a very rare use-case.

Technically I can just make the window editable, but that won't work very well because it displays formatted text.
