### ISSUE TITLE
System language detected incorrectly

### ISSUE THREAD

**Issue by azjio** [crow-translate/crow-translate#227]
Linux Mint 19.3 x64

If General -> Language: "System language" is selected, then the GUI is in English, although my system language is Russian. If I choose "Russian" it changes to Russian, it works correctly.

**Comment by Shatur95** [comment]
Can confirm. For unknown reason this sometimes happen. Will try to fix.

**Comment by Shatur95** [comment]
For some unknown reason, the language returned from `QLocale::system()` on some systems differs from the same language created in `QLocale(<explicitly selected language>)`. `QLocale` constructed in the selected language in the settings loads the correct localization, but the system `QLocale` does not.

https://github.com/crow-translate/crow-translate/blob/6d9a84ae21a200fa96423939ab4efb717a5086ed/src/settings/appsettings.cpp#L83-L86
