### ISSUE TITLE
OCR does not work on Gnome Wayland

### ISSUE THREAD

**Issue by mlario** [crow-translate/crow-translate#229]
Thanks for a very nice and neat program. OCR function is super nice, saves a lot of time.

**Bug description**
OCR "Recognize text in screen area" (Ctrl+Alt+I) under Wayland in Gnome does not work:
Selection tool appears but underlying screen is white, no desktop or text is visible under the selection tool

Under Xorg everything is fine. Must be Wayland video server isolation for different programs. 

**Steps to reproduce**
1.  Launch Crow Translate in Gnome under Wayland
2.  When main program window is in focus run Ctrl-Alt-I
3. See white screen with the selection tool, and no desktop or text visible. When drawing selection rectangle it is totally black. Nothing is selected

**Expected behavior**
Text should be visible under the selection tool. After drawing rectangle on top of text and pressing Enter it should be recognized by the program.

**Screenshots**

**Environment**

-   OS: Fedora and Gentoo
-   Desktop environment: Gnome
-   Crow Translate version: 2.6.2

**Additional context**
Heard chromium was working on the fix for screenshare under wayland - maybe there are some hints how to solve it there?

Otherwise as a workaround and enhancement - copying image fragment in GIMP and manually pasting in the translate field would be very handy. Opening jpeg or tiff directly in the program would also be a solution.

**Comment by Shatur95** [comment]
Thanks for the issue. Could you check if Spectacle (screenshot tool) works for you? I use the same class for taking screen capture.

**Comment by mlario** [comment]
Just checked Spectacle. It is the same issue: it does not work with Wayland (no picture taken) while works well under xorg

**Comment by mlario** [comment]
gnome-screenshot works well under wayland and xorg - some solution might be there

**Comment by mlario** [comment]
yes, sure

**Comment by mlario** [comment]
OK, here is submitted bug: https://bugs.kde.org/show_bug.cgi?id=431202

**Comment by Shatur95** [comment]
Thank you! Please, ping once the issue will be resolved.

**Comment by Shatur95** [comment]
Probably can be ported from [Ksnip](https://github.com/ksnip/ksnip).

Just need to get right pixmap here:
https://github.com/crow-translate/crow-translate/blob/5e97d236420e7c51d51ce74c374740137ff83af3/src/ocr/screengrabber.cpp#L88

Maybe I will try it after porting latest changes from Spectacle.

**Comment by Shatur95** [comment]
The author refused to create the library, so we will continue to use the old implementation.
I back-ported latest changes from the rectangular selection and going to add Wayland support for Gnome by myself, needed for #255. Stay tuned for updates.
In Wayland, the capture is very inconvenient and requires a separate implementation for each DE.

**Comment by mlario** [comment]
thank you so much

**Comment by Shatur95** [comment]
Done!
