### ISSUE TITLE
Some dll files seems missed in the installation

### ISSUE THREAD

**Issue by Ywang153** [crow-translate/crow-translate#23]
![image](https://user-images.githubusercontent.com/38997101/53380721-4ae09800-39a9-11e9-9e15-10f70c53d9df.png)

**Comment by Shatur95** [comment]
Are you using version from [releases](https://github.com/crow-translate/crow-translate/releases)?
What version of Windows are you using?

I tested on Windows 10 LTSB 1809 and LTSC 1607.

**Comment by Ywang153** [comment]
Are you using version from [releases](https://github.com/crow-translate/crow-translate/releases)?
yes

What version of Windows are you using?
![image](https://user-images.githubusercontent.com/38997101/53628772-e3477880-3c46-11e9-9ff1-38b0ca8f40ef.png)

**Comment by Shatur95** [comment]
Got it! My mistake. I will re-upload binaries in this evening.

**Comment by Shatur95** [comment]
Done! Just re-download from [releases](https://github.com/crow-translate/crow-translate/releases).

**Comment by Shatur95** [comment]
I suppose the issue can be closed.
