### ISSUE TITLE
Screen grabbber can be activated multiple times during OCR

### ISSUE THREAD

**Issue by LiteracyFanatic** [crow-translate/crow-translate#230]
**Bug description**
I accidentally discovered that you can trigger the screen grabber while it is already showing. This results in the light mask becoming progressively whiter each time.

**Steps to reproduce**
Hit the screen grab shortcut key multiple times in a row.

**Expected behavior**
Crow should check if a screen grab window is already open before drawing another one.

**Environment**

-   OS: Arch Linux
-   Desktop environment: i3
-   Crow Translate version: 2.6.2

**Comment by Shatur95** [comment]
Thanks!
