### ISSUE TITLE
May be interfering Video in SubtitleEdit

### ISSUE THREAD

**Issue by gitut2007** [crow-translate/crow-translate#231]
Videos are not loading MPV or VLC in SubtitleEdit; was fine previously. 

Hi. Maybe you could look at https://github.com/SubtitleEdit/subtitleedit/issues/4674 ,  sorry if i'm totally wrong and CrowT cannot be. Is it a way to 'uninstall' it completely to check?
Thx.
-   OS:  Windows7
-   Crow Translate version: 2.6.2

**Comment by Shatur95** [comment]
The app have nothing to do with SubtitleEdit if it closed. It do not change anything in registry except autostart (if enabled) and Crow-specific settings.

**Comment by gitut2007** [comment]
Ok. I'm suspecting another program now.
Thx.
