### ISSUE TITLE
Add the ability to configure Tesseract

### ISSUE THREAD

**Issue by Shatur95** [crow-translate/crow-translate#233]
**Is your feature request related to a problem? Please describe**
Sometimes we need to adjust tesseract settings. @LiteracyFanatic: 

> For example, the following parameters are of particular interest for CJK languages, especially when written vertically. Unfortunately automatic script and orientation detection is only supported by the legacy engine. The newer LSTM models usually give better results but require manually specifying the orientation.

```
# Tells tesseract whether the script is horizontal (6) or vertical (5)
tessedit_pageseg_mode
# Don't add spaces between characters
preserve_interword_spaces
# toggling these options on or off may improve the output in some circumstances
paragraph_text_based
textord_old_baselines
lstm_use_matrix
```

**Describe the solution you'd like**

@LiteracyFanatic, said:

> typical use cases often involve using multiple config files to switch a number of parameters at once - basically setting up profiles for different types of text.

I agree with this point. If you really need this, we can add the ability to set configuration path as was initially implemented in #232. If the profiles do not need to be changed often, it will be more convenient to store the options right inside the application settings. You decide.

Regardless of the solution above, it would be convenient to have the ability to configure such parameters directly in Crow. We could display a `QTableWidget` (with two columnts) in preferences, where users could set parameters and their values ​​that would be written to a file. This will be a little easier to implement if settings will be stored in the application settings because of `QSettings` :) If we save the settings in a separate file for tesseract, then we will need to write an additional class that is similar to `QSettings` (with `setValue`).

I don't really like the idea of ​​exporting some options separately. I think it's worth exporting all the options consistently as I described above.

Alternatively, we can support both approaches. If the path is not specified, then save it in the application settings. If specified, then in a separate file. Not sure if this might be needed, because look complicated, but not very usefull.

@LiteracyFanatic, what do you think? Need your opinion on it.

**Comment by LiteracyFanatic** [comment]
Yeah, now that I've got a working implementation that stores the settings in the crow config file I think that's better then adding another config file. I do switch profiles frequently (whenever I switch between horizontal and vertical text), but I was already accomplishing that by editing the path to the external config file with a script. I can just change to toggling the parameters directly in the INI file with `sed`.

The table seems like a good approach. Can you clarify a bit more on how you envision it working? The table will begin by displaying just the values that are set in the INI file and the user can press a button to add a new row? Do we expect the user to look up the parameter names in tesseract's documentation or should we display a list to choose from? The only issue I see is that I don't think tesseract's public API provides a way to get a list of the parameters. We could get the list from the command line tool with `tesseract --print-parameters` and then store them in a text file I suppose.

**Comment by Shatur95** [comment]
> Yeah, now that I've got a working implementation that stores the settings in the crow config file I think that's better then adding another config file. I do switch profiles frequently (whenever I switch between horizontal and vertical text), but I was already accomplishing that by editing the path to the external config file with a script. I can just change to toggling the parameters directly in the INI file with sed.

:thumbsup:

>  The table will begin by displaying just the values that are set in the INI file and the user can press a button to add a new row?

Exactly! And with the button to delete a row.

> We could get the list from the command line tool with tesseract --print-parameters

You can use `TessBaseAPI::PrintVariables(FILE *fp)` for it (the same thing [used in CLI](https://github.com/tesseract-ocr/tesseract/blob/3c71749b86595b7e1164960afa216516300af79f/src/api/tesseractmain.cpp#L681)). But maybe it worth to keep it simple at least for now :) So I suggest only displaying existing options, expecting the user to be able to look at the documentation (is there a link to it)?

One more thing. I think it worth to move all dictionaries-related things in a separate `QGroupBox` called "Languages". And keep only "Convert line breaks" with newly added configuration table in "OCR". What do you think?

**Comment by Shatur95** [comment]
> The table will begin by displaying just the values that are set in the INI file and the user can press a button to add a new row?

Could you also store such table logic in a separate class with getter and setter for map of variables? Just inherit from `QTableWidget`, provide convenient functions to get and set variables list and use "Promoted widgets..." to specify you class:
![изображение](https://user-images.githubusercontent.com/22453358/104093978-b890c700-5296-11eb-9fa9-13f2d40d941d.png)
For an example take a look at [OcrLanguagesListWidget](https://github.com/crow-translate/crow-translate/blob/master/src/settings/ocrlanguageslistwidget.h) class done.
It is very important to encapsulate such things, since the class with settings dialog is already very large.

**Comment by LiteracyFanatic** [comment]
> You can use TessBaseAPI::PrintVariables(FILE *fp) for it (the same thing used in CLI). But maybe it worth to keep it simple at least for now :) So I suggest only displaying existing options, expecting the user to be able to look at the documentation (is there a link to it)?

Alright, we can deal with that later if necessary. This is the documentation [website](https://tesseract-ocr.github.io/). Unfortunately a lot of the articles are out of date and most of the parameters only have as much explanation as the CLI output gives. To be fair though, many of them seem to be aimed at people trying to debug the model training process. I found most of the information I've managed to glean by searching through issues on GitHub.

> One more thing. I think it worth to move all dictionaries-related things in a separate QGroupBox called "Languages". And keep only "Convert line breaks" with newly added configuration table in "OCR". What do you think?

That seems like a good idea to prevent clutter.

> Could you also store such table logic in a separate class with getter and setter for map of variables? Just inherit from QTableWidget, provide convenient functions to get and set variables list and use "Promoted widgets..." in .ui to specify your class:

Sure thing.

Thank you for the guidance!

**Comment by Shatur95** [comment]
> Alright, we can deal with that later if necessary. This is the documentation website. Unfortunately a lot of the articles are out of date and most of the parameters only have as much explanation as the CLI output gives. To be fair though, many of them seem to be aimed at people trying to debug the model training process. I found most of the information I've managed to glean by searching through issues on GitHub.

Interesting, thanks for the info.

Okay, waiting for the PR :) Thank you for working on it.
