### ISSUE TITLE
!strcmp(locale, "C"): Error: Assert failed in file baseapi.cpp

### ISSUE THREAD

**Issue by alex-lit** [crow-translate/crow-translate#234]
**Bug description**

Application does not start

**Steps to reproduce**

1.  Click on the application icon
2.  Nothing happens

**Expected behavior**

Application started

**Screenshots**

![term](https://user-images.githubusercontent.com/5243967/104419706-e5d8c000-5589-11eb-9254-6a0441e8d630.png)

**Environment**

-   OS: Linux Deepin 20.1
-   Desktop environment: Deepin 20.1
-   Crow Translate version:  2.6.2

**Comment by Shatur95** [comment]
The problem is in your system configuration that is preventing Qt from working. Try the following:

```bash
env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
```

**Comment by alex-lit** [comment]
It works, thanks!

**Comment by WhiredPlanck** [comment]
> The problem is in your system configuration that is preventing Qt from working. Try to run in clean environment:
> 
> ```shell
> env -i XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY crow
> ```

I followed this to run `crow` and it still failed to start up with following error:

```
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

But I tried to run ```shell $ LANG="C" crow ```, and it works. Really confused.
My system locale is "zh_CN.UTF-8", I tried to set it to "C" or "en_US" but it didn't work. Crow-translate version 2.8.4.
