### ISSUE TITLE
How to build with bundled icons?

### ISSUE THREAD

**Issue by Ninlives** [crow-translate/crow-translate#239]
I had some issue displaying icons in crow's main window, I've tried several methods mentioned in #198 but none of them work. The README says the windows version is built with bundled icons, I wonder if I could build linux version with bundled icons?

**Comment by Shatur95** [comment]
Hi! Currently it is not possible to build it with bundled icons. I can change it, but maybe it will be better to fix the icon issue? If you provide details, then I can possibly help you.

**Comment by Ninlives** [comment]
@Shatur95 Hi, I'm using Gnome in NixOS, qtstyleplugins installed and QT_QPA_PLATFORMTHEME has been set, but I can only make some of the icons shown when switch to the adwaita icon set, so I guess the problem may be icons missing in my current icon set, but I do not plan to change the icon theme.

**Comment by Shatur95** [comment]
Hm... Which icon theme do you use?

**Comment by Ninlives** [comment]
> Hm... Which icon theme do you use?

Here is the link to the icon theme: https://www.opencode.net/adhe/gruvboxplasma

**Comment by LiteracyFanatic** [comment]
@Ninlives It looks like your theme inherits from Papirus, Breeze, and Numix (and by proxy Hicolor which is the fallback for all themes). If an icon isn't included in your theme, it will search those themes as well so I'd suggest installing at least one of them on your system if it isn't already present.

**Comment by Ninlives** [comment]
> @Ninlives It looks like your theme inherits from Papirus, Breeze, and Numix (and by proxy Hicolor which is the fallback for all themes). If an icon isn't included in your theme, it will search those themes as well so I'd suggest installing at least one of them on your system if it isn't already present.

Indeed! This solved my problem, thanks!

**Comment by LiteracyFanatic** [comment]
@Ninlives Great! Glad it worked.
