### ISSUE TITLE
Qt translation is not loaded

### ISSUE THREAD

**Issue by sikmir** [crow-translate/crow-translate#241]
**Bug description**
Caused by https://github.com/crow-translate/crow-translate/commit/ad1e1727decb05d43f91e4b7504661358df3f907

It looks like crow doesn't try to load `qt_ru.qm`:
```sh
$ strace -e trace=openat crow 2>&1 | grep ru.qm
openat(AT_FDCWD, ".../crow-translate_ru.qm", O_RDONLY|O_CLOEXEC) = 7

```

**Screenshots**
![scr0](https://user-images.githubusercontent.com/688044/106964573-5cb14500-6753-11eb-9116-396046ee9106.jpg)
![scr1](https://user-images.githubusercontent.com/688044/106964575-5de27200-6753-11eb-94a3-2c42c0f0f0de.jpg)

**Environment**
-   OS: Linux
-   Crow Translate version: 2.7.0

**Comment by Shatur95** [comment]
Hm... Could you check translation in other Qt-based apps? What distro are you using?

**Comment by sikmir** [comment]
> Hm... Could you check translation in other Qt-based apps? What distro are you using?

I've just checked, all other apps that I know load `qt_*.qm` explicitly.

**Comment by Shatur95** [comment]
Strange, for me it works without it. But okay, it won't hurt. I'll fix it tomorrow after right after job.

**Comment by sikmir** [comment]
> Strange, for me it works without it. But okay, it won't hurt. I'll fix it tomorrow after right after job.

That's interesting, I can't find in [documentation](https://doc.qt.io/qt-5/qtranslator.html) any notes that `qt_*.qm` is loaded by default. What do you see running `strace -e trace=openat crow 2>&1 | grep ru.qm` on your machine?

**Comment by Shatur95** [comment]
```bash
strace -e trace=openat crow 2>&1 | grep ru.qm
openat(AT_FDCWD, "/usr/share/qt/translations/qt_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtbase_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtscript_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtmultimedia_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtxmlpatterns_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qt_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtbase_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtscript_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtmultimedia_ru.qm", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/usr/share/qt/translations/qtxmlpatterns_ru.qm", O_RDONLY|O_CLOEXEC) = 6
```

**Comment by sikmir** [comment]
Well, I really have no idea why it works in your case...
Here just examples from other Qt projects:
* https://github.com/OpenOrienteering/mapper/blob/f7ee4034b49d62a2dffa47895db3ebcf2c8835c6/src/util/translation_util.cpp#L105-L106
* https://github.com/tumic0/GPXSee/blob/86c6fa7b0336d31e2ce8c43ad10a949560b2fd90/src/GUI/app.cpp#L38-L42
* https://github.com/goldendict/goldendict/blob/278c143a055a03934691557d9babb02c96c439e5/main.cc#L353-L355
* https://github.com/qgis/QGIS/blob/a89559879743242d2b7138c2d3d73179c380af97/src/core/qgsapplication.cpp#L189
