### ISSUE TITLE
Adding custom translator sites and store words

### ISSUE THREAD

**Issue by iG8R** [crow-translate/crow-translate#25]
Здравствуйте, Геннадий.
Hi, Hennadii.
Is it possible to implement adding custom translator sites and storing custom words with some notes?
There was Firefox add-on named DictionaryTip which has been long years ago abandoned but still functioning good. It doesn't use API but passes searching words or phrases via URL-string into web-version of Translator site and displays it in separate window(frame).

Screenshot of the main window(frame):

<img width="1108" alt="2019-03-02_123528" src="https://user-images.githubusercontent.com/11407417/53680715-ee9eb080-3ce7-11e9-953c-20a08c66746a.png">

Settings window:

<img width="484" alt="2019-03-02_123219" src="https://user-images.githubusercontent.com/11407417/53680770-974d1000-3ce8-11e9-8e5e-d84b9a82c3a9.png">

WordList window:

<img width="1919" alt="2019-03-02_124025" src="https://user-images.githubusercontent.com/11407417/53680776-b0ee5780-3ce8-11e9-94ce-4f429a57cda0.png">

**Comment by ShaturIQ** [comment]
Looks interesting. I will try to implement in the future :)

**Comment by Shatur95** [comment]
Looks interesting. I will try to implement in the future :)

**Comment by iG8R** [comment]
Thank you.

**Comment by gggin** [comment]
In china there's many website or API support english translate like Sogou baidu dict.cn etc. If I can customize url and keyword is so cool.

**Comment by Shatur95** [comment]
Crow does not use websites. It uses engines API directly. So, there is now way to add the ability to customize URL because engines API is different. I will close this issue and will track only translation history in #89.
