### ISSUE TITLE
[Question]Circle-icons for flags 

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#251]
For crow-translate v2.7.1
In the changelog it is mentioned that there are being used circle-icons for flags. Where are these icons in the application.
![flags](https://user-images.githubusercontent.com/46356616/107853481-ae726300-6e16-11eb-98f5-989a47214a2a.png)

EDIT: I mean I was expecting to see circle icons instead those square in the main window.

**Comment by Shatur95** [comment]
Yes, that's okay :) These icons use a circle mask that is incompatible with the TinySVG standard (that used in Qt) and the icons are displayed square. You can read more about it [here](https://github.com/HatScripts/circle-flags/issues/11). I just decided that even square icon is better then before.
