### ISSUE TITLE
New version crashed

### ISSUE THREAD

**Issue by kutahyaspor** [crow-translate/crow-translate#252]
2.7.1 version does not work on windows (W10) and Linux (Ubuntu). Main window closes without any error messages.

**Comment by Shatur95** [comment]
Can't reproduce on my side. Could you try to clear configuration by removing `~/.config/Crow Translate/` on Linux or clearing `HKEY_CURRENT_USER\Software\Crow Translate\Crow Translate` registry key on Windows?

**Comment by kutahyaspor** [comment]
windows side working perfectly now. The registry keys you mentioned can be added to the Uninstall the Program section. I haven't tested the Ubuntu side yet, I'll write the result here.

**Comment by Shatur95** [comment]
> The registry keys you mentioned can be added to the Uninstall the Program section.

I would like to add a checkbox for it, but not sure how to add it via NSIS (installation creator) in CMake. So, PR is appreciated.

>  haven't tested the Ubuntu side yet, I'll write the result here.

Could you post a configuration file here before deletion?

**Comment by kutahyaspor** [comment]
The program opening normally, functions other than OCR processes are running, when I select the screen for OCR and confirm it, an error occurs and the program closes. The situation does not changing after deleting the configuration file.


[Crow Translate.zip](https://github.com/crow-translate/crow-translate/files/5976529/Crow.Translate.zip)

**Comment by Shatur95** [comment]
So, the crash occurs only when you trying OCR? Was that what you wrote about the first message? Have you seen this issue before, or have you just recently installed the app?
To help you, I need a detailed description of the problem, preferably with steps to reproduce. This is why issue templates exist.

**Comment by kutahyaspor** [comment]
I think there is a problem with the setup method.

When I install the program with the command "sudo apt install crow-translate" from the terminal, all functions work fine. (v2.6.2)

I removed it from the terminal with the command "sudo apt-get remove crow-translate".

The same version;
- with "sudo dpkg -i crow-translate_2.6.2_amd64.deb" command from the terminal
- when I install the file from Ubuntu Software Center
- when I installed it with the Gdebi program

In all three cases, the program runs normally until it does OCR, then crashes.

**Comment by Shatur95** [comment]
Weird, I can't reproduce it on my computer with your configuration. What it prints if you run `crow` from the terminal (you should close previously opened instance before)?

**Comment by kutahyaspor** [comment]
terminal output:
```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
Error: LSTM requested, but not present!! Loading tesseract.
```

**Comment by kutahyaspor** [comment]
When I start from terminal and use OCR;

```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
Error: LSTM requested, but not present!! Loading tesseract.
Parçalama arızası (çekirdek döküldü)
```

**Comment by Shatur95** [comment]
Something wrong with your trained models. Try to install it from repo (via `tesseract-<lang>`).

**Comment by kutahyaspor** [comment]
`tesseract --list-langs ` output;
```
List of available languages (3):
eng
osd
tur
```

`Crow Translate.conf `file;
```
[OCR]
ApplyLightMask=true
CaptureOnRelease=false
ConvertLineBreaks=true
Languages=@ByteArray(eng+osd+tur)
LanguagesPath=@ByteArray(/home/ahmet/.config/tessdata)
RegionRememberType=0
ShowMagnifier=false
```
Language path is correct.

**Comment by Shatur95** [comment]
Could you try to install stable (4.1) tesseract?

**Comment by kutahyaspor** [comment]
Crow Translate v2.7.1 with tesseract v4.1.1 works without any problems. But Crow Translate v2.6.2 version (sudo apt install crow-translate) was working with the Tesseract 5.0 version.

**Comment by Shatur95** [comment]
I tested on the latest Tesseract 5.0 and everything is working fine on my side. Any chance to try to debug the crash?
You need to download QTCreator, download the repo, open `CMakeLists.txt` and press `F5` to run in Debug mode. Debugger will stop at the line that causes the crash if it occurs.

**Comment by Shatur95** [comment]
Oh, got it. It shouldn't work because all version from the releases page was compiled with stable (4.1) Tesseract. Maybe the version from your repo just was built with the 5.0 alpha. So, you need to wait for the update from the repository that you are using (I assume that they will continue to use Tesseract 5.0), or install the stable version of Tesseract to use with the version that you downloaded here.

**Comment by Shatur95** [comment]
Also you can recompile it yourself for the latest Tesseract, check out [this](https://github.com/crow-translate/crow-translate#building-a-package-using-cpack) section.

**Comment by kutahyaspor** [comment]
Thank you.
