### ISSUE TITLE
Crow Translate crash after startup

### ISSUE THREAD

**Issue by homus32** [crow-translate/crow-translate#254]
**Bug description**
Раньше crow translate работал, но после обновления моей системы перестал. Работает с рута. 
Пытался переустановить - все равно ошибка сегментации. Что делать дальше - не знаю...
en:
before the crow translate worked. After the system update, it stopped. Runs as root.
Tried to reinstall - still segmentation fault. I don't know what to do next ...

help :)

**Screenshots**
https://i.imgur.com/zk3PgBv.png
https://i.imgur.com/7Q7q4L3.png

**Environment**

-   OS: Neon 20.04 focal
-   Desktop environment: KDE 5.78.0 / Plasma 5.20.5
-   Crow Translate version: 2.7.0, previous versions don't work either

**Comment by Shatur95** [comment]
Unfortunately, the issue in your system configuration and I can't help you here :(
Please, read #196 for possible workarounds.
