### ISSUE TITLE
Executable continues to run in the background even after being closed

### ISSUE THREAD

**Issue by fabianski7** [crow-translate/crow-translate#256]
**Bug description**
Even with the "Show icon on systray" option disabled, the crow process remains active even after the program is closed

**Steps to reproduce**

1. Build version 2.7.1 or master
2. Open crow translate through the desktop icon or CLI 
3. Turn off the option to stay active in systray
4. Close the program (GUI)
5. Open the executable again

An alert will appear that Crow Translate is already running

**Expected behavior**
Since the program is configured not to stay in systray, it should be terminated and not run in the background after being closed

**Environment**

Operating System: Arch Linux
KDE Plasma Version: 5.21.0
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-arch1-1
OS Type: 64-bit
Graphics Platform: X11

**Comment by Shatur95** [comment]
Hi! Are you sure that you tested it on the latest master? I fixed the issue in c44dc9374720143f9900ccd5c889ce9e052278e4.

**Comment by fabianski7** [comment]
well, I already had the repository cloned on my machine and it seems I did not use the git pull correctly 😅
All working. Thank you very much.
