### ISSUE TITLE
Add a remove button for languages

### ISSUE THREAD

**Issue by MonBureauLinux** [crow-translate/crow-translate#26]
Thanks for this application ( discover on the PCLinuxOS Magazine April 2019 ).

Crow Translate version 2.1.0 in the repository.

Can we have also a button to remove languages that we added before ?

<a href="https://ibb.co/SK7kW19"><img src="https://i.ibb.co/mHFn1YM/crowtranslate-remove-button.png" alt="crowtranslate-remove-button" border="0"></a>

In my linux system ( PCLinuxOS ), the only way I found is to :

go to my home folder
shows hidden files
go to .config folder
delete the crow folder

Start or restart the application.

PS : the reset config keeps all language add before.

Thanks

**Comment by btd1337** [comment]
I have the same problem here.

**Comment by Shatur95** [comment]
I will begin to implement the proposed features as soon as I finish with refactoring and fixes for Bing. Stay tuned for updates :)

**Comment by serovar** [comment]
Any news on this?

**Comment by Shatur95** [comment]
I planning to implement it in next release. Sorry, do not have a lot of free time. I thinking about something like the following:
![image](https://user-images.githubusercontent.com/22453358/81505648-80954680-92f9-11ea-81ba-76c4227f6479.png)
You will can move, remove or add languages to the panel.

**Comment by Shatur95** [comment]
Now in master branch, feel free to give me a feedback.
