### ISSUE TITLE
Auto focus on the text field does not work if the app does not start minimized

### ISSUE THREAD

**Issue by fabianski7** [crow-translate/crow-translate#260]
**Is your feature request related to a problem? Please describe**
When the crow-translate is opened via a keyboard shortcut, it is necessary to return to the mouse to get the focus of the text field

**Describe the solution you'd like**
When opened, the text field could automatically focus.

**Describe alternatives you've considered**
I tried to use the tab button to change the focus, but it is necessary to press it five times until it reaches the text field

**Additional context**
It seems that the button to copy the original text is the part of the interface that gains automatic focus after the program is opened

**Comment by Shatur95** [comment]
It already done automatically long time ago (works on my machine):
https://github.com/crow-translate/crow-translate/blob/7d33f99a4ff374a7e1d9165a70e67b94fe72a0fa/src/mainwindow.cpp#L209

**Comment by fabianski7** [comment]
that's weird. what happens to me [is this](https://upload.vaa.red/2qRY4F#lZB4zeIIv0n6MDwjbuTgHsvYxHezFBZZ)

I'm using plama 5.21 with qt 5.15.2

**Comment by fabianski7** [comment]
I deleted my dotfile and realized that focus is not achieved correctly only if systray integration is disabled.
If crow-translate starts minimized, and then the window is launched, the focus is achieved as expected

**Comment by Shatur95** [comment]
Thanks!
