### ISSUE TITLE
minimize at startup

### ISSUE THREAD

**Issue by Ashishkumar-sys** [crow-translate/crow-translate#265]
**Bug description**
In 2.7.1 version minimize at startup not working. Before that it was working fine. I have turned on "Start minimized" option in Application Settings --> General --> Start minimized
**Steps to reproduce**

1.  Start your computer.
2.  Main window covering 1/4 of screen will be there.

**Expected behavior**
Want the crow-translate to start as minimized.

**Screenshots**
[Screenshot of bug](https://gyazo.com/e9ff3a7b721abf46a4d399048009d19c)
**Environment**

-   OS: (lubuntu)
-   Desktop environment: (LXQt)
-   Crow Translate version: (2.7.1)

**Additional context**

**Comment by Shatur95** [comment]
I already fixed this issue in the latest master, sorry for inconvenience. Will work as expected in the next release.

**Comment by yusanshi** [comment]
I'm running Crow 2.8.1 but I have met the same issue.

If I directly run `crow` in the terminal or launch the app in GNOME launcher, it will run minimized and show a tray icon as I have set in settings. But when I reboot the system (already set to launch at startup), it just shows a main window and the `Start minimized` setting become unavailable:

![image](https://user-images.githubusercontent.com/36265606/112147440-b0022880-8c17-11eb-9bf9-85ae91daa6a8.png)


I checked the GNOME Startup Applications settings and the command to start the app is `crow`:

![image](https://user-images.githubusercontent.com/36265606/112148164-83024580-8c18-11eb-9876-cbbddd042d84.png)

As I have mentioned earlier, run `crow` directly in the terminal works well. So I think this may be related to the way GNOME Startup Applications works, but I don't know where and how to debug...  

Thanks a lot

--- 
**Environment**
Ubuntu 20.04.2 LTS
GNOME 3.36.8
Crow 2.8.1 (from flathub)

**Comment by Shatur95** [comment]
@yusanshi, the application checks if the system tray is available at startup (required to work correctly on smartphones). Perhaps the system tray is initialized later than the application itself. Could you try adding a start delay to check it?

**Comment by Shatur95** [comment]
@yusanshi, I removed this check, should work correctly in the next release :)

**Comment by yusanshi** [comment]
Haha, you're right. I changed the startup command to `bash -c "sleep 10 && crow"` and it worked like a charm
