### ISSUE TITLE
Multiscreen OCR bug

### ISSUE THREAD

**Issue by bayan79** [crow-translate/crow-translate#271]
**Bug description**

OCR-mode available only with one of them, the other is fully black with helper message. Window focus dont effect what monitor will be available, always the same monitor is available.
When OCR-mode is on, screens swaps each other (see screenshots) 

**Steps to reproduce**
1. Start app 
2. Press Ctrl+Alt+I
3. See error

**Expected behavior**
Expected all monitors are available to capture screenshots

**Screenshots**
Having 2 monitors:
![screen1](https://user-images.githubusercontent.com/40488830/109497545-05816480-7ab4-11eb-9782-f6a6192a7140.png)
OCR-mode:
![screen2](https://user-images.githubusercontent.com/40488830/109497851-7b85cb80-7ab4-11eb-93b0-4ab85dc97f72.png)

**Environment**

-   OS: Arch Linux,
-   Desktop environment: i3-wm
-   Crow Translate version: 2.7.1

**Comment by Shatur95** [comment]
Sorry, I don't get it. You can capture rectangle from both monitors, even intersect them.

**Comment by bayan79** [comment]
When OCR-mode turns on, my right screen moves to the left monitor, and right monitor shows nothing except help message.
Below i tried capture intersection region, but left screen dissappeared and right screen moved to the left monitor, so I cant capture anything on my left screen

**Normal screens**
Red rectangle is the region i want to capture
![screen3](https://user-images.githubusercontent.com/40488830/109535145-07f8b400-7ade-11eb-81ac-fb84ff2025b7.png)

**OCR-mode**
![screen4](https://user-images.githubusercontent.com/40488830/109535203-1ba41a80-7ade-11eb-8c26-d1881af0c3ef.png)

**Comment by Shatur95** [comment]
Got it, thanks!
Could you try if Spectacle (screenshot software) works correctly with your setup? I am using the same implementation.

**Comment by Shatur95** [comment]
I mean, I cannot reproduce this on my side, so I need to check if another program is behaving the same way to determine if there are porting issues.

**Comment by bayan79** [comment]
Oops, probably it was my configuration problem, after system update bug removed
