### ISSUE TITLE
DeepL support

### ISSUE THREAD

**Issue by c-sanchez** [crow-translate/crow-translate#273]
It can be good to have DeepL as a translation engine as well, it has great quality of translations, sometimes is better than google even.
![deepl image](https://www.deepl.com/img/logo/DeepL_Logo_darkBlue_v2.svg)
https://www.deepl.com/translator

**Comment by Shatur95** [comment]
Duplicate of https://github.com/crow-translate/QOnlineTranslator/issues/6
