### ISSUE TITLE
Capture area with dual monitor doesn't work if the secondary monitor is on the left of the primary monitor

### ISSUE THREAD

**Issue by yurigiu** [crow-translate/crow-translate#279]
**Bug description**
Capture area with dual monitor doesn't work if the secondary monitor is on the left of the primary monitor.
Secondary monitor is not selectable at all, primary monitor image is shifted to the left and an the rest is black.

**Steps to reproduce**

0. Have dual display.
1.  Right click on the desktop and select "Display settings"
2.  Select the secondary display and move it to the left of the primary display.
3. Click "Apply".
4. Capture an area (default shortctut: Ctrl+Alt+I).

**Expected behavior**
Normal select area.

**Screenshots**
Primary display image is shifted to the left with the right all black.
![primary-display](https://user-images.githubusercontent.com/60064799/111051272-ca831780-8449-11eb-9999-2af0ccf54ac6.jpg)

(secondary display shows normal image, but it's not selectable at all)

**Environment**

-   OS: Win 10.
-   Crow Translate version: 2.8.0

**Comment by Shatur95** [comment]
Reproduced, will try to fix.

**Comment by Shatur95** [comment]
Is this a problem exists only after 2.8.0?

**Comment by Shatur95** [comment]
Hm... Happens on Linux too.

**Comment by yurigiu** [comment]
I just downloaded the 2.8.1 version which includes this fix.
Now the primary display image shows correctly (not shifted to the left), but the secondary display is still unselectable.
It works correctly when the secondary display is on the right of the primary.

**Comment by Shatur95** [comment]
Thanks for the report. Linux seems to be working correctly now, but Windows still has problems.
