### ISSUE TITLE
2.8.0 Errors installing on Windows 10.

### ISSUE THREAD

**Issue by algent-al** [crow-translate/crow-translate#289]
Just tried to install this on Windows, and I get a lot of errors about missing  `.dll` files.

**Environment**

-   OS: Windows 10 Pro 20H2
-   Crow Translate version: 2.8.0

**Comment by Shatur95** [comment]
Which error? Which dlls? How did you install the program?
Unfortunately, I do not yet possess psychic abilities :) Therefore, fill in the issue properly.

**Comment by algent-al** [comment]
> I do not yet possess psychic abilities :)

Of course you don't have psychic abilities, if so then there shouldn't be issues. :P

In fact I couldn't install it. These missing libraries are appearing during installation. The first one was `Qt5Core.dll`, then I click "Ignore" button, then another `.dll` showed up, I had to click 10 times "Ignore", before "Aborting" the installation which was about at 30% progress.

**Comment by algent-al** [comment]
I think I found the problem. The installation problem is at my work PC which it is conneced to our work domain. I think there should be some kind of limitations, even that I have administrator privileges (But it seems not fully.)

At home I have another PC with a Windows 10 Pro instalation and version 2.8.0 is installed without any issue.

So, this issue can be closed.

**Comment by Shatur95** [comment]
> In fact I couldn't install it. These missing libraries are appearing during installation. The first one was Qt5Core.dll, then I click "Ignore" button, then another .dll showed up, I had to click 10 times "Ignore", before "Aborting" the installation which was about at 30% progress.

Oh, so you can't just install it? Just try installing to a different directory (e.g. not it `Program Files`) that does not require administrator privileges.

**Comment by algent-al** [comment]
> Or you can download portable version in archive from the releases page.

Yes I think I will use that.

> Just try installing to a different directory (e.g. not in Program Files) that does not require administrator privileges.

Yes, I will try to do that.

I have installed `crow-translate` before, but I don't know why It isn't installing now. Even the version 2.7.1 is not installing that I have installed once.

**Comment by Shatur95** [comment]
> I have installed crow-translate before, but I don't know why It isn't installing now. Even the version 2.7.1 is not installing that I have installed once.

Weird. Maybe something changed in the environment on your work.

**Comment by algent-al** [comment]
You were right, installing it to a different directory it works fine. Thank you!
