### ISSUE TITLE
Add support for Ubuntu 19.04, please

### ISSUE THREAD

**Issue by MLDamazigh** [crow-translate/crow-translate#29]
Please add support for Ubuntu 19.04 Disco Dingo

**Comment by ShaturIQ** [comment]
The program should work. Have you tried installing the .deb package from the [releases](https://github.com/crow-translate/crow-translate/releases)?

**Comment by Shatur95** [comment]
The program should work. Have you tried installing the .deb package from the [releases](https://github.com/crow-translate/crow-translate/releases)?

**Comment by MLDamazigh** [comment]
Trying to install .deb package with Gdebi but it shows that the dependency (gstreamer1.0-fluendo-mp3) is missing.
![image](https://user-images.githubusercontent.com/15183134/56425958-e0abeb80-62a5-11e9-8b41-be42387859a7.png)

**Comment by Shatur95** [comment]
Thank you, I will fix the problem.

**Comment by Shatur95** [comment]
I re-uploaded the .deb-package in releases. Now everything should work. Can you check it?

**Comment by MLDamazigh** [comment]
YES, thank you very much, now it's working 
![image](https://user-images.githubusercontent.com/15183134/57133785-7316b980-6d93-11e9-9007-d7898585f02d.png)
