### ISSUE TITLE
"Crow” terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by Voralberg** [crow-translate/crow-translate#299]
**Bug Description**
Good morning, lately I've tried to install the latest version of crow via .deb (2.8.2) or in the Ubuntu PPA (2.6) on a KDE Neon 5.21 but I'm unable to run the application afterwords. Then I've tried to run the AppImage with the same result, the only thing that I've not tried still it's compiling it.

When i try to run it via terminal i get this:

> (gst-plugin-scanner:28802):` GLib-GObject-WARNING **: 08:07:59.735: cannot register existing type 'GstQtQuick2VideoSink'

> (gst-plugin-scanner:28802): GLib-GObject-CRITICAL **: 08:07:59.735: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

>(gst-plugin-scanner:28802): GLib-CRITICAL **: 08:07:59.735: g_once_init_leave: assertion 'result != 0' failed

>(gst-plugin-scanner:28802): GStreamer-CRITICAL **: 08:07:59.735: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed

Ending with:

>“crow” terminated by signal SIGSEGV (Address boundary error)

Is there a way to solve this problem?

**Steps to reproduce**

`$ crow`

**Environment**

OS: KDE neon User Edition 5.21 x86_64
KDE Plasma version: 5.21.4
KDE Frameworks version: 5.81.0
Qt version: 5.15.2

Crow Translate version: 2.8.2 and 2.6

**Comment by Shatur95** [comment]
KDE Neon has ABI compatibility issues with libraries because of modern KDE environment and old package base.
As you can see, even AppImage does not work, despite the fact that I tested it on Ubuntu 18.04, 20.04 and ArchLinux. Could you try to build it manually and check if it solves the issue? I have build instructions [here](https://github.com/crow-translate/crow-translate#building). You can check [CI config](https://github.com/crow-translate/crow-translate/blob/4a005c1ddc7831ffa52ba32c6ad3bd46892c6e40/.github/workflows/main.yml#L39) for a full list of dependencies for Ubuntu.

**Comment by Voralberg** [comment]
I see, actually I was prompted to open a thread because it used to work some months ago, always on KDE Neon. Evidently they updated something of late that sparked this incompatibility.

Unfortunately, after having installed the missing dependencies, I was able to compile completely but running the crow binaries I still got:

> terminated by signal SIGSEGV (Address boundary error)

**Comment by Shatur95** [comment]
Hm... Could you try [this](https://github.com/crow-translate/crow-translate/issues/196#issuecomment-740050611) workaround?

**Comment by Voralberg** [comment]
I have a Mesa DRI Intel® HD Graphics 3000, nonetheless I've tried all of the various command with no luck whatsoever, I always get he same message.

**Comment by Shatur95** [comment]
This is weird. Okay, since you've already installed the build dependencies, can you try opening the app in a debugger? Just install QtCreator, select "Open project", navigate to `CMakeLists.txt` from this repo and press F5 to build and run in debug mode. You will see where you application crashed. When the application crashes, you will see a stack. Send it to me in text or take a screenshot.

**Comment by Voralberg** [comment]
You'll have to excuse me but I'm quite the novice in these kind of things. 
[Dissasembler.txt](https://github.com/crow-translate/crow-translate/files/6342026/Dissasembler.txt)
I'm not sure that's what you are looking for, let me know.

**Comment by Shatur95** [comment]
> You'll have to excuse me but I'm quite the novice in these kind of things.

No problem.

>  I'm not sure that's what you are looking for, let me know.

This is not exactly what I need. Can you just send a screenshot from QtCreator? I would like to see the call stack.

**Comment by Voralberg** [comment]
Of course, that's what I see right after I follow the instruction that you gave me.

![Screenshot_2021-04-20_10 34 58](https://user-images.githubusercontent.com/53734126/115366631-c9ba6f80-a1c5-11eb-9db2-fe000e277532.png)

![Screenshot_2021-04-20_10 48 27](https://user-images.githubusercontent.com/53734126/115366886-fb333b00-a1c5-11eb-9066-c2cdf660bc03.png)

**Comment by Shatur95** [comment]
Could you switch to Debug build? You need to click on the monitor in the left bottom corner.

**Comment by Voralberg** [comment]
Sorry, if I click on the monitor nothing much happens, maybe I'm missing some step

![Screenshot_2021-04-20_10 59 29](https://user-images.githubusercontent.com/53734126/115368739-a8f31980-a1c7-11eb-8432-858f51e1802a.png)

**Comment by Voralberg** [comment]
Sorry, it's worth a try, is this one the correct text?
I saved the last bit.
[debugged.txt](https://github.com/crow-translate/crow-translate/files/6342300/debugged.txt)

**Comment by Shatur95** [comment]
No, you are still in debug build mode. So you building without debug information.

But I have another idea. Could you backup / move your current settings from `.config/Crow Translate/Crow Translate.conf` and check if it fixes a crash?

**Comment by Voralberg** [comment]
Well... I must say that this is by far the most silliest bug that I've encountered in my life... Now the binaries, the AppImage and the .deb package work... I purged crow from the system at the start so I really couldn't image that was the issue...

I have even rebooted and everything works as it should. I guess we can close this issue and forget about it. 

I thank you for your prompt support!

Take care.

**Comment by Shatur95** [comment]
> Well... I must say that this is by far the most silliest bug that I've encountered in my life... Now the binaries, the AppImage and the .deb package work... I purged crow from the system at the start so I really couldn't image that was the issue...

Awesome!
Do you still have a file that was causing the problem? I need it to reproduce the bug on my machine, because the application should not crash if the configuration is incorrect.

**Comment by Voralberg** [comment]
Of course, here you go.
[Crow Translate.txt](https://github.com/crow-translate/crow-translate/files/6343291/Crow.Translate.txt)

**Comment by Shatur95** [comment]
Thanks, added a check for such values.
