### ISSUE TITLE
Yandex translate doesn't work

### ISSUE THREAD

**Issue by roussak** [crow-translate/crow-translate#300]
**Bug description**
It looks like Yandex changed API for its translate service. If I'm attempting to translate a text (from English) using Yandex, I get the following message:

![image](https://user-images.githubusercontent.com/6649929/115356161-0be2b180-a1c4-11eb-8acc-3d6f918b157c.png)

or even this one:

![image](https://user-images.githubusercontent.com/6649929/115356949-cecaef00-a1c4-11eb-8d52-d7a7f72c8f20.png)

The Crow-Translate version is 2.8.1. I tried on several machines under different OSes (Windows 10, ArchLinux, KDE).

**Comment by Shatur95** [comment]
Known issue, but was fixed in 3.8.2 :)

**Comment by roussak** [comment]
Do you mean **2**.8.2?

**Comment by Shatur95** [comment]
> Do you mean 2.8.2?

Oops, that was a typo. Yes.

**Comment by roussak** [comment]
So, what can I say... Such a fast issue resolution I have never seen previously... ))
