### ISSUE TITLE
Can't capture screen for OCR on Ubuntu 21.04

### ISSUE THREAD

**Issue by buuduc1999** [crow-translate/crow-translate#302]
**Bug description**
crow-translate 2.8.2 work fine on ubuntu 20.10. but when i upgrade to version 21.04 when taking a screenshot, only gray screen appears and i can't use this feature.
**Steps to reproduce**

1.  Click shortcut to capture screen
2.  See error

*
**Screenshots**

**Environment**

-   OS: Ubuntu 21.04 64 bit
-   Desktop environment: Gnome 3.38.5 
-   Crow Translate version: 2.8.2

**Additional context**
I tried older crow-translate verson but it not working too

Thanks for your help. This is great software 

![Screenshot from 2021-04-28 16-13-20](https://user-images.githubusercontent.com/45002497/116380891-979cb380-a83e-11eb-95aa-d0e33c86be96.png)

**Comment by buuduc1999** [comment]
I think I fixed it. I changed the monitor driver to the nvidia's driver (I used the X.Org X server before 
![fixed](https://user-images.githubusercontent.com/45002497/116414034-56b69600-a862-11eb-99d2-fd5cdea96e85.png)
)

**Comment by Shatur95** [comment]
Glad the issue was resolved. I use built-in Qt functionality for screen capture on X11. So yes, I assume that this is a Nouveau issue.
