### ISSUE TITLE
PPA on launchpad missing for ubuntu hirsute Release

### ISSUE THREAD

**Issue by lwbaqueros** [crow-translate/crow-translate#310]
**Bug description**
Using last version of Ubuntu (21.04), and trying to install `Crow-Translate` thought the PPA, it returns 

```
Err:8 http://ppa.launchpad.net/jonmagon/crow-translate/ubuntu hirsute Release                                                               
  404  Not Found [IP: 91.189.95.85 80]
```

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package crow-translate
```

**Steps to reproduce**
`sudo add-apt-repository ppa:jonmagon/crow-translate`
`sudo apt-get update`
`sudo apt install crow-translate`

**Expected behavior**
APT finds the release version of `crow-translate` for Hirsute.

**Environment**

-   OS: Kubuntu 21.04
-   Desktop environment: KDE

**Comment by Shatur95** [comment]
Thanks for the issue.
CC @JonMagon, Ubuntu PPA maintainer.

**Comment by JonMagon** [comment]
Just published new packages for focal, groovy, and hursuit. You can check it out, don't forget to do the `apt update` command.
