### ISSUE TITLE
Installer - In program group "Uninstall" icond ecsription is untranslated

### ISSUE THREAD

**Issue by bovirus** [crow-translate/crow-translate#314]
**Bug description**

Seelcting Italian, in the Crow Translate program group there is an icon "Uninstall" without translation and without mention to uninstall program.

In English should be "Uninstall Crow Translate"
In Italian should be "Disinstalla Crow Translate"

Thanks.

**Steps to reproduce**

1.  Go to '...'
2.  Click on '...'
3.  Scroll down to '...'
4.  See error

**Expected behavior**

**Screenshots**

**Environment**

-   OS: (e.g. Arch Linux, Ubuntu, Windows)
-   Desktop environment: (only for Linux, e.g. KDE, Gnome)
-   Crow Translate version: (e.g. 2.3.0)

**Additional context**

**Comment by Shatur95** [comment]
Unfortunately, NSIS (the program used to create the installer) does not allow me to translate the uninstall program name. Try to report it to NSIS.

**Comment by bovirus** [comment]
@Shatur95 

May I have a the NSIS installer for a check?
I'm quite sure that you always can translate it.

**Comment by Shatur95** [comment]
> May I have a the NSIS installer for a check?
> I'm quite sure that you always can translate it.

NSIS script generated using CMake. You can set options in the main `CMakeLists.txt`:

https://github.com/crow-translate/crow-translate/blob/4f612602ca5e7df9098a820e1da146b6d05b88f9/CMakeLists.txt#L29-L31

Let me know if you find the solution.

**Comment by bovirus** [comment]
@Shatur95 

It seems that cmake with NSIS module didn't have option for multilanguage.

**Comment by Shatur95** [comment]
But are you sure that NSIS have the ability to translate such things as installation file name?

**Comment by bovirus** [comment]
@Shatur95 

The "UninstalL" strings is about a icon description in program group.

And NSIS has this feature.
I translated several software with this option.

**Comment by Shatur95** [comment]
Oh, got it. But you are right, this is not possible when you generating NSIS file automatically :(
We can set [CPACK_NSIS_UNINSTALL_NAME](https://cmake.org/cmake/help/latest/cpack_gen/nsis.html#variable:CPACK_NSIS_UNINSTALL_NAME), but it will not translatable.
