### ISSUE TITLE
PPA on launchpad missing for Pardus 19.5

### ISSUE THREAD

**Issue by satirdanKahraman** [crow-translate/crow-translate#325]
Using last version of Pardus (19.5), and trying to install Crow-Translate thought the PPA, it returns

>gpg: keybox '/tmp/tmp087sj80d/pubring.gpg' created
gpg: /tmp/tmp087sj80d/trustdb.gpg: trustdb created
gpg: key C2B0E8C0D58C0CED: public key "Launchpad PPA for Dmitry Sidorov" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
p@pardus:~$ 
p@pardus:~$ sudo apt update
Get:1 http://ppa.launchpad.net/jonmagon/crow-translate/ubuntu impish InRelease [18.1 kB]
Err:1 http://ppa.launchpad.net/jonmagon/crow-translate/ubuntu impish InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2B0E8C0D58C0CED
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/jonmagon/crow-translate/ubuntu impish InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2B0E8C0D58C0CED
E: The repository 'http://ppa.launchpad.net/jonmagon/crow-translate/ubuntu impish InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
p@pardus:~$ 
p@pardus:~$ sudo apt install crow-translate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package crow-translate
`

-Pardus 19.5, XFCE 4.12, 
Kernel: 4.19.0-16amd64

**Comment by Shatur** [comment]
@JonMagon, could you check if the installation works on regular Ubuntu?

**Comment by JonMagon** [comment]
This may be because impish has not yet been released, have you tried importing the key manually?
```bash
wget -O key "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b3c4a82f16ce6bc90f90007c2b0e8c0d58c0ced"
sudo apt-key add key
```

**Comment by satirdanKahraman** [comment]
I'm done, it returns: 
```
sudo apt install crow-translate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 crow-translate : Depends: libgcc-s1 (>= 3.3.1) but it is not installable
                  Depends: libqt5core5a (>= 5.15.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
                  Depends: libqt5dbus5 (>= 5.14.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
                  Depends: libqt5network5 (>= 5.14.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
                  Depends: libqt5widgets5 (>= 5.15.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
E: Unable to correct problems, you have held broken packagesroot@pardus:~# sudo apt install crow-translate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 crow-translate : Depends: libgcc-s1 (>= 3.3.1) but it is not installable
                  Depends: libqt5core5a (>= 5.15.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
                  Depends: libqt5dbus5 (>= 5.14.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
                  Depends: libqt5network5 (>= 5.14.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
                  Depends: libqt5widgets5 (>= 5.15.1) but 5.11.3+dfsg1-1+deb10u4 is to be installed
E: Unable to correct problems, you have held broken packages


```

**Comment by JonMagon** [comment]
It looks like your distribution has outdated Qt packages and does not have libgcc-s1
You can check here https://launchpadlibrarian.net/537979054/buildlog_ubuntu-focal-amd64.crow-translate_2.8.2-focal1_BUILDING.txt.gz since Focal Launchpad uses Qt packages from version 5.12 and above. PPA packages are designed primarily for Ubuntu, and I cannot guarantee that they will work on other distributions. Unfortunately, I'm not likely to be of much help here.

**Comment by satirdanKahraman** [comment]
thanks for helping. You have been very helpful. :)

**Comment by Shatur** [comment]
> thanks for helping. You have been very helpful. :)

You can try to download an appimage from the releases page.
