### ISSUE TITLE
Add other Neural Technology use services as Promt, DeepL, Watson, Reverso, Systran

### ISSUE THREAD

**Issue by SWatB-com** [crow-translate/crow-translate#328]
I propose to add other services using neural technologies for translation.
In particular, add the following services: Promt, DeepL, Watson, Reverso, Systran.
I would like a full-fledged, and even better alternative to the Qtranslate program, which is strongly outdated and has not been updated for a long time.

Original Russian text:
Предлагаю добавлять прочие сервисы, использующие нейронные технологии для перевода.
В частности, добавить следующие сервисы: PROMT, DeepL, Watson, Reverso, Systran.
Хотелось бы полноценную, и даже более лучшую альтернативу программы QTranslate, которая сильно устарела и давно не обновляется.

**Comment by Shatur** [comment]
I already have a suggestions about it in [QOnlineTranslator](https://github.com/crow-translate/QOnlineTranslator/issues) repository.
Now I don't have enough time, but if someone wants to add some new engine - PR is welcome.
