### ISSUE TITLE
Icons from main interface not loaded into AppImage

### ISSUE THREAD

**Issue by eduardomozart** [crow-translate/crow-translate#329]
**Bug description**

Icons from AppImage isn't shown into Deepin 20.2.2.

**Steps to reproduce**

**Expected behavior**

Icons should be shown into main interface.

**Screenshots**

![crow-translate](https://user-images.githubusercontent.com/2974895/125365893-76326a80-e34b-11eb-8788-e793a28eb6c7.jpg)

**Environment**

- OS: Deepin 20.2.2 
- Desktop environment: DDE 
- Crow Translate version: 2.8.4 

**Additional context**

**Comment by Shatur** [comment]
Unfortunately, this is an appimage issue.
I have the same with other appimages for applications that have themed icons.

**Comment by Shatur** [comment]
The issue was fixed by #426.
