### ISSUE TITLE
Transifex approval

### ISSUE THREAD

**Issue by TeknoMobil** [crow-translate/crow-translate#33]
Hello there
I want to start translation, but I've been waiting for confirmation for a week
https://www.transifex.com/crow-translate/crow-translate/
(Turkish translate)

Respects

**Comment by Shatur95** [comment]
Hello!
Oh, sorry, for some reason, I did not receive an alert :(
Done, please, check it again.

**Comment by TeknoMobil** [comment]
Yes I'm starting ready translation
Thanks :)
