### ISSUE TITLE
The icons in Crow Translate lost even I have tried to configure the qt5ct

### ISSUE THREAD

**Issue by WXZhao7** [crow-translate/crow-translate#330]
**Bug description**
The icons in Crow Translate lost even I have tried to configure the qt5ct. I don't know how to solve this problem.

**Steps to reproduce**
1. Install Crow Translate by dpkg
2. Install libqt5svg5, qt5ct by apt-get
3. add `export QT_QPA_PLATFORMTHEME=qt5ct` to ~/.profile
4. restart and run with `QT_QPA_PLATFORMTHEME=qt5ct crow`

**Screenshots**
![image](https://user-images.githubusercontent.com/56864878/125801698-d743482c-b7df-43f2-9764-fe60e4b6cbd5.png)
![image](https://user-images.githubusercontent.com/56864878/125802081-02150657-2d71-4b86-adda-401e8066fbc0.png)
![image](https://user-images.githubusercontent.com/56864878/125802192-10da3c10-f7b2-4a78-b06a-57793a798ac1.png)
![image](https://user-images.githubusercontent.com/56864878/125802228-6520a8be-a176-4e33-a40c-018da9bbb2c5.png)

**Test**
* If I set Appearence-style to gtk2 or run with `QT_QPA_PLATFORMTHEME=gtk2 crow`, "pk-gtk-module" error will occur. Some of the icons in the main interface lost, but the icons in Settings work well.
![image](https://user-images.githubusercontent.com/56864878/125804693-3f49d1db-b93e-45ca-94d8-d8ec454e3c07.png)
![image](https://user-images.githubusercontent.com/56864878/125808137-f04e1ec5-0c81-459d-be3e-3fe497a6c871.png)
![image](https://user-images.githubusercontent.com/56864878/125807144-bb3956f0-c818-4907-baf3-16b91c34cb62.png)
* If I use other styles, all icons almost lost.
![image](https://user-images.githubusercontent.com/56864878/125805714-a6e545d4-d56c-4cd0-a554-ba52073abe74.png)
![image](https://user-images.githubusercontent.com/56864878/125807724-18855ae8-252a-4c46-b20b-33ad0c299e8f.png)
![image](https://user-images.githubusercontent.com/56864878/125808279-601533a7-ddf4-4ccb-853e-c0b48af9b768.png)

**Environment**

- OS: Ubuntu 20.04.2 LTS
- Desktop environment: GNOME 3.36.8
- Crow Translate version: 2.8.4

**Additional context**
I have read https://github.com/crow-translate/crow-translate/issues/198 and googled a lot, but I still can't deal with trouble about QT. I need help.

**Comment by Shatur** [comment]
Hm... Could you try to install https://github.com/FedoraQt/adwaita-qt and run the translator with `QT_STYLE_OVERRIDE=adwaita`?

**Comment by WXZhao7** [comment]
> Hm... Could you try to install https://github.com/FedoraQt/adwaita-qt and run the translator with `QT_STYLE_OVERRIDE=adwaita`?
I try to start qt5ct with adwaita, it seems work well.
![image](https://user-images.githubusercontent.com/56864878/125815538-cc74b2ca-6788-4de9-978f-8ad64cddb5dd.png)
But nothing changed for `QT_STYLE_OVERRIDE=adwaita crow`....
![image](https://user-images.githubusercontent.com/56864878/125816162-55fea0f9-46a9-4eb7-bc69-4a54902e95f0.png)

**Comment by WXZhao7** [comment]
> Hm... Could you try to install https://github.com/FedoraQt/adwaita-qt and run the translator with `QT_STYLE_OVERRIDE=adwaita`?

After install adwaita,  Adwaita-Dark and  Adwaita are added to style list.
![image](https://user-images.githubusercontent.com/56864878/125818828-9367d2ff-4e52-4913-83a9-2127a06cc171.png)
But if I run `QT_STYLE_OVERRIDE=qt5ct crow`, another warning occured: `QApplication: invalid style override passed, ignoring it.`
![image](https://user-images.githubusercontent.com/56864878/125819440-630fe0ab-8d55-47ba-a095-a8d6e8610b92.png)

**Comment by Shatur** [comment]
> After install adwaita, Adwaita-Dark and Adwaita are added to style list.

No, I meant to start it with `QT_STYLE_OVERRIDE=adwaita` (e.g. without qt5ct).

**Comment by Shatur** [comment]
Never mind, I tried it myself on my VM - the issue exists even without qt5ct.
So yes, for unknown reason gnome does not respect fallback icons... The application has built-in icons that are displayed when there are no such icons in the current theme. And for some reason this mechanism doesn't work in Gnome, but it does work in KDE.

As a temporary workaround you could install Breeze (`breeze-icon-theme`) or [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) that have all icons and set the theme via `qt5ct` (for Qt applications only) or system-wide if you want to have consistent icon theme.

**Comment by WXZhao7** [comment]
> Never mind, I tried it myself on my VM - the issue exists even without qt5ct.
> So yes, for unknown reason gnome does not respect fallback icons... The application has built-in icons that are displayed when there are no such icons in the current theme. And for some reason this mechanism doesn't work in Gnome, but it does work in KDE.
> 
> As a temporary workaround you could install Breeze (`breeze-icon-theme`) or [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) that have all icons and set the theme via `qt5ct` (for Qt applications only) or system-wide if you want to have consistent icon theme.

Thanks! The [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) really provide correct icons except the menu icons of tray (I'm not sure about the name).
![image](https://user-images.githubusercontent.com/56864878/125874898-dfeab5da-eb0e-46d9-9dfa-6bcad3d2e5fd.png)
![image](https://user-images.githubusercontent.com/56864878/125875745-a171e2c5-3590-4b60-a73b-2c12a6d93709.png)
Now I consider to work with KDE + Arch Linux instead of GNOME + Ubuntu~

**Comment by Shatur** [comment]
> Thanks! The Papirus icon theme really provide correct icons

Glad to hear. But let's leave issue open because this is a bug. I hope someone will help me with a solution.

> except the menu icons of tray

This is another GNOME related issue. Since GNOME does not support the system tray, it is added by a third-party extension. And this extension does not take into account icon themes (as you can see, the Crow icon did not change its appearance even when using the Papirus icon theme).

>  Now I consider to work with KDE + Arch Linux instead of GNOME + Ubuntu~

Good choice :)

**Comment by azjio** [comment]
Make 3 Switch Positions:
1) icons from the system theme
2) Built-in badges for white theme
3) Built-in badges for black theme

One icon is only 1 KB, there will be 20 KB of place, but there will never be a problem of icons.

**Comment by Shatur** [comment]
> One icon is only 1 KB, there will be 20 KB of place, but there will never be a problem of icons.

Icons are already built-in. The issue with GNOME itself.

**Comment by azjio** [comment]
anarchy_x64 + Cinnamon + qt5ct

![Crow](https://user-images.githubusercontent.com/8190038/127718447-e59ade23-9962-4915-aa0d-af0af152345f.png)

**Comment by Shatur** [comment]
> anarchy_x64 + Cinnamon + qt5ct

Yes, it's because Cinnamon is a fork of GNOME.

The icons are built-in using this resources [file](https://github.com/crow-translate/crow-translate/blob/master/data/icons/we10x.qrc).
Unfortunately GNOME (and maybe other GTK-based environments) does not respect virtual `hicolor` folder that overridden inside Qt applications. If someone know a proper fix for it - please, let me know.

**Comment by VolkMilit** [comment]
I don't think it's GNOME or GTK-related issues. Crow is working fine on XFCE4, Arch Linux, even **without** qt5ct or qt5-styleplugins. But I use SDDM to launch session, maybe that is the reason.

**Comment by sikmir** [comment]
I use Crow on NixOS and the same problem there - no icons, I've tried to use qt5ct/adwaita-qt5/qtstyleplugins, but no luck..

**Comment by WXZhao7** [comment]
@Shatur The tray icons is controlled by system icons on Ubuntu20! It looks fancy~
![ep](https://user-images.githubusercontent.com/56864878/158051888-f87a74b4-4032-4c7e-8a83-8721f27c3db3.png)

**Comment by sikmir** [comment]
Just in case, installing `papirus-icon-theme` on NixOS solves the issue with icons for me.

**Comment by Shatur** [comment]
Yes, as I said [here](https://github.com/crow-translate/crow-translate/issues/330#issuecomment-880948898) its because `papirus-icon-theme` have all required icons.
If the some icons are missing, then they should be taken from the icons built into the application. But for some reason it doesn't happen on Gnome.

**Comment by gasinvein** [comment]
@Shatur I think I've found a way to make the fallbak icon theme work, see here #426. Tested on GNOME with Adwaita icons and and various non-Breeze Qt styles.
