### ISSUE TITLE
gpg: keyserver receive failed: Server indicated a failure

### ISSUE THREAD

**Issue by snorlax212** [crow-translate/crow-translate#332]
**Bug description**
Hello. When I try to install crow translate error appears:

```
$ sudo add-apt-repository --enable-source ppa:jonmagon/crow-translate
 Crow Translate is a simple and lightweight translator programmed in C++ / Qt that allows to translate and speak text using Google, Yandex and Bing translate API.
GitHub: https://github.com/crow-translate/crow-translate
 More info: https://launchpad.net/~jonmagon/+archive/ubuntu/crow-translate
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpjiy4xnki/pubring.gpg' created
gpg: keyserver receive failed: Server indicated a failure

```
And then:
```
$ sudo apt install crow-translate
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package crow-translate
```

**Steps to reproduce**
```
sudo add-apt-repository ppa:jonmagon/crow-translate
sudo apt update
sudo apt install crow-translate
```
**Expected behavior**
Successful installation

**Environment**

- OS: Debian GNU/Linux 11 (bullseye)
- Desktop environment: Xfce 4.16
- Crow Translate version: 2.8.4

**Comment by Shatur** [comment]
@JonMagon hi! Could you look into it?

**Comment by JonMagon** [comment]
It says that you cannot connect to the key server. The problem is on your side.

**Comment by Shatur** [comment]
@JonMagon, thank you! I just came across very little with Debian-based distros.
Maybe it's because it's an Ubuntu PPA. Try to add PPA GPG key manually. Like [here](https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux).

**Comment by snorlax212** [comment]
> @JonMagon, thank you! I just came across very little with Debian-based distros.
> Maybe it's because it's an Ubuntu PPA. Try to add PPA GPG key manually. Like [here](https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux).

Yes, adding GPG key manually did the trick. Thank you.
But now I encounter another problem during apt install:


```
root@snorlax212pc:/home/snorlax212# apt install crow-translate 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  crow-translate
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
3 not fully installed or removed.
Need to get 0 B/1,072 kB of archives.
After this operation, 3,668 kB of additional disk space will be used.
dpkg-deb: error: archive '/var/cache/apt/archives/crow-translate_2.8.4-impish_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/crow-translate_2.8.4-impish_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/crow-translate_2.8.4-impish_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```
I removed '/var/cache/apt/archives/crow-translate_2.8.4-impish_amd64.deb'  and tried again - same. I googled and some results appears like dpkg doesn't support zst compression, but it sounds nonsense. My dpkg version:
```

root@snorlax212pc:/home/snorlax212# dpkg --version
Debian 'dpkg' package management program version 1.20.9 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
```

**Comment by JCGoran** [comment]
The "unknown compression format" issue seems to be reported [upstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664), but it hasn't been resolved yet.
I managed to install it successfully with the following procedure (can probably be automated):
1. extract the `.deb` file somewhere with `ar x [DEB FILE]`
2. uncompress all of the zstd files by running `unzst *.zst`
3. re-compress the tar archives with `gzip *.tar`
4. remove the old `.deb` file, and then create a new one with `ar cr crow-translate_[VERSION]_[PLATFORM].deb debian-binary control.tar.gz data.tar.gz`. Note that the order of the included files seems to be important.
5. install the newly-create `.deb` file with either `dpkg -i` or `gdebi` (the latter should properly handle any missing dependencies)

**Comment by Shatur** [comment]
I assume that the issue can be closed.
