### ISSUE TITLE
crow translate 2.8.5 - feedback/bug fix

### ISSUE THREAD

**Issue by bovirus** [crow-translate/crow-translate#337]
**Bug description**

Pelase check screenshoty for details

![image](https://user-images.githubusercontent.com/1262554/131486526-e3df7a03-dbe3-4198-b9df-f889da48236a.png)
The link point to not existing page

![image](https://user-images.githubusercontent.com/1262554/131486567-a9b80a52-4209-4407-ba92-6d059977e523.png)
Please fix typo in translation (Tarduci - Traduci)
Colum size cannot b adjusted

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS: 
- Desktop environment: 
- Crow Translate version: 

**Additional context**

**Comment by Shatur** [comment]
Thanks, fixed!

>  Colum size cannot b adjusted

This is intentional. The columns automatically adjust to the size of the content. I use [QHeaderView::ResizeToContents](https://doc.qt.io/qt-5/qheaderview.html#ResizeMode-enum).

**Comment by bovirus** [comment]
@Shatur 

Did you fix in the language file the typo and the wrong link in the source code?

**Comment by Shatur** [comment]
Yes!

**Comment by bovirus** [comment]
@Shatur 

Thanks.
