### ISSUE TITLE
[Gnome] "Translate selected text" shorctut works incorrectly if different layouts for each window are enabled

### ISSUE THREAD

**Issue by hexauniverse** [crow-translate/crow-translate#34]
The behavior is quite strange: if i leave the key combination pressed down, the popup eventually appears.
If I disable different ones and use the same layout the shortcut starts working normally.

It happens on both xorg and xwayland.

**Comment by hexauniverse** [comment]
this was appeared after 2.0.1 update

**Comment by Shatur95** [comment]
Do I understand correctly that with different layouts of each windoww, translate popup sometimes does not appear?

**Comment by hexauniverse** [comment]
I mean this setting:

![](https://i.imgur.com/gkbMfhI.png)

**Comment by hexauniverse** [comment]
> Do I understand correctly that with different layouts of each window, translate popup sometimes does not appear?

no, it's appears always, but I have to hold down the keys for a long time

**Comment by Shatur95** [comment]
I think this may be related to your internet connection. Could you please try always to not hold the shortcut and just wait? Does a pop-up window appear in this case?

**Comment by hexauniverse** [comment]
> I think this may be related to your internet connection.  

no, i used different internet connections on 2 devices

> Does a pop-up window appear in this case?

no

**Comment by hexauniverse** [comment]
a little demo: https://i.imgur.com/PDADWqM.gif

**Comment by Shatur95** [comment]
Weird bug. Okay, I'll try to download GNOME and will try to fix it. What disto are you using?

**Comment by hexauniverse** [comment]
> What disto are you using?
arch

**Comment by hexauniverse** [comment]
it seems that the bug disappeared after 3.34 update
