### ISSUE TITLE
Appears on the wrong workspace if already running

### ISSUE THREAD

**Issue by JCGoran** [crow-translate/crow-translate#342]
**Bug description**
After clicking on the tray icon, the program appears on the old workspace if there's another instance of it already running on another workspace.
This could be XFCE4-specific though, but I think it's worth checking whether the problem is on this end, as other programs don't exhibit the same behavior.

**Steps to reproduce**

1. click on the tray icon
2. switch to another workspace
2.a. (optional) minimize the crow window
3. click on the tray icon again

**Expected behavior**

The crow window should appear on the currently focused workspace, but instead it appears (maximized if it was minimized earlier) on the one where it was running last.
The workaround is to close the crow window first, switch workspaces, and then click on the tray icon.

**Environment**

- OS: Debian Linux (Sid/Unstable) 
- Desktop environment: XFCE4 with `xfce4-panel` 4.16.3 
- Crow Translate version: 2.8.4

**Comment by Shatur** [comment]
Could you please check if the problem exists with other Qt applications?

**Comment by JCGoran** [comment]
Any recommendations for Qt apps that come with a systray/notification area icon? I don't seem to be using any (except crow), and I'd like to investigate this further.

**Comment by Shatur** [comment]
You could try qBitTorrent, Telegram or KeepassXC.

**Comment by JCGoran** [comment]
I've tried out KeepassXC 2.6.2 and qBittorrent 4.2.5, and, with the same settings (both minimize and close to tray), they seem to work differently from crow: in both cases, I can click on the tray icon a couple of times and it will bring the program up, while crow seems to be stuck on the same workspace no matter what I do (both left click, and right click → show window).
Note that it seems that they have different behavior on first click (on the tray icon): qBittorrent seems to always close the window on the other workspace first, and then only on the second click it displays it on the correct workspace again, while KeepassXC will spawn the window on the correct workspace, but only _after some interaction_ (like clicking anywhere on the screen with the mouse).

**Comment by VolkMilit** [comment]
@JCGoran, do you build Crow yourself? Can you, please, check if my patch fix your issue?
