### ISSUE TITLE
Sources of 2.8.7 version have 2.6.7 version in all

### ISSUE THREAD

**Issue by katnatek** [crow-translate/crow-translate#347]
**Bug description**

The recently 2.8.7 version is tagged as 2.6.7 version , the sources have that version too

**Steps to reproduce**

1. Go to  https://github.com/crow-translate/crow-translate/releases
2.  Go to 2.8.7 release
3. Put mouse pointer on  Source code (zip) or Source code (tar.gz)
4. You clearly see are urls for 2.6.7 version
5. If you download the sources you get a file with 2.6.7 version containing a folder with the same version

**Expected behavior**

Tagg, files and folder inside Source files be 2.8.7

**Comment by Shatur** [comment]
Oh, thanks! Fixed!
