### ISSUE TITLE
(Feature Request) Offline Translation

### ISSUE THREAD

**Issue by dtantono** [crow-translate/crow-translate#351]
Hi
I am just curious. is it possible for this app to have other feature for conduct offline translation by downloading offline data beforehand?

**Comment by Shatur** [comment]
Hi, no, no provider provides this option. But offline translation can be added in the future using OpenNMT: https://github.com/crow-translate/QOnlineTranslator/issues/5

**Comment by magdesign** [comment]
any news on offline features with library's from https://github.com/argosopentech/argos-translate

**Comment by magdesign** [comment]
any news for offline translation?
or any dirty hack to use https://github.com/argosopentech/argos-translate library...

**Comment by Shatur** [comment]
There are requested providers in https://github.com/crow-translate/QOnlineTranslator/issues, but I'm too busy to implement. If you are interested - PRs are welcome.
