### ISSUE TITLE
Highlight both the source and transalted sentenses on click 

### ISSUE THREAD

**Issue by mohamad-b** [crow-translate/crow-translate#363]
Sometimes the translation is inaccurate or wrong, so I need to go back to the source language to get the meaning, but it's hard to find the source text with a long text.
It would be great if the app automatically identifies and highlight both the translated and source sentence by just clicking on any word within the sentence, the highlight can be just by changing the color of both sentences to another clear color.

**Comment by Shatur** [comment]
Unfortunately, this is not possible, since no translation service provides such feature. And I can't detect it on the application side.
