### ISSUE TITLE
Suggestion to add the dark mode option

### ISSUE THREAD

**Issue by erlonpr** [crow-translate/crow-translate#364]
I would like to suggest adding the **dark mode** option inside the Interface tab so that Linux users who like to use this feature in their operating system can also use it in Crow Translate in a practical and easy way.

**Comment by Shatur** [comment]
The app uses a system theme. If you use a dark theme in your system, it will be used automatically. If you are using a GTK-based environment, then you need to configure the appearance of the Qt application globally. I cannot configure this from the application.

**Comment by hwndmaster** [comment]
@Shatur Is it also applicable to Windows systems?

I have Windows 10 Pro (v10.0.19044.1586) and a dark theme is selected system-wide (so all theme-compatible apps do also render in dark mode), but Crow Translate still being rendered in a default light mode, same as on screenshots in readme.md of the repo.

**Comment by Shatur** [comment]
> @Shatur Is it also applicable to Windows systems?

I don't know... Do you have any other Qt applications which supports dark mode in Windows?

**Comment by hwndmaster** [comment]
> Do you have any other Qt applications which supports dark mode in Windows?

I think Telegram Desktop is using Qt, but it could be that a theming has custom implementation there.
I can also find dependencies on Qt in the following apps: GOG Galaxy (a game store), Blackmagic Design DaVinci Resolve (video editor), [DupeGuru](https://github.com/arsenetar/dupeguru/releases/tag/4.2.1)

DupeGuru might be the best example since it has [source code](https://github.com/arsenetar/dupeguru) available on github. The dark mode looks a bit clumsy there but it works.

**Comment by Shatur** [comment]
> DupeGuru might be the best example since it has [source code](https://github.com/arsenetar/dupeguru) available on github. The dark mode looks a bit clumsy there but it works.

Thanks for the info. Could you open a separate issue (bug) for it? Application should respect system theme.
I currently don't have a Windows machine with dark theme support, but I would appreciate if anyone will take a look into it.

**Comment by Shatur** [comment]
There is nothing we could do until migration to Qt6.

**Comment by 1821746019** [comment]
> There is nothing we could do until migration to Qt6.

I suddenly have an idea. Maybe I can make a hook for the software when it wants to acquire the system settings.

**Comment by Shatur** [comment]
The program does not read system settings. Qt subsystem should do it and apply theming. But looks like it supported only in Qt6. We will migrate to it, but a bit later. If you want to help - you can try to port the app now, I will merge the PR and compile Windows version with Qt6.

**Comment by 1821746019** [comment]
Thank you for your enthusiastic invitation. I am glad to do that but my poor programming skills do not allow me. I have just learn cpp for half  a year.

**Comment by Gentleman03** [comment]
> The program does not read system settings. Qt subsystem should do it and apply theming. But looks like it supported only in Qt6. We will migrate to it, but a bit later. If you want to help - you can try to port the app now, I will merge the PR and compile Windows version with Qt6.

Is there any planned date for switching to Qt6? Dark mode is a dealbreaker for me.

**Comment by Shatur** [comment]
Yes, but I currently busy. But I merge PRs ASAP.

**Comment by Gentleman03** [comment]
> Yes, but I currently busy. But I merge PRs ASAP.

That's great! Could you share with us when we can expect Qt6 version?
