### ISSUE TITLE
Crow Translate 2.8.7 - String untranslated

### ISSUE THREAD

**Issue by bovirus** [crow-translate/crow-translate#377]
@Shatur 

**Bug description**

There is string untranslated.
Pelase check screenshot.

![image](https://user-images.githubusercontent.com/1262554/137734565-d6638313-ab08-4f3a-8d2a-26083dc5784b.png)

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS: 
- Desktop environment: 
- Crow Translate version: 

**Additional context**

**Comment by VolkMilit** [comment]
No, no, I mean your Linux distribution?
