### ISSUE TITLE
Trasnlation Icon after selecting text

### ISSUE THREAD

**Issue by BEST8OY** [crow-translate/crow-translate#386]
Hi
I can't get the job done just with mouse

After selecting text i would like some icon appear for translate or voice ...
![Screenshot (9)](https://user-images.githubusercontent.com/70865987/145871810-d7a91996-1b02-46c2-b32f-3088d3f946cc.png)

**Comment by VolkMilit** [comment]
It would be almost impossible for Windows and Wayland, because they are doesn't have unified selection buffer, like X11. This is possible only on program-level (i.e. program will use Crow API of some kind, and catch selection in program window), not system-level.
