### ISSUE TITLE
Simplify Source Doesn't Work

### ISSUE THREAD

**Issue by mustifanci** [crow-translate/crow-translate#387]
**Bug description**
i read many journals with pdf file. When i need translate text, the app translate with line break. How can i remove line break.

**Screenshots**
*![Ekran görüntüsü 2021-12-18 00-10-52](https://user-images.githubusercontent.com/40540308/146609627-97d213ce-1a41-40e3-bb96-d3cbf6ee027f.png)
![Ekran görüntüsü 2021-12-18 00-11-25](https://user-images.githubusercontent.com/40540308/146609612-30341c13-b140-4387-b567-ceeb1223d5f3.png)

**Environment**

debian
gnome
- Crow Translate version:  2.9.1

**Comment by Shatur** [comment]
Please, fill the issue according to template.
