### ISSUE TITLE
Add clear field icon

### ISSUE THREAD

**Issue by omega3** [crow-translate/crow-translate#39]
Please, add clear this field icon / option, as it is possible on original Bing / Google translators sites.

I marked this in red color:
https://imgur.com/MPH8e8r

It makes use more comfortable, because user doesn't need to mark the whole text before deleting and pasting a new one.

**Comment by Shatur95** [comment]
Unfortunately, Qt does not provide such buttons for QTextEdit, since this is not standard for interfaces. I could hack it, but this is not a good idea, I think.

**Comment by omega3** [comment]
I see. I am not a developer but I just typed in google:
QTextEdit+clear text 
and found this

https://stackoverflow.com/questions/15103409/trying-to-clear-a-textedit-box-in-qt-c-using-qt-creator

https://doc.qt.io/qt-5/qlineedit.html#clearButtonEnabled-prop

https://geocap.atlassian.net/wiki/spaces/ref/pages/6980082/qtextedit+-+multiline+text+editor

Anyway, if it is not useful forgive me my ignorance.

**Comment by Shatur95** [comment]
Yes, clearing the text is not a problem :)
But to add a separate button inside QTextEdit is the creation of a custom widget, which I try to avoid.
