### ISSUE TITLE
Translate data streams in linux

### ISSUE THREAD

**Issue by x4IPx** [crow-translate/crow-translate#395]
Hello everyone
Thank you for the application. It helps me a lot in learning the language.

Faced with the fact that I lack the ability to translate the output of terminal commands directly into the console. 
For example, I have no way to translate the output of the `git help` command by running :
`git help|crow`

I would like to be able to translate the output of commands using (stdout/stderr) Data Streams .

Examples of using Data Streams :
https://www.howtogeek.com/435903/what-are-stdin-stdout-and-stderr-on-linux/

**Comment by Shatur** [comment]
Use `--stdin` [flag](https://github.com/crow-translate/crow-translate#cli-commands).
