### ISSUE TITLE
hotkeys for clear input screen and switch between input languages

### ISSUE THREAD

**Issue by tom-vb** [crow-translate/crow-translate#396]
Would it be possible to add a hotkey to clear the input screen and another to switch between input languages?

thanks,
best regards

**Comment by Shatur** [comment]
Please fill in according to the template and I will open the issue again.

**Comment by tom-vb** [comment]
Hello, thanks for answering,
I will do it with pleasure, but what template are you referring to? I am not able to find any template

**Comment by Shatur** [comment]
@tom-vb when you opening a new issue, it alredy provides you a template. But you can also copy it starting from this line: https://github.com/crow-translate/crow-translate/blob/eddd38e8a7341096efa7663aa692acbb82b500c8/.github/ISSUE_TEMPLATE/feature_request.md?plain=1#L9
