### ISSUE TITLE
Output text formatting

### ISSUE THREAD

**Issue by tom-vb** [crow-translate/crow-translate#399]
**Describe the problem or limitation you are having**
The output format is a text without any formatting not even line breaks 

**Describe the solution you'd like**
If possible, would be great at least respect the line breaks that we have in the input text in the output text. It would be much more usable and pleasant.

**Additional context**
![image](https://user-images.githubusercontent.com/83949165/155890000-c66c1a48-9c51-4d73-bf80-4bf537fe4b5d.png)

**Comment by Shatur** [comment]
Disable "Simplify source" in translation settings.

**Comment by tom-vb** [comment]
opps, thanks!
