### ISSUE TITLE
Error transferring bing.com/tdetect - server replied: Not Found

### ISSUE THREAD

**Issue by omega3** [crow-translate/crow-translate#40]
When Bing is selected in speech synthesis I get error:

https://imgur.com/K9LnsKO

Error transferring http://www.bing.com/tdetect - server replied: Not Found

**Comment by Shatur95** [comment]
It looks like something wrong with Bing :(
Bing Translate API not available at all for now (translation and language detection not work too).

**Comment by Shatur95** [comment]
Solution [found](https://github.com/soimort/translate-shell/issues/311). I will fix it ASAP.
