### ISSUE TITLE
Sometimes, "Translate selected text" pop up a textbox with no text, depending on how I selected it.

### ISSUE THREAD

**Issue by rizzini** [crow-translate/crow-translate#400]
**Bug description**
Mostly on Reddit comments, if I select an entire paragraph with two clicks, the translation appears empty when pressing the "Translate selected text" hotkey. It works if I manually select the text.

**Steps to reproduce**
1. Select an entire paragraph of some Reddit comment by clicking twice.
2. Press the "Translate selected text" hotkey.

**Expected behavior**
Some kind of anticipation regarding what may change when using each way to select the text, clicking twice, or manually selecting it.

**Screenshots**
Vídeo -> https://imgur.com/a/ffdfe74

**Environment**

- OS: Arch Linux
- Desktop environment:  KDE
- Crow Translate version: 2.9.1

**Comment by Shatur** [comment]
I have the same issue with discord. I assume that something wrong with the application itself. E.g. selection buffer not always populated.

**Comment by rizzini** [comment]
> I have the same issue with discord. I assume that something wrong with the application itself. E.g. selection buffer not always populated.

True. It happens on discord here as well.

**Comment by Shatur** [comment]
No sure how to solve this for now.

**Comment by VolkMilit** [comment]
Hopefully fixed in PR #455, feel free to reopen this issue, if the problems still occurs.

**Comment by rizzini** [comment]
Oh my god.. It works seemly with everything now. This is a huge improvement, guys. 👏👏

**Comment by rizzini** [comment]
It's happening again since v2.9.11.

**Comment by Shatur** [comment]
Try 2.9.12, it should work now.

**Comment by rizzini** [comment]
Confirmed. Thank you.
