### ISSUE TITLE
Add a function to auto detect the text in an area and translate when text changes.

### ISSUE THREAD

**Issue by wuyudi** [crow-translate/crow-translate#402]
**Describe the problem or limitation you are having**

Currently, I am just beginning to use this tool. So I may miss this function in the manual. Please feel free to correct me.
I am playing a game, so I want to translate the dialog in the game, but I have to re-select the frame and translate it again and again.

**Describe the solution you'd like**

I use pseudo code to show my solution.

```py
while True:
    time.sleep(1000ms)
	img = screenshot()
	if img == last_img:
    	continue
	else:
    	ocr
 	    translate
   	    last_img = img
```

or

```py
while True:
    time.sleep(1000ms)
	img = screenshot()
    text = ocr(img)
	if text == last_text:
    	continue
	else:
 	    translate
   	    last_text = text
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Shatur** [comment]
Sorry, but such functionality doesn't match my vision of the application.

**Comment by wuyudi** [comment]
Anyway, thanks for the inspiration, I've done my small script. https://gist.github.com/wuyudi/d39be36fba365ec93115cbf7a7f417b4
