### ISSUE TITLE
Pin to dock Ubuntu

### ISSUE THREAD

**Issue by jmsgm00** [crow-translate/crow-translate#405]
I can't pin the icon to the dock in ubuntu 20. It always hides, I don't like it, I don't see an option in preferences either.  Is there any way to fix it? 

There is no option to add to favorites

Thanks
![Captura de pantalla de 2022-03-18 15-53-21](https://user-images.githubusercontent.com/101873276/159026600-2e582e39-14e7-4c02-8134-1371f18f8eca.png)

**Ubuntu 20.04 - Gnome**

**Comment by jmsgm00** [comment]
And if I add it from the app drawer, the app is duplicated every time it is opened :(
![2022-03-18_16-08](https://user-images.githubusercontent.com/101873276/159029209-67bec444-53cc-4dfa-b18d-07f8143132b2.png)

**Comment by Shatur** [comment]
Does this problem exist with other applications using Qt? For example, KeepassXC or QBittorrent.

**Comment by jmsgm00** [comment]
No, it only happens with crow, although I have seen that it can happen with other apps made for KDE. [I have followed this tutorial ](https://www.youtube.com/watch?v=xZ_M3Q-U-J0)adding the last line of code but it still doesn't work. You can help me? It is very annoying to have 2 icons. 
![photo_2022-03-19_11-14-59](https://user-images.githubusercontent.com/101873276/159117958-4c1169e1-fd4a-4d31-9009-76991c567ea4.jpg)

**Comment by Shatur** [comment]
Could you try adding the mentioned line into the first section?

**Comment by jmsgm00** [comment]
Here? It still doesn't work. Too bad, it's the best translator for linux but I can't use it that way :(
![2022-03-19_17-26](https://user-images.githubusercontent.com/101873276/159129832-42f6d646-69f1-4838-9dc3-139e774bd53e.png)

**Comment by Shatur** [comment]
> Here? It still doesn't work. Too bad, it's the best translator for linux but I can't use it that way :(

Yes. But could you try using `StartupWMClass` instead of `StartupWMclass`?
Another idea is to try to set it to `io.crow_translate.CrowTranslate` instead of `crow`.

**Comment by jmsgm00** [comment]
Oh yeah! sorry, sorry! it was the "c", beginner's mistake. Now it works! Thanks a lot! How can I donate to the project?

By the way, last question, I have some missing icons, do you know what specifically to install qt5 to solve it in Ubuntu? Thanks again!

![2022-03-19_17-43](https://user-images.githubusercontent.com/101873276/159130250-4e6fe947-3667-43a7-8168-a3d327b133bd.png)

**Comment by Shatur** [comment]
> Oh yeah! sorry, sorry! it was the "c", beginner's mistake. Now it works!

Great, I will add `StartupWMClass=crow` to the `.desktop` file.

> Thanks a lot! How can I donate to the project?

Unfortunately, this is currently not possible. There is no donation service that works with in my country.

> By the way, last question, I have some missing icons, do you know what specifically to install qt5 to solve it in Ubuntu?

It's a known issue on GNOME, for some reason it doesn't consider builtin icons as a fallback, see #330.
As a workaround I would recommend you to install [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) that contains all necessary icon (or any other icon theme with many icons).
