### ISSUE TITLE
Add Dictionary mode to show a single word detailed description instead of translation

### ISSUE THREAD

**Issue by MurzNN** [crow-translate/crow-translate#408]
**Describe the problem or limitation you are having**
Sometimes I need to understand some single word deeply, not with a translation, but with looking up the dictionary with detailed explanation and examples of usage. But [crow-translate](https://github.com/crow-translate/crow-translate) now gives me ability to only translate the word.

**Describe the solution you'd like**
Will be good to add integration with some online dictionaries, that provide integration via API, I've found several ones:
https://developer.oxforddictionaries.com/
https://dictionaryapi.dev/
and will add more later.

And add the optional auto-detection mode, if in source text there is only one word, auto switch to dictionary mode instead of translation.

Additionally, will be good to have ability to quickly see a dictionary description of a selected word in app's textarea.

**Describe alternatives you've considered**
Alternatively we can make integration with some other external app, or at least show a link to dictionary websites, but native integration will be much better.

**Comment by Shatur** [comment]
Sorry, but dictionary integration is out of scope. Some online engines like google provides translation options for a single word. For example:
![изображение](https://user-images.githubusercontent.com/22453358/162410108-85d6512e-1dbe-4f5e-9681-f748f265dfff.png)

**Comment by MurzNN** [comment]
Yeah, Google engine provides good dictionary-like results for single words, that's great! But other dictionaries provide more detailed description of words, and I understand that integration of them to crow is not so quick task.

So I'll check some other software that can fit those needs and put here links while found something suitable.
