### ISSUE TITLE
Close translation popup by Escape

### ISSUE THREAD

**Issue by kapsh** [crow-translate/crow-translate#41]
It would be convenient and faster to close translation popup with Esc or other customizable shortcut.

**Comment by Shatur95** [comment]
Pop-up window is just a window :) You can use Ctrl + Q or Alt + F4 to close it (depending on your system settings).

**Comment by Shatur95** [comment]
Also Crow Translate already have this shortcut in settings.

**Comment by kapsh** [comment]
@Shatur95 Thanks, I've understood now. Translation mode was set to "pop-up window" and this window doesn't have settings for "close" action. I will use main window for this.

**Comment by VolkMilit** [comment]
@kapsh, I'm not Shatur, but I can help you. Popup window close with either esc or click outside it. It works for me on various DEs and various WMs, never had a single problem. So I don't understand your problems. Which DE are you using? Which server (Xorg or Wayland) are you using?

**Comment by kapsh** [comment]
@VolkMilit thanks for your concerns. Actually Esc closes popup window for me now. Perhaps that was just me misunderstood something first time.
