### ISSUE TITLE
Sometimes TTS engine pronounces `space` as "percent twenty"

### ISSUE THREAD

**Issue by MurzNN** [crow-translate/crow-translate#410]
**Bug description**
Sometimes when I press "Speak", Crow pronounce spaces as "percent twenty", seems because that string somehow converted to url where `space` is replaced to `%20`. Interesting thing that if I press "Speak" button again without making any changes in text, it sometimes is pronounced normally, sometimes - with `%20`.

This is reproducible with Google and Yandex TTS engines.

Here is the screencast with vice, that reproduce this issue: 
https://user-images.githubusercontent.com/336662/162793198-7d0449fe-73bf-4ab6-a8dd-167eb14e8dda.mp4

**Steps to reproduce**

1. Select some text with spaces, eg in web browser, even three words like "Personally Identifiable information".
2. Press the Crow hotkey to initiate the translation.
3. Press the "Speak" button below the source text.
4. Hear that spaces are pronounced sometimes as `%20`, but sometimes - normally.

**Expected behavior**
Spaces should not be pronounced sometimes as `%20`

**Screenshots**
N/a

**Environment**
- OS: Windows 10
- Crow Translate version: 2.9.2

**Additional context**
N/a

**Comment by Shatur** [comment]
Reproducible only on Windows. Will investigate.

**Comment by Shatur** [comment]
Actually now, I can't reproduce it on my Windows machine either. Magic happens [here](
https://github.com/crow-translate/QOnlineTranslator/blob/d1a89cb918a0292a01bdac5e83d08bb8d2e04d55/src/qonlinetts.cpp#L70). I tried playing with different variants (removing `toPercentEncoding` or changing parameters in `setQuery`) - the current variant is the only one which works for me.

I would appreciate if someone will play with this.

**Comment by gitgrub** [comment]
Same here on win 10.
It happens in settings/speech synthesis/speech test, too.

**Comment by veksha** [comment]
commit: https://github.com/crow-translate/QOnlineTranslator/commit/f24f47f72831aeaac1a85d0547a876b26fc69b54

![image](https://user-images.githubusercontent.com/275333/232171530-de33f982-1779-40e0-a302-df06629bcfd0.png)


maybe try revert this change?

more info about QUrl: https://doc.qt.io/qt-6/qurl.html

for example we see here that TolerantMode (default) "will try to correct some common errors in URLs".
maybe sometimes it fails?

![image](https://user-images.githubusercontent.com/275333/232171418-a10c501b-2a8a-4a64-9b4f-a11bea631a0e.png)

**Comment by veksha** [comment]
therefore "%" char sometimes converted to %25:
`https://translate.googleapis.com/translate_tts?ie=UTF-8&client=gtx&tl=en-AU&q=hi%2520there`

**Comment by Shatur** [comment]
> maybe try revert this change?

It's just refactoring, I don't think it helps.

> maybe sometimes it fails?

Not sure why. I can't even reproduce the issue. If you can - try to play with it on Windows report back what fixes the issue for you.

**Comment by veksha** [comment]
@Shatur how to build? I cloned repo and triggered github action, but job is failing for Windows.

**Comment by Shatur** [comment]
What error are you seeing?

It builds like a normal C++ project on Windows. You need to install vcpkg and run CMake with `-DCMAKE_TOOLCHAIN_FILE=<vcpkg-root>/scripts/buildsystems/vcpkg.cmake`. Compilation will take some time because Qt takes a long time to build.

**Comment by veksha** [comment]
i mean not cloned, but forked. i want to build in the cloud using github actions.
job failed: "error: https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404"

can we fix it? found related info: https://github.com/microsoft/vcpkg/pull/30546

**Comment by Shatur** [comment]
Oh, got it!
Bump vcpkg commit version in workspace file to the one with the included PR.

**Comment by veksha** [comment]
thanks, but there is new error:
`error: tesseract:x64-windows@5.3.0#1 does not have required feature cpu-independed`

**Comment by Shatur** [comment]
Looks like tesseract was updated and don't have this feature anymore. Try to replace these lines:
https://github.com/crow-translate/crow-translate/blob/472b73103cab76cd12a7971a5ec0f6152b93a362/vcpkg.json#L5-L8
with just `tesseract`.

**Comment by veksha** [comment]
ok, @Shatur .
removed `QUrl::DecodedMode`
from [apiUrl.setQuery(query, QUrl::DecodedMode);](https://github.com/crow-translate/QOnlineTranslator/blob/d1a89cb918a0292a01bdac5e83d08bb8d2e04d55/src/qonlinetts.cpp#L74)

testing on Windows11. all ok. why this was needed?

**Comment by veksha** [comment]
you did `toPercentEncoding` and after that used `DecodedMode`. seems not logical.

**Comment by Shatur** [comment]
> you did toPercentEncoding and after that used DecodedMode. seems not logical.

Agree, doesn't make much sense, but for some reason long time ago it solved the problem for me... Let me try it on my machine.
In the meanwhile, could you open a PR?

I also see that you added source text selection for #528. Any chance you could turn it into an option and send as a separate PR?

**Comment by Shatur** [comment]
> I also see that you added source text selection for https://github.com/crow-translate/crow-translate/issues/528. Any chance you could turn it into an option and send as a separate PR?

On second thought, I think this should be always on, it's simply convenient.

**Comment by Shatur** [comment]
Tested the change on Windows 10, everything works.
Maybe for some reason it worked differently on Windows 7 or I just made a mistake. Anyway we should apply your change.
