### ISSUE TITLE
Translation does not work if there is anything other than text in the text

### ISSUE THREAD

**Issue by Aquinary** [crow-translate/crow-translate#416]
**Bug description**
If the text contains extraneous entities, then the text is not translated at all

**Steps to reproduce**
- [ ] try to translate this text by highlighting the checkbox including

**Expected behavior**
Get a normal translation

**Screenshots**
![image](https://user-images.githubusercontent.com/13851343/167681854-fa611616-d2f3-4037-a89e-480a33eb83f4.png)

**Environment**
- OS: Arch Linux
- Desktop environment: awesome
- Crow Translate version: 2.9.2

**Additional context**
This problem also occurs if you try to translate text with emoji in discord

**Comment by Shatur** [comment]
I mean I can't reproduce.

**Comment by Shatur** [comment]
>  This problem also occurs if you try to translate text with emoji in discord

Maybe duplicate of #400? Because in Discord I also sometimes have empty popup window. And it happens only with popup window.

**Comment by VolkMilit** [comment]
Can't reproduce in Firefox and Palemoon, but reproducible in Chrom(e)[ium]. If you copy text in Kate and then save and open document in Okteta - you will see nothing there but spaces. So I guess Chrom(e)[ium] (and friends) using some kind of UTF-8 symbol to display checkbox? Thing is, why it doesn't copy to clipboard, but Qt still read it?

**Comment by VolkMilit** [comment]
It stop working again after c337ac96a34eedddac11d2a0e9bf9eb5d77fd1c5 and we still doesn't have a proper fix.

**Comment by VolkMilit** [comment]
Ok, finally fixed in #465.
