### ISSUE TITLE
Error: Dependency is not satisfiable: libqt5core5a

### ISSUE THREAD

**Issue by the81kid** [crow-translate/crow-translate#42]
Hello
I downloaded the correct deb file for my system (Linux Mint 18.3) but I get the above error every time. My system already has the libqt5core5 file, perhaps not the correct version, but I cannot install a more recent version (I nearly ruined my Linux installation trying to manually install the file!). The create-package.sh didn't seem to work either. It just creates 3 very small files (total about 8kb in size) outside the crow-translate-2.1.0 folder. Excuse me if I haven't given enough info or explained correctly. I'm semi-Linux literate. Thanks

https://github.com/crow-translate/crow-translate#automatic-script

**Comment by Shatur95** [comment]
Unfortunately, Linux Mint 18.3 have a very old version of Qt (5.6). So I don't think that this is possible to compile the program for your distro :(

**Comment by the81kid** [comment]
That's a shame. Linux Mint 18.3 is not very old, only one distro previous to the newest one. Does Linux 19 have the same version of Qt (5.6)? I haven't upgraded yet because I'm kinda too busy for the next 2 months.

**Comment by Shatur95** [comment]
Linux Mint 19 based on Ubuntu 18.04 that have Qt 5.9. So yes, I think upgrade will solve the problem.
Sorry for that. I use Arch Linux and when I started developing Crow Translate, I had Qt > 5.6. For future versions, I trying to save compatibility. For example, [here](https://github.com/crow-translate/crow-translate/blob/267da5a527727803babc64f9d6444834222a20c0/src/popupwindow.cpp#L126).

**Comment by the81kid** [comment]
If I can find some time this week, I'll try to upgrade. I'd like to try out your translation program, I need it for exams! If not soon I'll upgrade in September. Looking forward to trying out your work. Thanks for the reply!

**Comment by Shatur95** [comment]
You are welcome :)
