### ISSUE TITLE
"Application is already running" popup is annoying

### ISSUE THREAD

**Issue by gasinvein** [crow-translate/crow-translate#421]
**Bug description**
I launch the app from taskbar, as with most other frequently-opened apps. The problem is that when tray icon is enabled in the app settings, the app is already running in background, and then the taskbar icon is clicked, the main window shows up together with a popup that says "Application is already running". I'm no UX expert, but since the fact that the app is already running is expected and valid in this case, I believe it's pointless to show this message every time.

**Steps to reproduce**

1. Pin Crow Translate to your taskbar/dock
2. Enable "Show tray icon" in the app settings
3. Close the app windows (minimize to tray)
4. Launch the app again from taskbar/dock
5. Observe "Application is already running" message popping up

**Expected behavior**

Just the app main window is opened.

**Screenshots**

A "Application is already running" popup is opened in addition to the main window.

**Environment**

- OS: Fedora 36
- Desktop environment: GNOME 42, with Dash-To-Dock and AppIndicator extensions
- Crow Translate version: 2.9.4

**Comment by Shatur** [comment]
Makes sense, let's remove it.

**Comment by gasinvein** [comment]
Thanks!

**Comment by gasinvein** [comment]
Hmm, looks like removal of the `MainWindow::open()` call for already running application stopped not only the popup message but the main window from appearing, too.
Seems to be fixable like this (I'm not very familiar with neither Qt nor C++ in general, so my fix may be incorrect):
```patch
diff --git a/src/mainwindow.cpp b/src/mainwindow.cpp
index 013f2e7..400b8ea 100644
--- a/src/mainwindow.cpp
+++ b/src/mainwindow.cpp
@@ -26,6 +26,7 @@
 #include "qtaskbarcontrol.h"
 #include "screenwatcher.h"
 #include "selection.h"
+#include "singleapplication.h"
 #include "trayicon.h"
 #include "ocr/ocr.h"
 #include "ocr/screengrabbers/abstractscreengrabber.h"
@@ -83,6 +84,9 @@ MainWindow::MainWindow(QWidget *parent)
     // Screen orientation
     connect(m_orientationWatcher, &ScreenWatcher::screenOrientationChanged, this, &MainWindow::setOrientation);
 
+    // Open the main window if the application is already running
+    connect(qobject_cast<SingleApplication *>(QCoreApplication::instance()), &SingleApplication::instanceStarted, this, &MainWindow::open);
+
     // Selection requests
     connect(&Selection::instance(), &Selection::requestedSelectionAvailable, ui->sourceEdit, &SourceTextEdit::replaceText);
 

```

**Comment by Shatur** [comment]
Nice catch, totally forgot about it.

**Comment by Shatur** [comment]
Fixed.
