### ISSUE TITLE
Autostart not working in Flatpak

### ISSUE THREAD

**Issue by gasinvein** [crow-translate/crow-translate#428]
**Describe the problem or limitation you are having**

This was an expected limitation, so I'm reporting it as an enhancement request.
Crow Translate copies the .desktop file to `~/.config/autostart` directory in order to enable autostart on Linux. But since flatpak apps are sandboxed, they can't write to that directory on the host.

**Describe the solution you'd like**

Flatpak relies on so-called portals, a set of DBus APIs that allow sandboxed apps to securely interact with the host OS environment. Specifically for autostart, there is the [Backgound portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Background), which allows apps to request to enable autostart for them. Crow Translate could make use of this portal when running in Flatpak sandbox.

**Describe alternatives you've considered**

The only alternative would be allowing the flatpak build to access `~/.config/autostart`, but not only it would mean a trivial sandbox escape, the app would also need to take into account that it's running in flatpak, since the `Exec=` property needs to be different (the portal handles it automatically).

**Comment by Shatur** [comment]
Should be easy to fix. Here is where I writing this file:

https://github.com/crow-translate/crow-translate/blob/d48d6d44d7f4a7476193f15c805358b9b5c3f7e1/src/settings/appsettings.cpp#L193-L210

We probably should check if the application is running in Flatpak (it defines env variable, right?) and use a DBus call. [Here](https://github.com/crow-translate/crow-translate/blob/master/src/ocr/screengrabbers/waylandportalscreengrabber.cpp) is how I use it on Wayland to capture screen. Any chance you could try to send a PR?

**Comment by gasinvein** [comment]
> check if the application is running in Flatpak (it defines env variable, right?)

The canonical way is to check for the `/.flatpak-info` file presence.

> Any chance you could try to send a PR?

My C++/Qt knowledge is very limited, but I can try - at least it's pretty clear how to resolve this issue.

The method `AppSettings::setAutostartEnabled` is going to become huge if we just drop in a flatpak-specific codepath. I'm considering to create an abstraction layer over the platform-specific autostart management, similarly to how you've abstracted screen grabbers. What do you think?

**Comment by Shatur** [comment]
> My C++/Qt knowledge is very limited, but I can try - at least it's pretty clear how to resolve this issue.

It would be great! I will happy to review / answer questions.

> I'm considering to create an abstraction layer over the platform-specific autostart management, similarly to how you've abstracted screen grabbers. What do you think?

Hm... Let's see how much code with Flatpaks-specific path we will have. If not too much - I would keep it as is since 3 different cases is not too much.

**Comment by gasinvein** [comment]
> how much code with Flatpaks-specific path we will have

Something about the `WaylandPortalScreenGrabber`'s size I suppose. We need to call one method and wait for one signal. Plus, since we can't know from the portal if autostart is enabled, we'll need to store the autostart setting state in the config file. And since the user can decline the autostart request, we'll need to parse the reply to get the value to store in config.

> 3 different cases is not too much.

Well, you (or someone else) will consider adding OS X or other platform in the future.

**Comment by Shatur** [comment]
Okay, let's abstract it :)
