### ISSUE TITLE
Add CLI commands that open main and popup windows for making shortcuts available on wayland

### ISSUE THREAD

**Issue by hexauniverse** [crow-translate/crow-translate#43]
That's simple solution I couldn’t guess for a long time though..

For example, I will be able to add a keyboard shortcut on gnome settings, something like that:

![](https://i.imgur.com/9b0jxWM.png)

**Comment by Shatur95** [comment]
You can just execute `crow` to open the program main window.

**Comment by hexauniverse** [comment]
@Shatur95, I can not.
`crow` does not intercept a current PRIMARY selection and opens "The application is already running" window

**Comment by Shatur95** [comment]
Sorry, I misunderstood you. In the application itself, hotkeys do not work on Wayland?

**Comment by hexauniverse** [comment]
Yeah, hotkeys (on any qt applications) don't work if focused window works on wayland

**Comment by hexauniverse** [comment]
I found the same issue: https://github.com/albertlauncher/albert/issues/309

**Comment by Shatur95** [comment]
Unfortunately, this is because I use the [QHotkey](https://github.com/Skycoder42/QHotkey) library, which does not work for Wayland :(
I do not like the proposed solution. I would like to be able to somehow register hotkeys for Wayland...

**Comment by hexauniverse** [comment]
> I would like to be able to somehow register hotkeys for Wayland...
It seems impossible now: https://github.com/Skycoder42/QHotkey/issues/14#issuecomment-354117427

**Comment by Shatur95** [comment]
I think that Gnome and KDE provide an API for this. I will try to figure out how to register hotkeys for them.

**Comment by Shatur95** [comment]
Hm... What if I provide a DBus API instead of CLI? This will separate the work with the CLI and GUI and allow to manage the program from third-party tools.
Also you will able to bind dbus commands as shortcuts too.

**Comment by hexauniverse** [comment]
@Shatur95, no problem, do as you see fit

**Comment by Shatur95** [comment]
Is there a way to somehow register available shortcuts for Gnome?
For example, to register the shortcuts in KDE i just need to add a few lines to .desktop file.

**Comment by hexauniverse** [comment]
@Shatur95, there is a difficult [way](https://askubuntu.com/questions/597395/how-to-set-custom-keyboard-shortcuts-from-terminal#597414) through gsettings. I think it's better to wait for a better implementation and now leave it manual

**Comment by Shatur95** [comment]
Done, check [the documentation](https://github.com/crow-translate/crow-translate#d-bus-api). But I'm no sure that Wayland supports global selection...

**Comment by VolkMilit** [comment]
@Shatur95, there is an different mechanism in Wayland, see [this](https://github.com/bugaevc/wl-clipboard).

[Speaking of fragmentation...](https://github.com/bugaevc/wl-clipboard/blob/master/src/protocol/gtk-primary-selection.xml#L27)

**Comment by hexauniverse** [comment]
@Shatur95 
> But I'm no sure that Wayland supports global selection...

I've checked it, all works fine

**Comment by Shatur95** [comment]
> I've checked it, all works fine
Good news, thank you

**Comment by Shatur95** [comment]
I made some changes to the D-Bus methods names in commit 2ea3f09.
