### ISSUE TITLE
Make XDG dialogs modal

### ISSUE THREAD

**Issue by Shatur** [crow-translate/crow-translate#430]
**Describe the problem or limitation you are having**

We currently do not set `parent_window` in XDG dialogs:

https://github.com/crow-translate/crow-translate/blob/0d52fa0769ce84cdb2a0b0e7ee21f9f78ae3dd05/src/settings/autostartmanager/portalautostartmanager.cpp#L50-L52
https://github.com/crow-translate/crow-translate/blob/0d52fa0769ce84cdb2a0b0e7ee21f9f78ae3dd05/src/ocr/screengrabbers/waylandportalscreengrabber.cpp#L52-L54

**Describe the solution you'd like**
We should detect parent window and pass it over D-Bus.

**Comment by Shatur** [comment]
@gasinvein do you want me to draft a new release with your fix you planning to take a look at this?

**Comment by gasinvein** [comment]
I've looked into it and got stuck with casts in C++. Specifically, this works (no crashes):
```c++
void PortalAutostartManager::setAutostartEnabled(bool enabled)
{
    auto *parent_window = static_cast<QWindow *>(parent());
```
but `clang-tidy` is unhappy and suggests to use `dynamic_cast` (or `qobject_cast`). But if I do this
```c++
void PortalAutostartManager::setAutostartEnabled(bool enabled)
{
    auto *parent_window = qobject_cast<QWindow *>(parent());
```
`clang-tidy` becomes happy, but app crashes on applying settings.

**Comment by Shatur** [comment]
> but clang-tidy is unhappy and suggests to use dynamic_cast (or qobject_cast) instead. If I do this

Right, you need to use a cast with check.

> clang-tidy becomes happy, but app crashes on applying settings.

This means that your parent isn't a `QWindow`. That's true, because `SettingsDialog` inherits from `QDialog` (which inherits from `QWidget`). How about this:

```cpp
auto *parentWindow = qobject_cast<QWidget *>(parent()).window();
```

**Comment by gasinvein** [comment]
> This means that your parent isn't a `QWindow`. That's true, because `SettingsDialog` inherits from `QDialog` (which inherits from `QWidget`).

Hmm, indeed. But then why (and how) `winId()` works on `SettingsDialog` casted to `QWindow`?

> How about this:
> 
> ```c++
> auto *parentWindow = qobject_cast<QWidget *>(parent()).window();
> ```

And then in cast it again to `QWindow` (or how else do we get to use `winId()`)?

**Comment by Shatur** [comment]
> Hmm, indeed. But then why (and how) winId() works on SettingsDialog casted to QWindow?

You casted parent to completely unrelated class, so it just returns garbage.

> And then in cast it again to QWindow (or how else do we get to use winId())? QWidget->window() returns another QWidget.

Oh, sorry, I mean `windowHandle()`, not `window()` to get `QWindow` to get `Wid`.
There is also [such method](https://doc.qt.io/qt-5/qwidget.html#winId) on `QWidget`, so you probably can call it directly.

**Comment by gasinvein** [comment]
Yep, this works, thanks, I'll open a PR.
