### ISSUE TITLE
PPA List Error

### ISSUE THREAD

**Issue by localcreator** [crow-translate/crow-translate#437]
'Репозиторий «https://ppa.launchpadcontent.net/jonmagon/crow-translate/ubuntu jammy Release» не содержит файла Release.' Such an error when adding a repository

**Comment by Shatur** [comment]
Ping @JonMagon, probably a package for 20.04 is missing.

**Comment by localcreator** [comment]
22.04 planned to be added?

**Comment by JonMagon** [comment]
Hi. This is definitely not a bug. I haven't updated the package for a while. I'm gonna pack a new release for all supported Ubuntu versions in the next week or two.

**Comment by Shatur** [comment]
It would be great. Note, that we switched to submodules, so you need to download `crow-translate-<version>-source.tar.gz` from the releases page (with all submodules included) instead of the default one provided by github.

**Comment by JonMagon** [comment]
The package has been updated for focal, impish and jammy. arm64 and armhf are still in the build queue, amd64 is already available.

**Comment by Shatur** [comment]
Thank you a lot!
