### ISSUE TITLE
Tray icon problem

### ISSUE THREAD

**Issue by GrimPixel** [crow-translate/crow-translate#439]
**Bug description**

The Crow Translate icon is missing.

**Steps to reproduce**

Just open it.

**Expected behavior**

Show the Crow Translate icon.

**Screenshots**

![icon](https://user-images.githubusercontent.com/39795763/168669917-e30bbe3a-75b9-4f6f-9527-e511ac23b763.png)

**Environment**

- OS:  Arch Linux
- Desktop environment:  MATE
- Crow Translate version:  2.9.6

**Additional context**

**Comment by Shatur** [comment]
Could you try installing it from AUR?

**Comment by GrimPixel** [comment]
I installed from AUR.

**Comment by Shatur** [comment]
Sorry, I meant `crow-translate-git`.

**Comment by GrimPixel** [comment]
crow-translate-git works well.

**Comment by Shatur** [comment]
Then the issue is already fixed, just wait for a new release.
