### ISSUE TITLE
Are you open to suggestions about the GUI and features?

### ISSUE THREAD

**Issue by neoOpus** [crow-translate/crow-translate#448]
Hi,

I love this Q-Translate alternative and I am starting to get used to it... I think this can be much better than Q-Translate which seems more like abandonware at this stage...

I would like to compile some ideas about how I think this can borrow some of the great features and what could increase productivity and user-friendliness, but I don't know if you guys are open to suggestions...

**Comment by Shatur** [comment]
Of course, feel free to open feature requests. But first, use the search, perhaps there is already a similar one.

I currently busy at the moment, but I always here and will be happy to review any pull request.
