### ISSUE TITLE
"Play text" is not working for google on ubuntu

### ISSUE THREAD

**Issue by zeroohub** [crow-translate/crow-translate#45]
I am using ubuntu 18.04 with latest stable version installed.
Translation works fine, but when i click `play source text`, it does not work.

**Comment by Shatur95** [comment]
It seems that some required package is missing. Could you show the output of `dpkg -l | grep gstreamdpkg -l | grep gstream`?

**Comment by zeroohub** [comment]
![image](https://user-images.githubusercontent.com/3849613/62841259-7eee1200-bcd8-11e9-8ada-b91938077eeb.png)
Here is the output

**Comment by Shatur95** [comment]
Could you try to install `gstreamer1.0-fluendo-mp3`, show me the installation output and try to speak text again?

**Comment by zeroohub** [comment]
Oh, it works now. It's strange that i have this lib installed before, it does not have voice, but today it works.

**Comment by Shatur95** [comment]
Indeed, I did not notice this in your output :)
Weird
