### ISSUE TITLE
GUI issue - Mismatch about button text and explanation

### ISSUE THREAD

**Issue by bovirus** [crow-translate/crow-translate#457]
@Shatur 

**Bug description**
GUI issues.

**Steps to reproduce**

**Expected behavior**

Should be a newline first and after file name.

The explanation about "Termina" and relative button "Interrompi" didn't match.
Change string "Termina  in "Interrompi". 

**Screenshots**

Original

![image](https://user-images.githubusercontent.com/1262554/183364253-068e5fcb-0f74-494c-90c1-89d8fb8a3728.png)

Expcxted

![image](https://user-images.githubusercontent.com/1262554/183364866-90e0fcbc-bc03-4c3b-8b3c-5efca8de6b96.png)

**Environment**

Windows 11

**Additional context**

**Comment by Shatur** [comment]
Hi! The installator is built using NSIS. I have no control over its translation. You can report it to the NSIS directly.

**Comment by bovirus** [comment]
@Shatur

Which version of NSIS are you using?

I'm the italian translator for NSIS language file and I can made the change easily.

**Comment by Shatur** [comment]
Releases generated on CI using [windows-2019](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) machine which have `NSIS v3.08` (latest).

**Comment by bovirus** [comment]
@Shatur 

New language for NSIS 3.08.

I will update soon also for new reelase.

[R05.zip](https://github.com/crow-translate/crow-translate/files/9280290/R05.zip)

Please update the file in your installation.

**Comment by Shatur** [comment]
I don't have access to it I use what NSIS have. You need to upstream it.

**Comment by bovirus** [comment]
@Shatur.

Sorry but I didn't understand.
Download the zio file, extract the contents and use to overwrite you current NSIS 3.08 language file.

**Comment by Shatur** [comment]
I don't build it manually. It's done on CI.
And I don't want to maintain translation for another program. Just submit it upstream and the next NSIS version will have the correct translation.

**Comment by bovirus** [comment]
Yes.
But I can see the changes about italian in NSIS only in new version (ex., 3.09):
Until then you will have now the option to replace the current installation with new version.
When NSIS will release 3.09 it will include also the changes.

**Comment by Shatur** [comment]
> But I can see the changes about italian in NSIS only in new version (ex., 3.09):

Unfortunately, yes. But it's not a big deal, right? CI will have 3.09 once it will be released.
It is possible to automate copying this file on CI, but IMHO it just not worth it, better wait for the upstream fix.
