### ISSUE TITLE
Global shortcuts are disabled on Wayland

### ISSUE THREAD

**Issue by xAdamQ** [crow-translate/crow-translate#460]
I switched from x11 to Wayland then the global shortcuts became greyed out and the default shortcuts doesn't work.

- OS: Arch Linux Manjaro
- Desktop environment: KDE Plasma
- Crow Translate version: 2.9.10 

![image](https://user-images.githubusercontent.com/29926942/183380870-8808c803-eb93-405b-9a6e-e72f8a04b249.png)

**Comment by Shatur** [comment]
It's expected because global shortcuts are unsupported on Wayland.
In Wayland global shortcuts became IDE-specific. Looks like you use KDE? You can set Crow global shortcuts in your system settings (just add `Crow Translate` application and configure its shortcuts).
But be aware that there is some unresolved issues with Wayland like https://github.com/crow-translate/crow-translate/issues/324.

**Comment by xAdamQ** [comment]
Thank you very much.

**Comment by GrgMdmn** [comment]
Hello ! I am using KDE (openSUSE), and have added "Crow Translate" in the "shortcut section" : 
![image](https://github.com/crow-translate/crow-translate/assets/68954220/c5d1ab80-1a68-4294-904c-6d86c6c52021)

What I do not understand is that the shortcut section of the "Crow Translate" app is still in grey, and the shortcut are still not working, even if I reboot my system...
![image](https://github.com/crow-translate/crow-translate/assets/68954220/998772c2-3d71-42ac-a93e-776b47a0c9ed)

**Comment by Shatur** [comment]
You probably missing `qdbus` in your system. These shortcuts in KDE settings basically execute these commands:https://github.com/crow-translate/crow-translate/blob/a3443aef9e5662a53d824a048a82debd36cc2391/data/io.crow_translate.CrowTranslate.desktop#L27

**Comment by GrgMdmn** [comment]
I am trying to install qdbus using this command `sudo zypper install libqt5-qdbus` but system says me it is already installed

**Comment by Shatur** [comment]
Try to execute `qdbus io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow translateSelection` from the desktop file.

**Comment by GrgMdmn** [comment]
Where to find this desktop file...? ^^'

**Comment by Shatur** [comment]
Depends on your distro. In my case it located in `/usr/share/applications/io.crow_translate.CrowTranslate.desktop`.

**Comment by GrgMdmn** [comment]
`qdbus` does not exist... "command not found"... However, I have `qdbus-qt5` .
But if I try to run the command with it, it fails: 
```
qdbus-qt5 io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow translateSelection
Service 'io.crow_translate.CrowTranslate' does not exist.
```

**Comment by Shatur** [comment]
> qdbus does not exist... "command not found"... However, I have qdbus-qt5 .

Looks like command is different on your distro.

> Service 'io.crow_translate.CrowTranslate' does not exist.

The program should be running.

**Comment by GrgMdmn** [comment]
Too bad... So I am not able to run the shortcuts :(

**Comment by Shatur** [comment]
You just need to open the program first and the global shortcuts will work. But you need to change `qdbus` to `qdbus-qt5` in your desktop file.

**Comment by GrgMdmn** [comment]
I have replaced all the `qdbus` with `qdbus-qt5` inside of my `/usr/share/applications/io.crow_translate.CrowTranslate.desktop` file, but the shortcuts are still not working.

Here is what I have when  I execute `io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow`
```
method void io.crow_translate.CrowTranslate.MainWindow.cancelOperation()
method void io.crow_translate.CrowTranslate.MainWindow.clearText()
method void io.crow_translate.CrowTranslate.MainWindow.copyAllTranslationInfo()
method void io.crow_translate.CrowTranslate.MainWindow.copySourceText()
method void io.crow_translate.CrowTranslate.MainWindow.copyTranslatedSelection()
method void io.crow_translate.CrowTranslate.MainWindow.copyTranslation()
method void io.crow_translate.CrowTranslate.MainWindow.delayedRecognizeScreenArea()
method void io.crow_translate.CrowTranslate.MainWindow.delayedTranslateScreenArea()
method void io.crow_translate.CrowTranslate.MainWindow.open()
method void io.crow_translate.CrowTranslate.MainWindow.openSettings()
method void io.crow_translate.CrowTranslate.MainWindow.playPauseSpeaking()
method void io.crow_translate.CrowTranslate.MainWindow.quit()
method void io.crow_translate.CrowTranslate.MainWindow.recognizeScreenArea()
method void io.crow_translate.CrowTranslate.MainWindow.setAutoTranslateEnabled(bool enabled)
method void io.crow_translate.CrowTranslate.MainWindow.speakSelection()
method void io.crow_translate.CrowTranslate.MainWindow.speakTranslatedSelection()
method void io.crow_translate.CrowTranslate.MainWindow.stopSpeaking()
method void io.crow_translate.CrowTranslate.MainWindow.swapLanguages()
method void io.crow_translate.CrowTranslate.MainWindow.translateScreenArea()
method void io.crow_translate.CrowTranslate.MainWindow.translateSelection()
signal void org.freedesktop.DBus.Properties.PropertiesChanged(QString interface_name, QVariantMap changed_properties, QStringList invalidated_properties)
method QDBusVariant org.freedesktop.DBus.Properties.Get(QString interface_name, QString property_name)
method QVariantMap org.freedesktop.DBus.Properties.GetAll(QString interface_name)
method void org.freedesktop.DBus.Properties.Set(QString interface_name, QString property_name, QDBusVariant value)
method QString org.freedesktop.DBus.Introspectable.Introspect()
method QString org.freedesktop.DBus.Peer.GetMachineId()
method void org.freedesktop.DBus.Peer.Ping()
```

**Comment by Shatur** [comment]
> Here is what I have when I execute io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow

You missing the last argument. It should be the name of the listed function. Try to add `openSettings`.

**Comment by GrgMdmn** [comment]
Oh sorry, I forgot the last argument. When I do this command ligne with `openSettings`, the setting window of the app is opening. In "shortcuts", still have the "Global" section and all shortcuts it contains in grey.

**Comment by Shatur** [comment]
> When I do this command ligne with openSettings, the setting window of the app is opening. In "shortcuts"

Then it's working.

> still have the "Global" section and all shortcuts it contains in grey.

This is expected. Wayland doesn't support global shortcuts provided by apps.

**Comment by GrgMdmn** [comment]
Oh ok, I understand, so I will never be able to use the global shortcuts :(

**Comment by GrgMdmn** [comment]
According to this article, KDE Wayland is supporting the global shortcuts since the start of the year : 
https://www.phoronix.com/news/KDE-Plasma-5.27-Released

The version I have is 5.27.8 so it should work

**Comment by Shatur** [comment]
> According to this article, KDE Plasma + Wayland is supporting the global shortcuts since the start of the year :

You don't understand me. Global shortcuts are supported inside the KDE settings. So you need to setup bindings inside them, not inside the app. Apps can't register global shortcuts themselves under Wayland, it's not supported by the protocol.

**Comment by GrgMdmn** [comment]
Oh I did not understand, indeed, and I am sorry for it. The problem is I have added Crow Translate shortcuts  in my kde manager ("Raccourcis" = "Shortcuts" in french)
![image](https://github.com/crow-translate/crow-translate/assets/68954220/e76ee3e7-7a36-4e25-a3b8-375e929f0d83)
