### ISSUE TITLE
Update via winget

### ISSUE THREAD

**Issue by Dhowti** [crow-translate/crow-translate#467]
I prefer to update via winget. But the installer does not understand that the application is already running and does not update the core files. This does not show any errors.

**Comment by Shatur** [comment]
Hi! I can't fix this, you need to close the application before the update.

**Comment by Dhowti** [comment]
My update is automated, I can't. But ok, I will use the built-in update.

**Comment by Shatur** [comment]
So you automatically update your applications? But what if an application is already running?

**Comment by Dhowti** [comment]
> So you automatically update your applications? But what if an application is already running?

I add them to Winget-AutoUpdate script exceptions and update them manually.
