### ISSUE TITLE
Translate selection shorctut does not work

### ISSUE THREAD

**Issue by geeksesi** [crow-translate/crow-translate#48]
Hi,
os : ubuntu 19.4 | Gnome `GNOME Shell 3.32.2`

selected text doesnot work... has any flag to get log of the program ?
i don't know just what happend... ( shortcut does execute ? read selection text has problem... ? or something else )

i can use cli and it's work ( also open main windows and translate on them does work )

please add a flag to debug.
also can add some place to cach all of voice ?

**Comment by Shatur95** [comment]
Hi, are you using Wayland?

Unfortunately, voice caching is not planned to be added in the near future :(

**Comment by geeksesi** [comment]
no i use Xorg. 
and also in cli option have a flag with -i ( for get text from selection ) also it doesn't work.

**Comment by Shatur95** [comment]
`-i` does not get text from selection, it gets text from `stdin`.
Maybe shortcut for selection is used by another app? Have you tried changing this?

**Comment by geeksesi** [comment]
yes, tested the another shortcut.
but just open main windows shortcut will work. ( and also i don't know what happend on other. )
if make anything to show debug logs we can fix it.

**Comment by Shatur95** [comment]
Could you show me the output of `crow` after start?
Have you tried changing the key combination to translate the selected text?

**Comment by geeksesi** [comment]
hasn't special output just a warning about GTK ...
```
 crow                                                                                                            Mon 02 Sep 2019 03:34:51 AM +0430

(crow:4133): Gtk-WARNING **: 03:34:54.815: Theme parsing error: gtk.css:25:8: 'height' is not a valid property name

(crow:4133): Gtk-WARNING **: 03:34:54.816: Theme parsing error: gtk.css:27:12: 'max-height' is not a valid property name

```

another problem i found now.
GUI can't connect to google | yandex | bing Api..
![image](https://user-images.githubusercontent.com/28778964/64083316-3d7ae080-cd33-11e9-9e89-ff2c01b081f3.png)

but CLI can.
![image](https://user-images.githubusercontent.com/28778964/64083317-48ce0c00-cd33-11e9-93fd-094f23fb94c7.png)

first when i installed gui translate also work. but now... idk.

**Comment by Shatur95** [comment]
Weird... Can't reproduce this issue.
A new version has been released, I will try to provide Ubuntu packages as soon as possible, need to check on the latest releae.

**Comment by Shatur95** [comment]
Ubuntu packages added, try the latest version

**Comment by geeksesi** [comment]
again will appear `Host translate.yandex.com not found`
my internet conection is ok. and also i can use Cli.

**Comment by Shatur95** [comment]
Could you check proxy settings in crow?

**Comment by geeksesi** [comment]
it's done. 
thank you. 
idk why is in empty socks5.

**Comment by Shatur95** [comment]
What about "Translate selection" shortcut in the latest release?

**Comment by geeksesi** [comment]
also it's ok.

**Comment by Shatur95** [comment]
Cool :)

**Comment by kirillt** [comment]
This is the log right after launching `crow`:
```
QSocketNotifier: Can only be used with threads started with QThread
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
QHotkey: Unable to map shortcut to native keys. Key: Qt::Key_E Modifiers: QFlags<Qt::KeyboardModifier>(ControlModifier|AltModifier)
QHotkey: Unable to map shortcut to native keys. Key: Qt::Key_S Modifiers: QFlags<Qt::KeyboardModifier>(ControlModifier|AltModifier)
QHotkey: Unable to map shortcut to native keys. Key: Qt::Key_G Modifiers: QFlags<Qt::KeyboardModifier>(ControlModifier|AltModifier)
QHotkey: Unable to map shortcut to native keys. Key: Qt::Key_F Modifiers: QFlags<Qt::KeyboardModifier>(ControlModifier|AltModifier)
QHotkey: Unable to map shortcut to native keys. Key: Qt::Key_C Modifiers: QFlags<Qt::KeyboardModifier>(ControlModifier|AltModifier)
```
Fedora 31
Gnome 3.34.4
Wayland
```
[kirill@fedora ~]$ uname -a
Linux fedora 5.5.8-200.fc31.x86_64 #1 SMP Thu Mar 5 21:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[kirill@fedora ~]$ loginctl show-session 2 -p Type
Type=wayland
```

**Comment by kirillt** [comment]
Switching to Xorg helps though.

**Comment by Shatur95** [comment]
You can't use in-app global shortcuts because Wayland do not allow to register global shortcuts. You need to map shortcuts in your IDE directly via [D-Bus commands](https://github.com/crow-translate/crow-translate#d-bus-api).

**Comment by kirillt** [comment]
Got it, thanks. For me it is OK to just switch to Xorg actually, at lrast on this machine. But that's useful information.

**Comment by Beppe6464** [comment]
Hi, I have a similar issue on Fedora 35 (Kernel 5.15).
If I right click on the Crow icon I get a "Translate Selected Text" menù option but if I press it the Crow window open but there is not the selected text inside.

Can anybody help me ?

Thank you.
Ciao.
gp

**Comment by Shatur** [comment]
>  If I right click on the Crow icon I get a "Translate Selected Text" menù option but if I press it the Crow window open but there is not the selected text inside.

Unfortunately, you can't translate selection on Wayland. See #324.

**Comment by Beppe6464** [comment]
Understood.
Thank you.
Ciao.
Gp



Il dom 6 feb 2022, 18:37 Hennadii Chernyshchyk ***@***.***>
ha scritto:
