### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by ryanpan** [crow-translate/crow-translate#481]
Please add always on top feature

**Comment by Shatur** [comment]
I think that this feature should be provided by your window manager. For example, in KDE I have it out of the box.

**Comment by ryanpan** [comment]
Some apps also provide this feature, like CopyTranslator, and QTranslate.

https://github.com/CopyTranslator/CopyTranslator

**Comment by Shatur** [comment]
I think it would be better to go with something like #500 instead. It should fit your use case too.

**Comment by nightkall** [comment]
The always on top of my suggestion was for the capture area window also, which you can move and resize, and everything inside is captured and translated. Another solution would be to automatically translate the previously selected area of the screen until a new one is selected.
