### ISSUE TITLE
Desktop file has multiple Main Categories

### ISSUE THREAD

**Issue by EdstromP** [crow-translate/crow-translate#482]
The desktop file, io.crow_translate.CrowTranslate.desktop, has two Main Categories: Office and Network.

According to the [latest specification](https://specifications.freedesktop.org/menu-spec/latest/apa.html):

> If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu.

My suggestion is to remove Network.

https://github.com/crow-translate/crow-translate/blob/master/data/io.crow_translate.CrowTranslate.desktop#L18

**Comment by Shatur** [comment]
But it uses network to provide translations.
It also have Qt category as most Qt applications.

**Comment by EdstromP** [comment]
Hi Shatur,

Yes, it uses network but is it really a network application? That is, should it be located in both a 'Network' and 'Office' menu?

Qt is not defined as a Main category, but an Additional category. [Here](https://specifications.freedesktop.org/menu-spec/latest/apas02.html) is the full list of Additional categories. (Dictionary would be another nice fit).

The reason for me caring about this at all, is that I'm building a Slackware package (SlackBuild) for crow-translate and want to distribute it through the SBo repo. A requirement for that is the passing of a lint script, that among other things, tests the presence of multiple Main categories.

**Comment by Shatur** [comment]
Okay, makes sense, feel free to submit a PR, I will accept it!

**Comment by EdstromP** [comment]
Great!
Here's the PR: #483

**Comment by Shatur** [comment]
Okay, should I draft a minor new release after this change?

**Comment by EdstromP** [comment]
That would be really good, because then I could build a new SlackBuild package based on the new release.

**Comment by Shatur** [comment]
Okay, I will do it today after work.

**Comment by Shatur** [comment]
Closed by 788578723e6ebfd34b013b53a922ce722e39a1d5.
