### ISSUE TITLE
Dialog boxes block hotkeys

### ISSUE THREAD

**Issue by perguto** [crow-translate/crow-translate#488]
**Bug description**

When an error/notification like "Playback Text is Empty" appears, you have to manually close the window to make the shortcuts work again. This is a bit annoying, especially, when you only use the TTS or popup translation hotkeys, where the dialog box doesn't show up.

**Steps to reproduce**
See error

**Expected behavior**
It would be nice if an invocation of a global hotkey would automatically close the popup and execute the command as normal.

**Environment**

- OS: Windows
- Desktop environment: 
- Crow Translate version: 2.10.1

**Comment by Shatur** [comment]
I think you can press enter to close the popup.
