### ISSUE TITLE
I want to translate to Chinese in the CLI, but I don't know the abbreviation

### ISSUE THREAD

**Issue by BuddhiLW** [crow-translate/crow-translate#490]
## Issue
I'm using the following:
```sh
crow -p -s pt -t zh "Olá!"
```

Which means translate "Olá!" from Portuguese (pt) to Chinese (zh).

But, I get `"Error: Selected translation language  is not supported for Google"`. I have tried zh, ch, cn, etc. And I can't figure out what is the correct acronym used to Chinese built-in in the software.

## I wish
I would like to pass a flag to `crow`, like `crow --list` and it returns a the language list of available languages and it's acronymn.

```sh
crow -ls
```

Example:
pt - Portuguese
en - English
zh/ch/etc.. - Chinese

## Alternatives
- Fuzzy match the accronym given as input to the list of possible ones.
- Let one give the english-name of the language and match it, `crow --out-lang Chinese`.

**Comment by Shatur** [comment]
Hi! We have `crow --codes`.

**Comment by BuddhiLW** [comment]
Oh, perfect! Thank you; and a great project the team built.
