### ISSUE TITLE
Not able to turn on global shortcuts

### ISSUE THREAD

**Issue by charlesneimog** [crow-translate/crow-translate#494]
**Bug description**
I am on Fedora 37 and I can not turn on the global shortcuts.

**Steps to reproduce**
Try to enable global shortcuts on Fedora 37.

**Screenshots**
![image](https://user-images.githubusercontent.com/31707161/206858561-382c0bb7-f41b-4a5d-bcf2-530aa07913cf.png)

**Environment**

- OS: Fedora 37
- Desktop environment: Gnome
- Crow Translate version: 2.10.0 (not possible to install 2.10.1 because of tesseract).

Sorry if this is because some specific configuration!

**Comment by Shatur** [comment]
Hi! Global shortcuts don't work on Wayland because in this protocol the implementation depends on DE (GNOME, KDE, etc.).
What you can do is to map global shortcuts yourself [using D-Bus](https://github.com/crow-translate/crow-translate#d-bus-api).

**Comment by charlesneimog** [comment]
Thanks!
