### ISSUE TITLE
When I run an application in Wayland, the image of the second monitor is copied to the first monitor.

### ISSUE THREAD

**Issue by imLEGR** [crow-translate/crow-translate#495]
**Bug description**
When I run OCR (in Wayland), the image from the second monitor flips to the first one.

**Steps to reproduce**
Running OCR (in Wayland).

**Expected behavior**
Everything should work fine

**Video**

https://user-images.githubusercontent.com/53097257/207509497-88958dd6-df26-4b63-abe5-eccf74694bde.mp4

**Environment**

Operating System: Arch Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.0.12-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × Intel® Core™ i7-10700K CPU @ 3.80GHz
Memory: 62.7 ГиБ of RAM
Graphics Processor: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C80

crow-translate 2.10.1-1

**Comment by Shatur** [comment]
> Yes, Spectacle works. With the same problem.

Could you report it to them? Because we basically use the same code for capturing :D

**Comment by imLEGR** [comment]
> > Yes, Spectacle works. With the same problem.
> 
> Could you report it to them? Because we basically use the same code for capturing :D

I'd love to, but Spectacle works just fine. Maybe you could take a look at the advice I was given for Flameshot and it could be applied here?

Help please, I really need the recognition feature :)

**Comment by Shatur** [comment]
> I'd love to, but Spectacle works just fine.

But you said `With the same problem.`. So it does have this issue?

> I don't know how to do it here. The problem probably occurs if there is more than one monitor.

It's a suggestion for settings in KDE. But I don't use Wayland currently, so can't help much.

**Comment by Shatur** [comment]
So just to be clear, Spectacle don't have this issue, it works correctly on Wayland, right?

**Comment by imLEGR** [comment]
> So just to be clear, Spectacle don't have this issue, it works correctly on Wayland, right?

That's right, Spectacle works fine in all modes. Screenshot of the highlighted area, the window, and the entire screen. But in 
Crow Translate does what I showed in the video.

The image from the second monitor flies to the first one.

**Comment by Shatur** [comment]
Thanks! It's a good sign, we probably should try to port the new code from it in order to have a proper capturing.
Unfortunately, I currently busy :(
But PR is welcome, I will review it ASAP.

In the meanwhile what I can recommend is to switch to Xorg session in order to have a proper text recognition as a workaround.

**Comment by imLEGR** [comment]
@Shatur Thank you. I hope you or your colleagues (I do not know how many people develop this wonderful program) will make changes and I will continue to use your program :)

**Comment by imLEGR** [comment]
> Thanks! It's a good sign, we probably should try to port the new code from it in order to have a proper capturing. Unfortunately, I currently busy :( But PR is welcome, I will review it ASAP.
> 
> In the meanwhile what I can recommend is to switch to Xorg session in order to have a proper text recognition as a workaround.

Hello :)
Please fix this bug, if I could I would have done it myself a long time ago, but I'm not that good at programming.

**Comment by Shatur** [comment]
Sorry, can't help you much currently.
What is needed to do is to replace [SnippingArea](https://github.com/crow-translate/crow-translate/blob/master/src/ocr/snippingarea.h) with the [new one from Spectacle](https://invent.kde.org/graphics/spectacle/-/blob/master/src/Gui/CaptureWindow.h). Or any a library that provides a window area.

**Comment by imLEGR** [comment]
> Sorry, can't help you much currently. What is needed to do is to replace [SnippingArea](https://github.com/crow-translate/crow-translate/blob/master/src/ocr/snippingarea.h) with the [new one from Spectacle](https://invent.kde.org/graphics/spectacle/-/blob/master/src/Gui/CaptureWindow.h). Or any a library that provides a window area.

Can you please tell me how to do this? :)

**Comment by Shatur** [comment]
> Can you please tell me how to do this? :)

No sure what can I tell, I posted it mostly for potential contributors. We need to port this class.

>  And another question: will you no longer be involved in this project? For example, will it stop working and require updating? Is the project abandoned?

We had a release 3 days ago. In our free time we prioritize translation engines support. Also we welcome contributions.
