### ISSUE TITLE
Windows: Google region is not saved to .ini file

### ISSUE THREAD

**Issue by gitgrub** [crow-translate/crow-translate#496]
In settings/speech synthesis/google region always reverts to Bengali.

Test:
Change region to "German", press OK in the settings dialog, open it again, region is "Bengali".
Selecting "German" is not saved to the settings.ini file.

Using version 2.10.1 in portable mode on windows 10.

**Comment by Shatur** [comment]
It's not what you think. In this menu you first select a language that you want to configure and then you select a region for it.
It's fine that it reverts back "Bengali" because it's not a setting.

**Comment by gitgrub** [comment]
Oh I see, thank you.
