### ISSUE TITLE
Record the selection of auto-translation, not canceled automatically when restarting

### ISSUE THREAD

**Issue by shaonianruntu** [crow-translate/crow-translate#501]
Every time the computer is restarted, the auto-translation selection box will be initialized and canceled.

Can an option be added to record this selection? Make this option is still selected after computer  restarting.

![image](https://user-images.githubusercontent.com/16336682/208843315-6128ceb2-4efe-443b-b601-1e0c561f4294.png)

For detail, 
My computer system is Windows 10 21H2 (19044.2251)
My crow translate software version is: 
![image](https://user-images.githubusercontent.com/16336682/208843746-012dfc1c-d66b-4586-8c67-d891ab9e9ffe.png)

**Comment by Shatur** [comment]
The option is saved. You probably killed the application. Try to check this option and exit the app normally.

**Comment by shaonianruntu** [comment]
> The option is saved. You probably killed the application. Try to check this option and exit the app normally.

Is is related to my software version is the Green (Unzip) version.

**Comment by Shatur** [comment]
Should work fine in both versions. I just checked it, everything is saved.
Provide steps to reproduce and I will reopen the issue.

**Comment by shaonianruntu** [comment]
> Should work fine in both versions. I just checked it, everything is saved. Provide steps to reproduce and I will reopen the issue.

Thank you very much. But I don't know how to reproduce this problem, because I have been having this problem since I installed it.

I set the software to start automatically at boot, and the software will always stay in the background. 
When I get off work, I always click the shutdown button of the system to turn off the computer directly (I will not manually exit the software from the background). 
![image](https://user-images.githubusercontent.com/16336682/208855174-1abcf5fd-5e00-49f7-8198-58379dee1ee1.png)
When the computer is turned on the next day, this option of the software is automatically canceled.

For details of the software settings are as follows:
![image](https://user-images.githubusercontent.com/16336682/208855820-04df0fcd-aaa1-4d6d-b2bd-86b0006d70d8.png)
![image](https://user-images.githubusercontent.com/16336682/208855954-f401024d-4e60-421c-bde7-8547cd2fe267.png)
![image](https://user-images.githubusercontent.com/16336682/208856004-e3e36e88-5f32-4dea-af62-7be25331a1fa.png)
![image](https://user-images.githubusercontent.com/16336682/208856045-08574d6b-1c4f-4f05-82d1-4e1fdb996b7d.png)
![image](https://user-images.githubusercontent.com/16336682/208856070-ccc823c4-f4fc-427b-a96b-363267d2923c.png)
![image](https://user-images.githubusercontent.com/16336682/208856081-e363d93f-cabd-4b7c-84ef-5c6757a47ba1.png)
![image](https://user-images.githubusercontent.com/16336682/208856101-9533a3ed-21a4-4b69-bb45-1c2b7a3a7e9a.png)
![image](https://user-images.githubusercontent.com/16336682/208856120-0c02c437-7a79-476b-b056-36faa4429693.png)
![image](https://user-images.githubusercontent.com/16336682/208856138-92f181bf-0ef8-404c-b035-86f1fecd3383.png)

**Comment by Shatur** [comment]
> I set the software to start automatically at boot, and the software will always stay in the background.
When I get off work, I always click the shutdown button of the system to turn off the computer directly (I will not manually exit the software from the background before turn off).

That's exactly what I thought. We save the settings of the main window (for example, selected languages, auto-translation, etc.) upon exit. But if the application is killed, the settings will not be saved. It looks like Windows is killing the application on shutdown and that is causing the issue.

I already had a discussion about it in #88. I probably should reconsider the decision and save settings on change. Reopening.

As a temporary workaround you can make the changes you need and then exit the app normally once (via system tray).

**Comment by shaonianruntu** [comment]
> > I set the software to start automatically at boot, and the software will always stay in the background.
> > When I get off work, I always click the shutdown button of the system to turn off the computer directly (I will not manually exit the software from the background before turn off).
> 
> That's exactly what I thought. We save the settings of the main window (for example, selected languages, auto-translation, etc.) upon exit. But if the application is killed, the settings will not be saved. It looks like Windows is killing the application on shutdown and that is causing the issue.
> 
> I already had a discussion about it in #88. I probably should reconsider the decision and save settings on change. Reopening.
> 
> As a temporary workaround you can make the changes you need and then exit the app normally once (via system tray).

Thank you very much.

Yes, I tried to manually exit the software from the system tray, and then restarted the computer. After restarting, the option of the software was not cancelled.
