### ISSUE TITLE
Ubuntu 22.04 TLS initialization failed

### ISSUE THREAD

**Issue by ilkarataev** [crow-translate/crow-translate#503]
**Bug description**
When I update my os crow translater doesn't work anymore. Can't translate always get error TLS initialization failed.
I tried to reinstall libss openssl and other staff but not get luck.

**Steps to reproduce**
Just try to translate any word get this message

**Screenshots**
![image](https://user-images.githubusercontent.com/27670867/209470613-e869da23-0174-4fa8-a50d-cd1e9f1a060e.png)
**Environment**
- OS:Ubuntu 22.04.1 LTS
- Desktop environment: Gnome
- Crow Translate version: 2.10.0

**Comment by Shatur** [comment]
Duplicate of #28.

**Comment by Shatur** [comment]
My bad, its on Ubuntu.
The issue in different version of OpenSSL. I think that the application needs to be rebuilt for 22.04.

**Comment by ilkarataev** [comment]
> My bad, its on Ubuntu. The issue in different version of OpenSSL. I think that the application needs to be rebuilt for 22.04.

Can i do it with source code? Or i need wait new release?

**Comment by Shatur** [comment]
> Can i do it with source code? Or i need wait new release?

You can just recompile the application on your machine and it will work.

**Comment by ilkarataev** [comment]
Maybe you can help me I don't undestand how add libraries. get error when try to build.

`karvet@karvet-Latitude-7420:~/Downloads/temo/crow-translate/build$ cmake ..
CMake Error at CMakeLists.txt:62 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/karvet/Downloads/temo/crow-translate/build/CMakeFiles/CMakeOutput.log".
`

**Comment by ilkarataev** [comment]
I found i can just install
apt install extra-cmake-modules
but i have many erros)
Maybe you can provide ready docker file to build the app?

**Comment by Shatur** [comment]
Please show what errors do you have. Maybe you forgot to download git submodules?

**Comment by ilkarataev** [comment]
Yes, I doesn't see this. 
I successful build binary
But have the same issue.

**Comment by Shatur** [comment]
So you have runtime errors. Looks like you have an incompatible version of OpenSSL with your Qt libraries.
I think that something wrong with your OS installation, the OpenSSL from the repo should be compatible with the Qt from the repo. I would recommend you to fully reinstall the OS. Ubuntu often breaks when you update between major versions. After this I think the version from the releases page should start working.

**Comment by ilkarataev** [comment]
I lived with it 6 years) And always update) I don't want reinstall)
Maybe you give me advise how I can debug this problem.

**Comment by Shatur** [comment]
Unfortunately, I don't know how to debug this. You probably want to play with OpenSSL / Qt versions you have in your repo then.

**Comment by ilkarataev** [comment]
I am so sorry of waste you time. Thank you.
I found the problem i have different libcrypto files in /usr/local/lib

Thank you one more time.
