### ISSUE TITLE
Crow-translate CUI is slow

### ISSUE THREAD

**Issue by AllTheLife** [crow-translate/crow-translate#504]
**Bug description**
`crow` in terminal  always takes about 1 minute to respond.

**Steps to reproduce**

1. Open the shell
2. Type in `crow --version` and enter

**Expected behavior**
I want it to give me the translation at once.

**Screenshots**
![Peek 2023-01-15 14-24](https://user-images.githubusercontent.com/87554738/212526281-71aef28e-91a6-420d-96cd-91126a1ad5b4.gif)

**Environment**

- OS: Arch Linux
- Desktop environment: [dwm](https://dwm.suckless.org/)
- Crow Translate version: 2.10.1

Please have a look at this issue.  I've tried many ways to fix it but failed :'(
Thanks!

**Comment by Shatur** [comment]
Can't reproduce, it response instantly on my machine. I also use Arch.
Maybe you compiled it in Debug?

**Comment by AllTheLife** [comment]
I installed it by `pacman -S crow-translate`.
I'll try to compile it to see if the issue still exists.
Thanks for the answering :)

**Comment by AllTheLife** [comment]
It is strange.
After compiling it, I can use it smoothly on KDE Plasma but still bad on dwm.
Maybe it's an issue of dwm, not Crow. And I'll close this issue.
Thanks!

**Comment by Shatur** [comment]
No, it uses only CLI.

**Comment by AllTheLife** [comment]
May you add this please?
Or it will cause some bugs?

**Comment by Shatur** [comment]
Already have a request for it in #411.

**Comment by AllTheLife** [comment]
OK, that's exactly I want!

Sorry for wasting your time and Thank U
