### ISSUE TITLE
Please add always on top feature

### ISSUE THREAD

**Issue by HM-Huong** [crow-translate/crow-translate#506]
Please add always on top feature in the main window.

**Comment by VolkMilit** [comment]
I'm not sure, why you close this request, but if you're on Linux - most, if not all, DE\WM have this feature.

**Comment by HM-Huong** [comment]
Because it is duplicated. I've just learned how to use GitHub. I'm very sorry about that. BTW I'm using windows, and the app doesn't have that feature.
