### ISSUE TITLE
The OCR in v2.10.3 does not capture the screen correctly on my Win10

### ISSUE THREAD

**Issue by MelodyUSA** [crow-translate/crow-translate#513]
### Bug description
The OCR in version 2.10.3 doesn't work well on Win10. 
When I was trying to capture a screen area, it turned out to be like this:

![](https://i.imgur.com/ZehRONR.png)

The desktop would display as four duplicate copies.
then it does not capture the correct position of the text on the screen.
it would capture the wrong place.
And the same problem occurred in version 2.10.2.

And if I switch to version 2.10.1, it works totally fine.
So it's obviously there's something between these two versions, right?

I'm not a developer, I don't know how to describe it in a way that would be more helpful.
But I really like this translation tool, Thank you for developing such a great tool! so\~good luck to you guys\~

### Environment

- OS:  **Windows 10 Pro 1903**
- Desktop environment: 
- Crow Translate version: **2.10.3**

**Comment by Shatur** [comment]
> And if I switch to version 2.10.1, it works totally fine.

Strange, we didn't change anything related to OCR between this version and the current one.

**Comment by MelodyUSA** [comment]
> > And if I switch to version 2.10.1, it works totally fine.
> 
> Strange, we didn't change anything related to OCR between this version and the current one.

Well, maybe my description wasn't quite right.
The OCR itself still works well. It recognises text correctly. 
I was trying to say that maybe the problem is with the screen capture feature

Appreciate that you guys are still working on it~

**Comment by Shatur** [comment]
>  I was trying to say that maybe the problem is with the screen capture feature

Yes, yes, I meant screen capture. 2.10.1 - 2.10.3 had only translation-related changes.
So it's strange. But it's not the only issue with the current screen capture, see #495.

The solution would be to port over screen capture from the KDE Spectacle.

**Comment by MelodyUSA** [comment]
>So it's strange. But it's not the only issue with the current screen capture, see https://github.com/crow-translate/crow-translate/issues/495.

Wow, the issue he submitted looks similar to mine.
Well, I have no idea what the cause is exactly, but so glad you've noticed and come up with the solution.
Appreciate your work~ good luck to you bro~

**Comment by VolkMilit** [comment]
Windows 10 updates tends to break software that worked for YEARS, so this is not surprising. My main job as for now is system administrator, and one Windows 10 update broke Firefox exclusively on one machine. I still doesn't figure what is going on, but rollback this update fixed everything, so I stick to this.

**Comment by o0ZLH0o** [comment]
I encountered the same issue but managed to find a solution that works for me. I installed both versions 2.10.1 and 2.10.5 in separate directories. Then, I copied the .exe and all .dll files from the 2.10.5 version's directory to the corresponding directory of version 2.10.1. This workaround works for me! It allows me to use bing translate and the OCR normally.

**Comment by Shatur** [comment]
This actually a very valuable installation. It means that the bug is in Qt. And downgrading to the previous version works.
Not sure how to solve it for now...

**Comment by Shatur** [comment]
@o0ZLH0o I currently don't have access to Windows machine, so I configured build artifacts. Could you confirm that it works and the bug is reproducible? If yes, I will try some scaling workarounds.

**Comment by o0ZLH0o** [comment]
@Shatur I would love to help! However, I try to run the artifacts and it gives some errors, missing dll including "mcvcp140d.dll," "ucrtbased.dll," "vcruntime140d.dll," and "vcruntime140_1d.dll". I googled and it said I missing the runtime lib for debugging, but I don't know how to install that.

**Comment by Shatur** [comment]
@o0ZLH0o oh, sorry, I forgot that vcpkg have issue with debug configuration. Could you try [this](https://github.com/crow-translate/crow-translate/actions/runs/5243618391) one?

**Comment by o0ZLH0o** [comment]
@Shatur 
![image](https://github.com/crow-translate/crow-translate/assets/25858330/ca19e88b-269c-440a-a9b9-0e03dd04df4f)
Hi, I just tried but it seems to me that the problem persists.

**Comment by Shatur** [comment]
@o0ZLH0o could you try https://github.com/crow-translate/crow-translate/pull/559?

**Comment by o0ZLH0o** [comment]
> @o0ZLH0o could you try #559?

![image](https://github.com/crow-translate/crow-translate/assets/25858330/8cd09f0d-25ed-4000-a257-4ecf336976c2)
I just tried, but still...

**Comment by Shatur** [comment]
Okay... I assume that you have UI scaling about 125% , right? Could you try to set it to 100% temporarely just to make sure that it's the problem?

**Comment by o0ZLH0o** [comment]
@Shatur It appears the same to me...
![image](https://github.com/crow-translate/crow-translate/assets/25858330/7a597a2d-4175-4034-bd22-ebfe040e11e1)

**Comment by Shatur** [comment]
That's odd. Are you sure that you closed the previously opened application before running the new one?

**Comment by Shatur** [comment]
No, it can't be caused by config. But if you have your original program in `c:\program files` running, the new version won't start, it will tell the running program to open from tray.

**Comment by o0ZLH0o** [comment]
> No, it can't be caused by config. But if you have your original program in `c:\program files` running, the new version won't start, it will tell the running program to open from tray.

Thank you but I did close the old one before trying the new one.

**Comment by Shatur** [comment]
Got it, okay, I will think about it more. We just missing a multiplier by dpi somewhere for Windows...
Originally it wasn't needed, but after some changes in Qt - it's needed.

**Comment by Shatur** [comment]
I hope I will find a solution... Pushed another attempt, please check it out.

**Comment by o0ZLH0o** [comment]
> I hope I will find a solution... Pushed another attempt, please check it out.
It seems remains...
![image](https://github.com/crow-translate/crow-translate/assets/25858330/40230445-9aac-476d-91c0-6a7dace2c55a)

**Comment by Shatur** [comment]
@o0ZLH0o thanks! I pushed changes to disaplay some information. Could you please try again and confirm that now all screen is white and if you right click on it anywhere it should display the message with your pixel ration. Please, send me the screenshot.

**Comment by o0ZLH0o** [comment]
> @o0ZLH0o thanks! I pushed changes to disaplay some information. Could you please try again and confirm that now all screen is white and if you right click on it anywhere it should display the message with your pixel ration. Please, send me the screenshot.

You are welcome. the screen is white now, and it displays dpr, which is in line with the computer setting. However, after I right click it is not displaying the pixel message. If I left click and drag the whole screen, I can see that its 3072*1920, which is right. 

I just find a very interesting thing: in the last no-bug version 2.10.1, although it captures the screen correctly, it does not display the correct pixel ratio, as in the last picture. 
![image](https://github.com/crow-translate/crow-translate/assets/25858330/208b0431-2f57-4743-ab82-75f6af19a463)
![image](https://github.com/crow-translate/crow-translate/assets/25858330/fb19c01c-faa4-492f-a8d7-60b1b8ea81f5)
![image](https://github.com/crow-translate/crow-translate/assets/25858330/cf4e68c7-871a-4e6d-99e8-487edb3e3c6c)
![image](https://github.com/crow-translate/crow-translate/assets/25858330/109f5bcf-4969-4306-82ec-3a1f16b5eea5)

**Comment by Shatur** [comment]
> You are welcome. the screen is white now, and it displays dpr, which is in line with the computer setting.

@o0ZLH0o That's what I meant, right click just cancels the rectangle in case you have one remembered.
The information is valuable, thank you. I pushed one more change to determine how resizing behaves. Please, try again and send me what it looks like now.

> I just find a very interesting thing: in the last no-bug version 2.10.1, although it captures the screen correctly, it does not display the correct pixel ratio, as in the last picture.

That's because I added this message in this PR in order to debug it.

**Comment by o0ZLH0o** [comment]
Hi, it looks like this now
![image](https://github.com/crow-translate/crow-translate/assets/25858330/33e8344b-b7f3-42a1-9d06-eed5abb49b73)
![image](https://github.com/crow-translate/crow-translate/assets/25858330/48b0be65-6451-4ae6-a80e-ebedd0f8679e)
:) In 2.10.1 it consider my screen to be 2049x1281

**Comment by Shatur** [comment]
Thank you!
Pushed one more change. Could you try it and also tell me the the displayed dpr (I need to confirm that this value is also corrent)?

**Comment by o0ZLH0o** [comment]
![image](https://github.com/crow-translate/crow-translate/assets/25858330/bf37189e-649b-44bd-85a5-f061a6dc63a1)
Displayed dpr is 1.5, which is current
![image](https://github.com/crow-translate/crow-translate/assets/25858330/edb3a8d9-f9e3-4b1b-8655-3a55433a2396)

**Comment by Shatur** [comment]
Thanks! Pushed another change, please try again.

**Comment by o0ZLH0o** [comment]
![image](https://github.com/crow-translate/crow-translate/assets/25858330/89d1472d-4443-4ae5-add9-d780a8a3a3b9)
![image](https://github.com/crow-translate/crow-translate/assets/25858330/3de193f8-2810-40b0-aac4-4074eabfc116)

**Comment by Shatur** [comment]
Weird, I would expect it to affect the result.
Okay, let's try to disable hidpi attributes. Pushed the change.

**Comment by o0ZLH0o** [comment]
![image](https://github.com/crow-translate/crow-translate/assets/25858330/8eb6557c-5284-4558-a5a0-ce49ef0e268c)
It looks like this this time.

**Comment by Shatur** [comment]
Completely broken, makes sense. Okay, let's back and take a look at the resulting pixmap that Qt gives me. I implemented saving to png in the crow's folder. Please, take a looks at normal and scaled file and tell me their resolution.

**Comment by thewalldao** [comment]
I have exactly the same issue with manjaro kde 1.5 scale

**Comment by Shatur** [comment]
@thewalldao thanks for letting me know! I will try to reproduce on my machine then.

**Comment by Shatur** [comment]
Reproduced!
Will be much easier to fix now.

**Comment by Shatur** [comment]
Fixed!
I tested it on my PC (X11, Linux) and on my Phone (Wayland, Linux). But I need someone to confirm that it works on Windows too. You could download the binaries from CI job in summary tab after it finishes: https://github.com/crow-translate/crow-translate/actions/runs/5383063172/jobs/9769340547.

**Comment by o0ZLH0o** [comment]
Works on windows as well
