### ISSUE TITLE
Function to automatically send the translated text to the clipboard

### ISSUE THREAD

**Issue by MauricioLucas** [crow-translate/crow-translate#514]
Linux users tend to automate tasks with shell scripts, python, xdotool and other things. A function that automatically sends the translation to the clipboard would be very useful, as would the other shortcut functions in GUI mode available also in CLI mode and/or scripts. Or at least that the shortcut that copies to the clipboard is a global function so that it can also be used in OCR capture
label:enhancement

**Comment by Shatur** [comment]
You can use xclip:
```bash
crow "Hello world" | xclip -selection clipboard
```

**Comment by MauricioLucas** [comment]
You are sure.
Obviously I wasn't clear in my request.

### But what if, instead, I need a function to capture texts from a video that needs to be remade in another language? ### 

- [ ]  1.  Ctrl + Alt + O Recognizes the text in the screen area perfectly, but does not send it to the clipboard. It just shows in the window.

- [ ]  2. In "no" CLI mode there is a command that enables per-region screenshot of tesseract-ocr.

- [ ]  3. Note that "Recognize text in screen area" (Ctrl + Alt + O ) is a global shortcut and can be easily incorporated into script.

- [ ]  4. Ctrl+Shift+C Copy translation to clipboard, but this function is not "Global", it is only available "In main window"


Okay, okay! You will reply that I should use the dbus-send command, and then the shortcut to copy to the clipboard


**Why should you make it easy when you can make it difficult?**
¯ \ _ (ツ) _ / ¯ \ _ (ツ) _ / ¯ \ _ (ツ) _ / ¯ \ _ (ツ) _ / ¯ \ _ (ツ) _ / ¯

**Comment by Shatur** [comment]
Sorry, not planning this kind of automation. If you want to use it in other language, just use https://github.com/crow-translate/QOnlineTranslator library.

**Comment by MauricioLucas** [comment]
Buddy, your program is perfect and it works perfectly for me. If you don't want to implement commands that facilitate automation, I'll accept your decision.

Only if it's not a nuisance, it would be of great help if after converting a text capture using OCR, that the translation was also available on the clipboard.

sorry to disturb you

**Comment by VolkMilit** [comment]
@MauricioLucas

> You will answer that I should use ( Ctrl + Alt + C ) to activate the window, then Ctrl + Shift + C) to copy it to the clipboard and close the window ( Ctrl + Q )

You actually don't? You can use Ctrl+Alt+O (by default) to capture text and display it in mini-window. But, you can also can use xclip, as Shatur suggested, and put it in as custom command in your favorite DE\WM. Crow is supported terminal output on Linux, so you can easy parse any command(s) and even output in json.
