### ISSUE TITLE
Is it possible to add an option to remove line breaks from the text before translating the selected text?

### ISSUE THREAD

**Issue by lifeformg** [crow-translate/crow-translate#515]
This is not a problem with this software, but when there are line breaks in the text (e.g. in a pdf file), it gives a bit of a strange translation result. I think the easiest solution might be to let the user choose whether to just remove all line breaks.

**Comment by VolkMilit** [comment]
@lifeformg, what OS do you use? What program for PDF files you use? The answer is depends on your setup. For example, I know that has Acrobat is awful clipboard support, even when pasting between Acrobat and Word, for instance.

**Comment by lifeformg** [comment]
@VolkMilit Hey there, sorry for not giving you the exact info earlier. I'm using Kubuntu and Okular. At first, I didn't notice the "Simplify source" option because the name wasn't clear enough (the mouse hover has a better explanation though, but I guess I wasn't paying attention enough, my bad...). But after I turned it on, the software worked like a charm. Thanks a bunch for your help!
