### ISSUE TITLE
I am not able to use Chinese input. I can't switch fcitx input method. 

### ISSUE THREAD

**Issue by d29107d** [crow-translate/crow-translate#517]
**Bug description**

I can't switch fcitx input method on the main window.
**Steps to reproduce**

**Expected behavior**

**Screenshots**

![2023-03-02_04-54](https://user-images.githubusercontent.com/82889377/222262777-db9c4173-d791-4a49-b28f-97be8228e23c.png)

**Environment**

- OS:  archlinux
- Desktop environment:  KDE
- Crow Translate version:  2.10.3

**Additional context**

**Comment by Shatur** [comment]
Can you use it in other KDE apps?

**Comment by d29107d** [comment]
I upgrade the fcitx to fcitx5, it's ok now.
