### ISSUE TITLE
Debian repository

### ISSUE THREAD

**Issue by peter099** [crow-translate/crow-translate#518]
**Describe the problem or limitation you are having**

I can't install `crow translate` from repository on debian.

**Describe the solution you'd like**

Repository for debian will be very useful.

**Describe alternatives you've considered**

Currently i am using the flatpak version of `crow translate`, but i prefer installing software from .deb files. Flatpaks are bloatware.

**Comment by Shatur** [comment]
It would be great, but I can't do it. You need to ask Debian developers.

**Comment by peter099** [comment]
But you have ubuntu repository. What is the difference?

**Comment by Shatur** [comment]
No, I don't maintain Ubuntu PPA either. It's volunteered by another person.
You could write him or ask Debian devs to include the app.
