### ISSUE TITLE
Not working on Amazon kindle desktop or web reader.

### ISSUE THREAD

**Issue by RyanOrigens** [crow-translate/crow-translate#521]
Bug description
Not working on Amazon kindle desktop or web reader.

Steps to reproduce

1. Select the text on amazon kindle app or web reader
2. try to use the translate selected text feature
3. It ignores the selected text and translate the previous selection

The amazon kindle has a different selection feature which doesn't actually consider that you're selecting the text.

Screenshots
[Screenshot from 2023-03-25 10-04-32](https://user-images.githubusercontent.com/103891807/227719191-d9b4dd94-183c-438d-9c7b-be3bac455550.png)

Possible solution

Add a translate clipboard text feature.

**Comment by Shatur** [comment]
Should be fixed by fd02ef6244364d46e4f9bced1b6a97a49599aa6d.
