### ISSUE TITLE
Installer - Issues about installer script

### ISSUE THREAD

**Issue by bovirus** [crow-translate/crow-translate#532]
@Shatur 

**Bug description**

Installer Bug
- Not showed version on top left
-  "Uninstall" program icon description untranslated

** How to reproduce the problem**

Install the application

**Expected behavior**

Add right info in installer script to fix these.

**Screenshots**

![image](https://user-images.githubusercontent.com/1262554/232588588-26509e3d-838a-4aba-b1fc-b8e61d1925e9.png)

![image](https://user-images.githubusercontent.com/1262554/232588352-f4e9804c-6de1-4041-9fb9-b974cfdc868d.png)

![image](https://user-images.githubusercontent.com/1262554/232588031-80d7b0a5-853e-4f30-884d-8fdfc010ba0b.png)

If you like I can help with installer script.

**Environment**

- OS: Windows 10 22H2
- Desktop environment: 
- Crow Translate version: 2.10.4

**Additional context**

**Comment by Shatur** [comment]
> Not showed version on top left
> "Uninstall" program icon description untranslated

We don't have control over it. The installer is generated using NSIS. You can ask them to add translation for "Uninstall" and show version on the top left: https://github.com/kichik/nsis

Regarding the info you already opened a PR. There is one comment to address: https://github.com/crow-translate/crow-translate/pull/459#discussion_r939974790.
Sorry, I missed your comment where you asked to help you with ECM. You don't need to install it manually. Just install vcpkg and specify path to toolchain via `-DCMAKE_TOOLCHAIN_FILE=<vcpkg-root>/scripts/buildsystems/vcpkg.cmake`, it will install all necessary dependencies and compile the app. Alternatively you could try to fork the project, enable CI and draft a new release in the fork. This will trigger the CI and it will compile the project for you.

**Comment by veksha** [comment]
> Sorry, I missed your comment where you asked to help you with ECM. You don't need to install it manually. Just install vcpkg and specify path to toolchain via `-DCMAKE_TOOLCHAIN_FILE=<vcpkg-root>/scripts/buildsystems/vcpkg.cmake`, it will install all necessary dependencies and compile the app.

also delete `CMakeCache.txt` if it already exists. wasted some time to figure it out.

**Comment by bovirus** [comment]
@Shatur 

The command of NSIS is included in CmakeList.txt then we should identify the right command to add to CmakeList.txt.
Also the string "Uninstall" is part of NSIS installer script that is included in Cmakelist.txt

**Comment by Shatur** [comment]
>  Is it possible to add the line missing line like

Yes, address the comments in PR and compile the binary to verify that it works.

**Comment by bovirus** [comment]
@Shatur 

You can also add

   Name \"${APPLICATION_NAME} {VERSION}\"

to have on top left the program name + version

and
 
  BrandingText \"${COMPANY_NAME}\"

or

  BrandingText \"${LEGAL_COPYRIGHT}\"


to have info about Company Name or Copyright on bottom left.

**Comment by Shatur** [comment]
> to have on top left the program name + version

This makes sense to me.

> to have info about Company Name or Copyright on bottom left.

It's up to you, but I would not add it.

**Comment by bovirus** [comment]
@Shatur 

Ok.
If you can please make a temporary build to check these changes.
Thanks.

**Comment by Shatur** [comment]
Unfortunately, I currently busy. But I described how to do it in this comment: https://github.com/crow-translate/crow-translate/issues/532#issuecomment-1512032744. Try for yourself or ask me questions if there is something unclear to you.

**Comment by bovirus** [comment]
@Shatur 

I tried but I got an error during compilation.

When you will have more time please consider if you to enable for any changes of source code the automatic creation of a temporary build.

**Comment by Shatur** [comment]
> I tried but I got an error during compilation.

Which one?

> When you will have more time please consider if you to enable for any changes of source code the automatic creation of a temporary build.

We do create automatic build on releases. Just activate GitHub actions and create a new release in your fork.
But you need to rebase the fork to the latest master to point to the latest vcpkg version (old one tries to use outdated source links).

**Comment by bovirus** [comment]
@Shatur 

I created a fork from latest master.
Form the fork I selected on top left "Actions".
On the left I have "Main" and "Release".
And now?

**Comment by Shatur** [comment]
> I created a fork from latest master.

Great!
Now open repo settings, navigate to "Actions", then "General", scroll to "Workflow permissions" and select "Read and write permissions". After it open releases page and draft a new release. This will trigger the action.

Uploading artifacts after each commit also makes sense, I will configure it when I have some time. It will make it easy to test things in the future.

**Comment by bovirus** [comment]
@Shatur 

Set in teh settings the permission to read and write.

Go to "Action" tab then on the left I have "Releases" but nothing else.
Should I do same specific actions?

**Comment by Shatur** [comment]
Not sure If I understand you correctly. Did you manage to set permissions, but don't know how to draft a new release?

> Go to "Action" tab then on the left I have "Releases" but nothing else.
> Should I do same specific actions?

Under "Releases" page I meant [this](https://github.com/crow-translate/crow-translate/releases) one, but in your fork. Just create a new release in your fork and it will compile the app.

> The error with compialtion (oN Windows) is always thes ame

If you want to compile it locally (on your computer), you need to use vcpkg. The installation is simply, all you need to do is to set `-DCMAKE_TOOLCHAIN_FILE=<vcpkg-root>/scripts/buildsystems/vcpkg.cmake` on configuration step.

**Comment by bovirus** [comment]
Hi-

My configuration is this

Variable VCPKG_ROOT=D:\Download\Development\vcpkg
QT system 6.6.0 (MSWC 2019 64bity
Developping tool - Cmake 3.24.2

When I downlaod souce and decomrpess it, create a build subfodler and from it I run

cmake -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake .. 

I got this error

CMake Error at CMakeLists.txt:62 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by Shatur** [comment]
> cmake -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake ..

Hm... I think it does not expand the envvar. What I would suggest is to set `-DCMAKE_TOOLCHAIN_FILE=D:/Download/Development/vcpkg/scripts/buildsystems/vcpkg.cmake ..` directly. But do not forget to clean the build dir before doing it.

> I got this error

If you using vcpkg it should work out of the box. You don't need to install anything else.
