### ISSUE TITLE
OCR error

### ISSUE THREAD

**Issue by momosnail** [crow-translate/crow-translate#537]
## Problem Description
- When I use the OCR shortcut：`ctrl + alt+ I ` ，The screen will turn gray and the text cannot be recognized

- Below is a screenshot of when the error occurs：
![error](https://www.futurus.top:5544/uploads/%E6%88%AA%E5%9B%BE%202023-04-22%2020-49-47.png)

##  Environment and configuration
- Linux：majaro
- crow-translate:
![settings](https://www.futurus.top:5544/uploads/%E6%88%AA%E5%9B%BE%202023-04-22%2020-51-19.png)

> But I don't have this problem on another manjaro
Hello, this is the normal crow-translate on another manjaro
![settings](https://www.futurus.top:5544/uploads/%E6%88%AA%E5%9B%BE%202023-04-23%2013-45-02.png)

**Comment by Shatur** [comment]
Please, fill the issue in english. If we developing translator it does not mean that we will translate every issue. Here is how the text looks in my browser:
![изображение](https://user-images.githubusercontent.com/22453358/233787348-036d145a-a109-4999-8299-fb6bd4112bc4.png)

**Comment by momosnail** [comment]
> Please, fill the issue in english. If we developing translator it does not mean that we will translate every issue. Here is how the text looks in my browser: ![изображение](https://user-images.githubusercontent.com/22453358/233787348-036d145a-a109-4999-8299-fb6bd4112bc4.png)

sorry this is my problem i have updated the description

**Comment by Shatur** [comment]
Thanks!
I use Archlinux on which Manjaro is based on and I don't have this issue. You also mentioned that you don't have this problem on other Manjaro. How these two setups are different?

**Comment by momosnail** [comment]
> Thanks! I use Archlinux on which Manjaro is based on and I don't have this issue. You also mentioned that you don't have this problem on other Manjaro. How these two setups are different?

Another manjaro that can use crow-translate normally is in the company. I will go to work tomorrow to check its configuration. Thank you very much for your patience in helping me solve the problem.

**Comment by momosnail** [comment]
> Thanks! I use Archlinux on which Manjaro is based on and I don't have this issue. You also mentioned that you don't have this problem on other Manjaro. How these two setups are different?
Hello, this is the normal crow-translate on another manjaro
![settings](https://www.futurus.top:5544/uploads/截图 2023-04-23 13-45-02.png)

**Comment by momosnail** [comment]
> Thanks! I use Archlinux on which Manjaro is based on and I don't have this issue. You also mentioned that you don't have this problem on other Manjaro. How these two setups are different?

I see that the crow-translate setting on another manjaro is the same. I think it may be a system problem. I will use it for a while to confirm the problem. Come back to give you feedback. Thank you very much for taking the time to answer my questions, thank you very much!
