### ISSUE TITLE
Remember translation window position

### ISSUE THREAD

**Issue by leonid1812** [crow-translate/crow-translate#549]
Currently, the text translation popup window appears in varying positions on the screen each time it is opened. This cause inconvenience for users. Therefore, I would like to propose the implementation of a feature that allows the software to remember and retain the position or coordinates of the text translation popup window.

By incorporating this functionality, the software would be able to intelligently store and recall the previous position of the translation popup window. As a result, users would no longer need to readjust its position manually each time they invoke the translation feature. This would greatly enhance the usability of the software and streamline the translation process.

**Comment by Shatur** [comment]
Popup appears right under the cursor and I think it's a reasonable behavior. You can switch to translation window that remembers the last position.
