### ISSUE TITLE
[Windows] 2.2.1 build has no sys tray icon

### ISSUE THREAD

**Issue by mockroot** [crow-translate/crow-translate#55]
With 2.2.1 update, system tray icon has gone. Only way to activate the window is via shortcut.
I checked the settings and it's the same as before, so I'm guessing there is a problem with the new build?

**Comment by Shatur95** [comment]
Wow, yes thanks you, it's because Windows sometimes breaks symbolic links. I will fix it asap.

**Comment by Shatur95** [comment]
Done! I re-uploaded Windows build.
