### ISSUE TITLE
settings.ini in portable mode should be taken relative to the executable path

### ISSUE THREAD

**Issue by char101** [crow-translate/crow-translate#556]
**Describe the problem or limitation you are having**
I added crow.exe to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths` so that I can run `crow.exe` from the run dialog. But it did not pick the `settings.ini` file because it is specified as relative path (i.e. to the current working directory) rather than to the application directory.

**Describe the solution you'd like**
Join `settings.ini` with `QCoreApplication::applicationDirPath()`.

**Describe alternatives you've considered**
N/A

**Additional context**
OS: Windows 10

**Comment by Shatur** [comment]
Makes total sense to me. Could you submit a PR?

**Comment by char101** [comment]
Sorry I know some Qt but I haven't used C++ in a long time.

**Comment by Shatur** [comment]
No problem. I just currently a little busy.
If anyone want to tackle it in the meantime - just prepend `QCoreApplication::applicationDirPath()` here:
https://github.com/crow-translate/crow-translate/blob/74bdbdf17274a003339c5cf3aa417e23048f8c3b/src/settings/appsettings.h#LL388C25-L388C32
