### ISSUE TITLE
Wrong pop-up window coordinates and form height after translation 

### ISSUE THREAD

**Issue by leonid1812** [crow-translate/crow-translate#565]
Params:
![image](https://github.com/crow-translate/crow-translate/assets/17238147/ab1a54bd-4b9b-4a02-aeae-ffc892d0c237)

Wrong pop-up window coordinates and form height after translation 
![1](https://github.com/crow-translate/crow-translate/assets/17238147/c1eb11c1-d4d8-4a63-9df5-8e8d24ba0eac)

![2](https://github.com/crow-translate/crow-translate/assets/17238147/4e6c0f4e-4b13-4b45-8008-a53de246ecc7)

**Comment by Shatur** [comment]
Popup window opens under your cursor, not under the text. In fact, there is no way to detect the selected text position on the screen. So the behavior is expected.
