### ISSUE TITLE
Unbale to install

### ISSUE THREAD

**Issue by yulibu** [crow-translate/crow-translate#57]
Hi i really love crow translate it's simple and easy to use, i can install it from manjaro with Aur but i just change to ubuntu 19.04 try to install it but fail i got this error

WARNING: Project ERROR: Unknown module(s) in QT: winextras

is there any deb package i can use

thanks

**Comment by Shatur95** [comment]
Hello! Thank you :)

It's not an error:
`WARNING: Project ERROR: Unknown module(s) in QT: winextras`
This warning appear because qmake checks all specified modules even if I specified it for windows. You can just ignore it.

Yes, .deb package is on the way, stay tuned for updates.

**Comment by Shatur95** [comment]
Done! I also fixed some Lantian warnings :)
