### ISSUE TITLE
 crow-translate deb package can't install on debian 12

### ISSUE THREAD

**Issue by Minipada** [crow-translate/crow-translate#577]
**Bug description**
 crow-translate depends on libtesseract4; however:
Package libtesseract4 is not installed.

**Steps to reproduce**
1. download 2.10.6 version amd64 deb file
2. dpkg -i crow-translate_2.10,6_amd64.deb

get
```
Selecting previously unselected package crow-translate.
(Reading database ... 307444 files and directories currently installed.)
Preparing to unpack .../crow-translate_2.10.6_amd64.deb ...
Unpacking crow-translate (2.10.6) ...
dpkg: dependency problems prevent configuration of crow-translate:
 crow-translate depends on libtesseract4; however:
  Package libtesseract4 is not installed.

dpkg: error processing package crow-translate (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 crow-translate
```

**Expected behavior**
install sucessefull

**Environment**

- OS:  Debian 12 bookworm
- Desktop environment: KDE
- Crow Translate version: 2.10.6

**Additional context**
Only libtesseract5 is available here, instead of the requested libtesseract4

**Comment by Shatur** [comment]
It's because it compiled under Ubuntu 20.04. Unfortunately, you need to build it for Debian yourself :(
Or ask maintainers to add this application to the official repository. I would be happy to mention the installation way on the website.
