### ISSUE TITLE
[BUG] When the program starts, it automatically creates a new file in the user directory

### ISSUE THREAD

**Issue by poplar-at-twilight** [crow-translate/crow-translate#593]
**Bug description**

When crow-translate  starts, it automatically creates a new file named `tesseract_opencl_profile_devices.dat` in the user directory

```
poplar@c004-h0:~> cat tesseract_opencl_profile_devices.dat
<version>v0.1</version>
<device><type></type><score>�N�></score></device>
```

**Steps to reproduce**

1. Installing crow-translate with zypper: `sudo zypper in  crow-translate`
2. Just click to start it.

**Expected behavior**

And then that strange file appeared in the user directory.

**Screenshots**

No screenshots at the moment, I can add them if you need them.

**Environment**

>Operating System: openSUSE Tumbleweed 20230724
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.4-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Additional context**

```
poplar@c004-h0:~> date; zypper info crow-translate
2023年 07月 28日 星期五 18:39:09 CST
正在加载软件源数据...
正在读取已安装的软件包...


软件包 crow-translate 的信息：
------------------------------
软件源     : openSUSE-Tumbleweed-Oss
名称       : crow-translate
版本       : 2.10.0-1.4
架构       : x86_64
出品方     : openSUSE
已安装大小 : 2.7 MiB
已安装     : 是
状态       : 最新
源代码包   : crow-translate-2.10.0-1.4.src
上游网址   : https://crow-translate.github.io/
摘要       : A Qt GUI for Google, Yandex and Bing translators
描述       : 
    A simple and lightweight translator that allows to translate and speak
    text using Google, Yandex and Bing written with Qt5.
```

**Comment by Shatur** [comment]
> tesseract_opencl_profile_devices.dat

I assume that this file created by Tesseract, text recognition library.
But I can't reproduce this issue on my machine, so I think it's related to the tesseract configuration on your distro.

**Comment by poplar-at-twilight** [comment]
Newly created configuration or cache files should be placed in `~/.config`, `~/.cache`, or an XDG-compliant folder, not directly in the user's home directory.

**Comment by poplar-at-twilight** [comment]
> I assume that this file created by Tesseract, text recognition library. But I can't reproduce this issue on my machine, so I think it's related to the tesseract configuration on your distro.

Thanks for the reply, I will report this issue to the openSUSE maintainers.

**Comment by victorhck** [comment]
> > I assume that this file created by Tesseract, text recognition library. But I can't reproduce this issue on my machine, so I think it's related to the tesseract configuration on your distro.
> 
> Thanks for the reply, I will report this issue to the openSUSE maintainers.

did you fill a bug for this? same issue here, but didn't know is related with this...
Greetings

**Comment by poplar-at-twilight** [comment]
> did you fill a bug for this? same issue here, but didn't know is related with this... Greetings

I remember that I submitted an issue, but I never received replies from maintainers.

After that, I switched to using the package provided by flathub.
