### ISSUE TITLE
Global shortcuts are not activated, WHY?

### ISSUE THREAD

**Issue by khaled-magdy123** [crow-translate/crow-translate#594]
![image](https://github.com/crow-translate/crow-translate/assets/93298421/7d3617b3-810c-48af-977c-0dd6664f44ae)

**Comment by Shatur** [comment]
Because you using Wayland.

**Comment by khaled-magdy123** [comment]
Thanks.

**Comment by khaled-magdy123** [comment]
> Because you using Wayland.

is disabling it will harm my Ubuntu

**Comment by Shatur** [comment]
Sorry, I don't use Ubuntu, so I can't tell.
But you can use https://github.com/crow-translate/crow-translate#d-bus-api to call specific commands. You can bind this commands inside your system settings.
But Wayland we currently have issues with translating selection on Wayland, see https://github.com/crow-translate/crow-translate/issues/324.

**Comment by joenepraat** [comment]
For people coming here via a search engine. The command you have to use to translate selected text (as a custom shortcut in system settings > keyboard) is: 

`dbus-send --type=method_call --dest=io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow io.crow_translate.CrowTranslate.MainWindow.translateSelection`
