### ISSUE TITLE
auto tranlate

### ISSUE THREAD

**Issue by 2Cwizard** [crow-translate/crow-translate#600]
**Bug description**
when tranlate selected text or a text you have to choice language tab in top on translate box cause defualt is auto. for example I wanna tranlate from english to persian but its translate from english to english and you must have to choice persian language tab on top of tranlate box becuase defualt is auto.

**Steps to reproduce**

1. open crow translate
2. add language right english an left persian
3. wright english text in right box and then translate
4. you see its translate english to english instead ensglish to persian

for selected text:
1. open crow translate
2. add language right english an left persian
3. select a text in broswer or anywhere 
4. and translate it with shortkey
5. you see its translate english to english instead ensglish to persian

**Expected behavior**

**Screenshots**
![Screenshot at 2023-08-05 03-33-31 (copy)](https://github.com/crow-translate/crow-translate/assets/86792168/38e3bb8c-768b-4d51-96f0-13ee99163d99)

**Environment**

- OS: linux, parrot
- Desktop environment: MATE
- Crow Translate version: 2.10.10
**Additional context**

**Comment by Shatur** [comment]
This works as expected. "Auto" by default translates to system language. But if the system language matches the source language, it translates to English. You can select other "fallback" language in setting in translation tab.
