### ISSUE TITLE
Proposal for Comprehensive UI Redesign

### ISSUE THREAD

**Issue by Tiberth** [crow-translate/crow-translate#604]
**Describe the problem or limitation you are having**
I would like to propose a comprehensive UI redesign for the program to enhance its user experience and overall aesthetics.

**Describe the solution you'd like**
I have created a detailed mockup, which presents a revamped UI design aimed at improving user interaction and visual appeal. The proposed changes include a reorganization of elements, a new color palette following the Material 3 design principles and a more intuitive icons.

**Additional context**
I have used the Material 3 design guidelines to ensure consistency and familiarity in the new UI. The language icons are sourced from this [Icon Pack](https://github.com/HatScripts/circle-flags), and the Lingva logo is obtained from their [GitHub Page](https://raw.githubusercontent.com/thedaviddelta/lingva-translate/0190ea5da9fbccba51e82184ca855c4ef5728fc7/public/logo.svg). Additionally, the rest of the icons are from the Material Icons library.

Here are the two images: firstly, the Light Mode
![Crow Translate Light](https://github.com/crow-translate/crow-translate/assets/62080102/ef1ea9ba-c8bc-4a0a-b8db-03e4bc990cfd)
, and secondly, the Dark Mode.
![Crow Translate Dark](https://github.com/crow-translate/crow-translate/assets/62080102/e08ba344-5d0b-4655-99aa-21075356f593)

Furthermore, I omitted two elements. Firstly, the 'Auto-translation' checkbox, as I believe it would be more suitable within the General Settings section. Secondly, I removed the 'Copy all Translation Data to Clipboard' button, as I couldn't find a suitable icon or identify a clear use case.

I have retained the original logo, but if desired, I am open to converting the old logo into a vector graphic. However, I thought this might entail unnecessary effort.

Your feedback and thoughts on this proposed UI redesign would be greatly appreciated. Thank you for considering this enhancement!

**Comment by Shatur** [comment]
Thanks! I open to redesign by re-arranging / adding / removing elements. But I against using custom style for elements. In my opinion applications should use system theme and icons. See [this](https://stopthemingmy.app/) for more information (it's about GTK apps, but the same can be said for Qt).

I think moving auto-translation checkbox to settings is a good idea, yes.
`Copy all Translation Data to Clipboard` copies all text from translation, including examples.
