### ISSUE TITLE
[Fedora 31] Nothing provides qt-gstreamer

### ISSUE THREAD

**Issue by serovar** [crow-translate/crow-translate#61]
It is not possible to install the package from the COPR on Fedora 31:
sudo dnf install crow-translate
Error: 
 Problem: conflicting requests
  - nothing provides qt-gstreamer needed by crow-translate-2.2.1-2.fc31.x86_64
  - nothing provides qt-gstreamer needed by crow-translate-2.2.2-1.fc31.x86_64

**Comment by faezebax** [comment]
> It is not possible to install the package from the COPR on Fedora 31:
> sudo dnf install crow-translate
> Error:
> Problem: conflicting requests
> 
> * nothing provides qt-gstreamer needed by crow-translate-2.2.1-2.fc31.x86_64
> * nothing provides qt-gstreamer needed by crow-translate-2.2.2-1.fc31.x86_64

this was because of retired package `qt-gstreamer` in f31. it's rebuilt now without that dependency and should work without  any problem.
