### ISSUE TITLE
Adding the Deepl API

### ISSUE THREAD

**Issue by GrgMdmn** [crow-translate/crow-translate#612]
Hello ! I would like to know if it could be possible adding deepl as a translator. Deepl is API-friendly. Man can create an account and get an api key that could be used in crow-translate.

Thanks a lot for answering :)

**Comment by Shatur** [comment]
Duplicate of https://github.com/crow-translate/QOnlineTranslator/issues/6

**Comment by viktor-zhuromskyy** [comment]
Please!
DeepL gives free API with 500K symbols allowance per month. That is nore than enough for most users!

Please add this option to use DeepL in your app!
I can send you $50 to thank for adding this feature.
