### ISSUE TITLE
The program crashes when you press the settings button (Arch, 2.11.02)

### ISSUE THREAD

**Issue by azjio** [crow-translate/crow-translate#621]
**Bug description**
The program crashes when you press the settings button

**Steps to reproduce**
1. Click on a button or menu item in the tray
2. Afterwards the program will not start
3. If you delete the configuration file, the program starts
4. The cycle repeats.

**Environment**

- OS: Arch Linux x64
- Desktop environment: Cinnamon
- Crow Translate version: 2.11.02

**Additional context**
The problem appeared immediately after the update

**Comment by Shatur** [comment]
Can't reproduce on my machine.

**Comment by azjio** [comment]
```
>>crow
nouveau: kernel rejected pushbuf: Нет такого устройства
nouveau: ch5: krec 0 pushes 1 bufs 4 relocs 0
nouveau: ch5: buf 00000000 00000035 00000004 00000004 00000000 0x7f6d9bf00000 0xf1b000 0x80000
nouveau: ch5: buf 00000001 00000006 00000004 00000000 00000004 0x7f6dbbb38000 0x218000 0x1000
nouveau: ch5: buf 00000002 00000049 00000002 00000000 00000002 (nil) 0x112d000 0x2000
nouveau: ch5: buf 00000003 0000003a 00000004 00000004 00000000 0x7f6daccbb000 0x1129000 0x2000
nouveau: ch5: psh 00000000 0000000780 00000007d0
nouveau: 	0x200181c2
nouveau: 	0x03303210
nouveau: 	0x200681c3
nouveau: 	0x00001030
nouveau: 	0x00000020
nouveau: 	0x00000040
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20088100
nouveau: 	0x00000000
nouveau: 	0x01129000
nouveau: 	0x00000000
nouveau: 	0x0112d000
nouveau: 	0x00000080
nouveau: 	0x00000080
nouveau: 	0x00000020
nouveau: 	0x00000040
nouveau: 	0x200180c0
nouveau: 	0x00000686
crow: ../libdrm-2.4.117/nouveau/pushbuf.c:730: nouveau_pushbuf_data: Проверочное утверждение «kref» не выполнено.
Аварийный останов (образ памяти сброшен на диск)

```

**Comment by Shatur** [comment]
Looks like the problem is related to your graphical drivers. Something in Qt causes this.

**Comment by azjio** [comment]
Is it possible to make any settings optionally? If it worked before, then some new things have hardware dependence.

**Comment by Shatur** [comment]
> Is it possible to make any settings optionally? If it worked before, then some new things have hardware dependence.

I didn't add anything. Something in your machine is crashing the application after the update and it is related to the graphics driver. Try replacing nouveau with NVIDIA drivers and see if it works.

**Comment by ehaupt** [comment]
I see a similar thing on `FreeBSD 14.0-RELEASE amd64` with `2.11.0`. Pressing the settings icon immediately terminates the program with:

```
$ crow 
No autostart provider implemented
Abort trap (core dumped)
```

**Comment by Shatur** [comment]
The issue is different. The program was unable to detect autostart provide because we don't support FreeBSD. Feel free to add extra defines though.

**Comment by ehaupt** [comment]
> The issue is different. The program was unable to detect autostart provide because we don't support FreeBSD. Feel free to add extra defines though.

Could you give me a hint?

**Comment by Shatur** [comment]
> While I understand that FreeBSD is not officially supported, would you consider including this patch upstream

Sure! But instead of `#if defined(Q_OS_LINUX) || defined(Q_OS_UNIX)` use just `#if defined(Q_OS_UNIX)`.

**Comment by ehaupt** [comment]
> > While I understand that FreeBSD is not officially supported, would you consider including this patch upstream
> 
> Sure! But instead of `#if defined(Q_OS_LINUX) || defined(Q_OS_UNIX)` use just `#if defined(Q_OS_UNIX)`.

Are you sure that won't break Linux support?

**Comment by Shatur** [comment]
Sure :)

**Comment by VolkMilit** [comment]
@azjio
Can't reproduce either, also Arch, but I'm using proprietary Nvidia drivers. I found [this issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/1099) on MESA bugtracker, but it was closed 2 years ago. Althrough, it might be related to Cinnamon, I'm and Shatur using KDE and X11. Are you, be any chance, using Wayland?

**Comment by azjio** [comment]
echo $XDG_SESSION_TYPE
x11

**Comment by azjio** [comment]
I installed the open safe video card package and it works for me now.
sudo pacman -Syu nvidia-open-dkms
