### ISSUE TITLE
How to specify priority of APIs? Add GPT v3.5 or later API?

### ISSUE THREAD

**Issue by pstein** [crow-translate/crow-translate#630]
As far as I can see Crow Translate uses (only) Yandex, Bing, LibreTranslate and Lingva translate APIs.

How do I tell Crow which of the translation services it should contact (first)?

Furthermore I miss GPT v3.5 (or later) API.
Can this API be added too?

**Comment by Shatur** [comment]
> How do I tell Crow which of the translation services it should contact (first)?

We use only selected API,  there are no plans to use multiple sources at once.

>  Can this API be added too?

Already requested in other issue.
