### ISSUE TITLE
Accessibility issue with Screen readers

### ISSUE THREAD

**Issue by MesterPerfect** [crow-translate/crow-translate#632]
**Bug description**
I am a blind user and utilize NVDA and JAWS screen readers to navigate the Internet. While all elements in your program are accessible using a screen reader, I encounter difficulty exiting the text box once I've entered it.

**Steps to reproduce**
"Navigate through the items using the tab key, enter the text box, but I am unable to exit it."

**Expected behavior**
I use the tab key to navigate between items. However, inside the text box, pressing the Tab key inserts four white spaces instead of moving to the next item in the program's interface, as it is supposed to.

**Screenshots**
![image](https://github.com/crow-translate/crow-translate/assets/44323153/c1d4b408-2464-4627-bf26-a928736709c2)

**Environment**
- OS: Windows10
- Crow Translate version: 2.11.0

**Additional context**

**Comment by Shatur** [comment]
Hm... Looks like there is [tabChangesFocusProperty](https://doc.qt.io/qt-5/qtextedit.html#tabChangesFocus-prop). I will try to set it to true. Are there other where you experience difficulties?

**Comment by MesterPerfect** [comment]
> Hm... Looks like there is [tabChangesFocusProperty](https://doc.qt.io/qt-5/qtextedit.html#tabChangesFocus-prop). I will try to set it to true. Are there other where you experience difficulties?


"Yes, there are certain elements that a screen reader can't identify. Firstly, the program icon in the system tray lacks a name, making it accessible to a screen reader but preventing it from recognizing the name.

Secondly, the main program interface contains a button that a screen reader can access but is unable to identify by name. This button opens the dialog box for adding a new language to the program.

Thirdly, concerning the program settings, the screen reader can navigate and access all elements, except for the list of shortcuts. Although it can access it, the screen reader is unable to read or modify the list."

**Comment by Shatur** [comment]
Thanks for the feedback, I addressed it in #633. Could you try [this](https://github.com/crow-translate/crow-translate/suites/18683843303/artifacts/1087401925) artifact to confirm that it works?

Regarding shortcuts, now you will be able to read the list, but in order to change it, you need to select any element from it, then set the key sequence in the input edit field below and after that click the “Accept” button.

**Comment by MesterPerfect** [comment]
> Thanks for the feedback, I addressed it in #633. Could you try [this](https://github.com/crow-translate/crow-translate/suites/18683843303/artifacts/1087401925) artifact to confirm that it works?
> 
> Regarding shortcuts, now you will be able to read the list, but in order to change it, you need to select any element from it, then set the key sequence in the input edit field below and after that click the “Accept” button.

"That's awesome! I am extremely pleased with the prompt response to my request for resolving accessibility issues. Everything is working perfectly. Thank you!"

**Comment by Shatur** [comment]
You are welcome!
I will draft a new release once localization catch up for the newly added strings. In the meantime, you can use the downloaded version.

**Comment by Shatur** [comment]
Feel free to submit translations using [this](https://github.com/crow-translate/crow-translate#localization) instruction.
