### ISSUE TITLE
OCR SELECTOR not working properly on wayland/wlroots...

### ISSUE THREAD

**Issue by RyanOrigens** [crow-translate/crow-translate#636]
I cannot tell for certain if this is a Wayland issue or if it's a Hyprland thing because it doesn't happen on Sway!

The bug is as follows: when I activate the OCR, the ability to drag and pick the location where the text is located doesn't work properly; it becomes all weird, and I struggle to move it.

This issue doesn't occur with other screenshot tools; that's why I believe it's a Crow-Translate issue rather than a Hyprland issue.

**Comment by RyanOrigens** [comment]
Unless sway or hyprland edits the DPI for some reason, and I'm not aware, on my part, I haven't changed.

**Comment by RyanOrigens** [comment]
I'll see if i can find out what is the DPI of my screen in both of them.

**Comment by wzqj** [comment]
> I cannot tell for certain if this is a Wayland issue or if it's a Hyprland thing because it doesn't happen on Sway!

Can I ask what your setup is? I'm using Arch with Sway, and every time I try to use the screen area selection, I get an error with "Unable to grab screen. No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop". 

I have xdg-desktop-portal 1.18.2-1.1 and xdg-desktop-portal-wlr 0.7.0-2 installed.

**Comment by Shatur** [comment]
Hm... Maybe on sway you have a different D-Bus interface?
Crow tried to detect if you using GNOME or KDE and uses specialized interfaces [here](https://github.com/crow-translate/crow-translate/blob/master/src/ocr/screengrabbers/waylandgnomescreengrabber.cpp) and [here](https://github.com/crow-translate/crow-translate/blob/master/src/ocr/screengrabbers/waylandplasmascreengrabber.cpp). But if you use a different DE, crow uses [generic XDG portal interface](https://github.com/crow-translate/crow-translate/blob/master/src/ocr/screengrabbers/waylandgnomescreengrabber.cpp).
Try using dbus from CLI to see what interface you have available and write me back.

**Comment by wzqj** [comment]
I changed some configs and restarted xdg-desktop-portal services, and now it seems to work, but only for the first screen capture. Any subsequent captures gives "Unable to grab screen. Received an empty path from xdg-desktop-portal." If I close crow and reopen it, screen capture will work for a single time again, and error on the subsequent attempts.

> Try using dbus from CLI to see what interface you have available and write me back.

I got the same error as above using the translateScreenArea command on the README, if you meant something else, please let me know and I will run it. 

Also, I have a laptop and external monitor at 1080p, with the external one positioned above in sway config like this:
> output eDP-1 resolution 1920x1080 position 0,0
> output HDMI-A-1 resolution 1920x1080 position 0,-1080 

The screen capture preview grabs the external monitor's output and displays it the laptop monitor; basically, I cannot select anything on the laptop monitor for the screen capture.

**Comment by Shatur** [comment]
> EDIT: I tried using dbus-monitor, this is where the error seems to occur when capturing:

Looks like something wrong on XDG desktop size. Because they seem to can't allocate memory. Not sure if I can do something about it.

> The screen capture preview grabs the external monitor's output and displays it the laptop monitor; basically, I cannot select anything on the laptop monitor for the screen capture.

This looks like a bug on my side, but I need the hardware to fix it :(

**Comment by wzqj** [comment]
> Looks like something wrong on XDG desktop size. Because is seems like XDG can't allocate memory. Not sure if I can do something about it.

Hmm, I have no problem using grimshot (grim + slurp), and flameshot "works" (except that it also has the problem with external monitor". Not sure if that's any help.

> This looks like a bug on my side, but I need the hardware to fix it :(
:( Maybe looking at grim/slurp's repos can give some ideas. I am open to testing or providing needed information :)

**Comment by Shatur** [comment]
> Maybe looking at grim/slurp's repos can give some ideas. I am open to testing or providing needed information

Without access to the hardware it will be pain to debug. We probably need someone with have free time, dual monitor setup like yours and some coding skills :)

**Comment by wzqj** [comment]
> Without access to the hardware it will be pain to debug. We probably need someone with have free time, dual monitor setup like yours and some coding skills :)

Maybe a holiday gift will show up :pray: :) I am using tesseract output in the meantime with the cli version and it is working well. Just wished I could find something that can make a popup of the translation temporarily so I don't have to switch back to the terminal every time. 

As a side note, It would be nice if you could add iciba as an engine, it seems to be better at translating Chinese than others. Someone has implemented it in another program before, maybe it would be helpful:
https://codeberg.org/SimpleWeb/SimplyTranslate-Engines/src/branch/master/simplytranslate_engines/icibatranslate.py

**Comment by RyanOrigens** [comment]
By translating, you mean recognizing Chinese characters with the OCR?

**Comment by RyanOrigens** [comment]
It was a hyprland issue, it was fixed on 33.1.
