### ISSUE TITLE
On Ubuntu 22.04, global shortcuts work in Google Chrome and do not work in gedit, Evince, ...

### ISSUE THREAD

**Issue by poglazov** [crow-translate/crow-translate#638]
**Bug description**
Both default Ctrl - Alt - E and a new shortcut I set instead:
- work in Google Chrome,
- don't work in most other applications, e.g. gedit and Evince.

I've read that "Wayland does not support global shortcuts registration, but you can use [D-Bus](https://github.com/crow-translate/crow-translate#d-bus-api) to bind actions in the system settings.", but I can't figure out why it works in Google Chrome.

**Environment**

- OS: Ubuntu 22.04.3 LTS
- Desktop environment: GNOME 42.9
- Crow Translate version: 2.11.0
- Windowing System: Wayland

**Comment by Shatur** [comment]
Most likely you run Crow on XWayland and it works with other XWayland applications, like Google Chrome.

**Comment by poglazov** [comment]
> Most likely you run Crow on XWayland and it works with other XWayland applications, like Google Chrome.

Could you tell how can I check it?

I tried ```xlsclients``` as a random internet advice tells. It tells that Google Chrome does run on XWayland, but Crow doesn't: 
![Screenshot from 2023-12-06 22-22-15](https://github.com/crow-translate/crow-translate/assets/1129843/01564c9f-cb50-4ea8-aa37-2582888b6f7e)

**Comment by poglazov** [comment]
> And if it's empty, try to set `QT_QPA_PLATFORM=wayland` and run the app.

You were right:
```
pavel@pavel-ux31a:~$ env | grep QT
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
pavel@pavel-ux31a:~$ export QT_QPA_PLATFORM=wayland
pavel@pavel-ux31a:~$ env | grep QT
QT_ACCESSIBILITY=1
QT_QPA_PLATFORM=wayland
QT_IM_MODULE=ibus
pavel@pavel-ux31a:~$ crow 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
```

Now the shortcuts don't work in either Chrome or gedit. Crow app itself also works worse, e.g. not all entered text is displayed.

I wish shortcuts worked across all apps, and Crow worked well.

What should I do?

**Comment by Shatur** [comment]
> Now the shortcuts don't work in either Chrome or gedit.

On Wayland there is no API for global shortcuts. Each DE implements global shortcuts in its own specific way and you need to manually register D-Bus commands on shortcuts. But now you should have working selection translation. Try it out.

> Crow app itself also works worse, e.g. not all entered text is displayed.

This is odd. I assume that it could be some GNOME-specific bug. I run the app my phone on Phosh (a DE similar to GNOME, but mobile oriented) and the app work fine.

**Comment by poglazov** [comment]
Thank you for explanation.

I created a Gnome shortcut running dbus-send, disabled global shortcuts in Crow, and now the shortcut works in both Chrome and gedit: 
![image](https://github.com/crow-translate/crow-translate/assets/1129843/aa6f0c93-3819-4fe0-9bb1-70c2b0c8067c)

The shortcut works both with Crow running with QT_QPA_PLATFORM=wayland and without it. Which option should I use?

**Comment by Shatur** [comment]
> QT_QPA_PLATFORM=wayland

With this parameter it will run "natively" on Wayland. Without it will run through XWayland. It's a compatibility layer.
On my phone I set this variable globally for all Qt applications.
