### ISSUE TITLE
feature_request(2.11): hide sources area when translating selected text

### ISSUE THREAD

**Issue by Kristinita** [crow-translate/crow-translate#639]
### 1. Summary

Please return the ability (at least as an option) to hide sources area when executing a command `TranslateSelection`.

### 2. Steps to reproduce

The user selects text → presses the shortcut to execute the `TranslateSelection` command:

#### 3.1. Desired

As in Crow Translate 2.10 and previous versions:

![Crow Translate 2.10 no sources block](https://i.imgur.com/qQqAHaN.png)

#### 3.2. Undesirable

Crow Translate 2.11 has an additional sources area (in a red rectangle):

![Crow Translate 2.11 sources block](https://i.imgur.com/X7m16gE.png)

#### 4.1. Duplication

The contents of the sources area duplicate the contents of the selected text. 

The original text may have the design: for example, paragraphing, bold, italic text. The text in the sources area doesn’t have this, so I’d rather look at the original text rather than the text in the sources area. I don’t understand why it was necessary to add to Crow Translate area with additional duplicate text without formatting.

#### 4.2. Monitor area

Sources area takes up space on the monitor screen and can cover the original text (as in my example). I often look at the source text to verify the correctness of the machine translation, but the sources area prevents me from doing this.

Thanks.

**Comment by Shatur** [comment]
I didn't change any behavior between these two versions.
In general settings there is an option called "Translation mode" and it should be set to "Pop-up window" in order to get the behavior you describing.

**Comment by Kristinita** [comment]
**Status: RESOLVED** :heavy_check_mark:

### 1. Source area problem

The problem arose because, for some reason, there was a line in my `settings.ini` file:

```ini
[Interface]
PopupOpacity=0
```

If I set the integer value `1` for the parameter `PopupOpacity`:

```ini
[Interface]
PopupOpacity=1
```

I get desired behavior.

### 2. Migration to the version 2.11

From the [**description of the release of Crow Translate 2.11.0**](https://github.com/crow-translate/crow-translate/releases/tag/2.11.0):

> Remove spaces in settings paths. Everywhere instead of "Crow Translate" now "crow-translate".

I had problems with Crow Translate settings on my Windows 11 after I updated Crow Translate to version 2.11.0 via [**Scoop**](https://scoop.sh/). What I did to restore the previous settings:

1. I opened Crow Translate 2.10.10 (the previous version) → `Settings` → `General` → `Portable mode` → in the root of the Crow Translate 2.10.10 folder appeared the file `settings.ini`. Portable mode is necessary because in standard mode Crow Translate strangely stores settings — [**in the Windows Registry without any configuration file**](https://github.com/crow-translate/crow-translate/issues/74). In the portable mode, Crow Translate stores all settings in the `settings.ini` file in the root of the Crow Translate folder.
1. I copied the `settings.ini` file from the `2.10.10` folder to the root of the `2.11.0` folder → Crow Translate now works for me as before.

Perhaps my comment will help someone who is having trouble upgrading Crow Translate to version 2.11.0 on Windows.

Thanks.
