### ISSUE TITLE
ChatGPT integration

### ISSUE THREAD

**Issue by lwbaqueros** [crow-translate/crow-translate#648]
**Describe the problem or limitation you are having**

The translations done by Google Translator and others are inferior to those done by ChatGPT. Additionally, ChatGPT can enhance translations by using proper context. Furthermore, for languages such as German, Google Translate cannot utilize the second informal person very well and consistently mismatches the tone of the conversation. This issue does not occur when using ChatGPT for translation.

**Describe the solution you'd like**

Use the ChatGPT API to launch a fixed message ChatGPT and receive the response as follows: 
1. _Translate the next text from <Primary_Language> to <Secondary_Language>: "Input User Text"_
2. When ticking an option to improve the translated text, the ChatGPT question should be: _Translate the next text from <Primary_Language> to <Secondary_Language> and improve style: "Input User Text"_

**Describe alternatives you've considered**

https://github.com/simpleapples/chatgpt-translator

**Additional context**

The ChatGPT beats any other translator out there.

**Comment by Shatur** [comment]
Duplicate.
