### ISSUE TITLE
Add support for Brazilian Portuguese

### ISSUE THREAD

**Issue by autogris** [crow-translate/crow-translate#651]
**Describe the problem or limitation you are having**
Currently, Crow only display Portugal's Portuguese option, which is in many aspects different from Brazilian Portuguese.

**Describe the solution you'd like**
Add Brazilian Portuguese option, which is available in several translations services.

**Describe alternatives you've considered**
Manually correct spelling variants and different phrase constructions.

**Comment by Shatur** [comment]
We have both enabled:
![image](https://github.com/crow-translate/crow-translate/assets/22453358/6dd09bf4-2c3a-4ddf-88cb-7f5b1df7ca46)

**Comment by autogris** [comment]
That's strange on my list of available languages it shows only Portugal
![image](https://github.com/crow-translate/crow-translate/assets/13917422/d896f153-2bc1-4b73-9966-3928725cfe55)
![image](https://github.com/crow-translate/crow-translate/assets/13917422/e6a75160-8c18-44b3-9536-7a502ae56d49)

**Comment by Shatur** [comment]
Ah, you mean languages for translation. I thought that you mean localization.

Languages come from translation engines, I have no control over available languages.

**Comment by FabricioLopees** [comment]
> That's strange on my list of available languages it shows only Portugal (I'm on version 2.11.1) ![image](https://private-user-images.githubusercontent.com/13917422/298399757-d896f153-2bc1-4b73-9966-3928725cfe55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Mzg2NTgsIm5iZiI6MTcxMTYzODM1OCwicGF0aCI6Ii8xMzkxNzQyMi8yOTgzOTk3NTctZDg5NmYxNTMtMmJjMS00YjczLTk5NjYtMzkyODcyNWNmZTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE1MDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YjU0ZmJmMjc3NjQxZDY3OThmMWVlZWEzM2ViYzZkNjkwZWEyNGNlMmY2NzY2NDZlY2ExNjlkM2RhZGU3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TPqj8siT_lNQ2dPSlpWcZwwb_pyFe2U83nSA4g2lPfo) ![image](https://private-user-images.githubusercontent.com/13917422/298399790-e6a75160-8c18-44b3-9536-7a502ae56d49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Mzg2NTgsIm5iZiI6MTcxMTYzODM1OCwicGF0aCI6Ii8xMzkxNzQyMi8yOTgzOTk3OTAtZTZhNzUxNjAtOGMxOC00NGIzLTk1MzYtN2E1MDJhZTU2ZDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE1MDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZTQ5ZmJhMThkYWE2MmQxMjhkMjg3N2YyNzg5NTUwYmU1ZWU3MzYwZTM0YTdkMGU5Yjc3YWIwNWMzZThkNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xblGYtic6f-kx0EHN3DTaQ0ku5yVo4XA9nZw0GU153Q)

### It shows the flag of Portugal, but it is in Brazilian Portuguese. It's just an error in the reference icon. It would be nice if the icon was the Brazilian flag, but it doesn't affect usability, so it's ok for me.

![crow screenshot img 1](https://github.com/crow-translate/crow-translate/assets/162738847/09a2cf8a-2ed7-4280-82b8-99f2b03e4215)
![crow screenshot img 2](https://github.com/crow-translate/crow-translate/assets/162738847/41963471-74c6-452d-a77f-8e116c12a5f8)
