### ISSUE TITLE
Ubuntu Package is outdated

### ISSUE THREAD

**Issue by hoshython** [crow-translate/crow-translate#656]
who the hell is maintaining this package for Ubuntu? Didn't update for 43 weeks and 23.10 is not supported though.

**Comment by Shatur** [comment]
If you referring to PPA, I think it's @JonMagon.
Feel free to create your own PPA and share with others.

**Comment by JonMagon** [comment]
> who the hell is maintaining this package for Ubuntu? Didn't update for 43 weeks and 23.10 is not supported though.

Hi. I haven't used Ubuntu for a long time, but another distro, and I don't always have time to keep track. You could write me an email. I try to maintain it to the best of my ability, and would be happy for someone else to start maintaining.
Unfortunately this kind of tone in the question doesn't do much for that.

**Comment by JonMagon** [comment]
Built 2.11.1 for focal, jammy, mantic and future noble.

**Comment by Shatur** [comment]
Thank you a lot!
It's so great that you continue to support your PPA even though you no longer use Ubuntu.
