### ISSUE TITLE
Add Croatian translation

### ISSUE THREAD

**Issue by milotype** [crow-translate/crow-translate#658]
**Describe the problem or limitation you are having**
I'm not able to add or send a merge request due to my "old" MacOS 10.11.6/Firefox 78.15.0esr.

**Describe the solution you'd like**
Please add my attached Croatian translation into https://github.com/crow-translate/crow-translate/tree/master/data/translations

**Additional context**
Please also add the Croatian translation to https://crowdin.com/project/crow-translate?auto_accepted=13751141&invite_hash=public-join

[crow-translate_hr_HR.ts.zip](https://github.com/crow-translate/crow-translate/files/14319929/crow-translate_hr_HR.ts.zip)

**Comment by Shatur** [comment]
Thanks, closed by #653.

**Comment by Shatur** [comment]
Wrong PR, one moment.

**Comment by Shatur** [comment]
Looks like it only 96% translated. It's [available on Crowdin](https://crowdin.com/project/crow-translate), please visit and finish the translation :)

**Comment by milotype** [comment]
> Looks like it only 96% translated. It's [available on Crowdin](https://crowdin.com/project/crow-translate), please visit and finish the translation :)

Thank you for adding Croatian translation.
The Croatian translation is now 100 % translated. :-)
