### ISSUE TITLE
small size font 

### ISSUE THREAD

**Issue by Cherkah** [crow-translate/crow-translate#662]
**Bug description**
impossible to have crow size font corresponding to the general system font size. Even when scaling is enabled.
 A lot of sections from the Gui wiht text stay small ( buttons, labels, comboboxes, etc).

**Expected behavior**
coherent font size with system font settings

**Screenshots**
the system size font = 13 and scaling = 115%
but the crow's font appear smaller:

![Copie d'écran_10 03 2024_14h43](https://github.com/crow-translate/crow-translate/assets/16431970/fa52c0e1-c048-4d27-ab98-c103aa4be4ca)

**Environment**

- OS: endeavouros  
- Desktop environment: kde plasma6 + wayland
- Crow Translate version: 2.11.1

*Additional context*
i can observe this issue with an other app which is still an qt5

As crow bug info:
```
QFont::fromString: Invalid description 'Noto Sans,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Hack,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
```

**Comment by Cherkah** [comment]
@Shatur your  responsive & accurate. 
i didn't lose my time with you cuz you permitted me to resolve a quite of issues :)
 thanks a lot

**Comment by Shatur** [comment]
You are welcome :)
