### ISSUE TITLE
Tray icon as ... (three dots) on Gnome Wayland.

### ISSUE THREAD

**Issue by ivan-toriya** [crow-translate/crow-translate#665]
**Bug description**

Tray icon doesn't look fine.

**Steps to reproduce**

1. Install via flatpak.
2. Start Crow Translate.

**Expected behavior**

Proper icon in the tray.

**Screenshots**

![image](https://github.com/crow-translate/crow-translate/assets/43750521/54bc3b7d-a2bb-4892-b442-b7dbad5dabc1)

**Environment**

- OS: Debian 12.5 
- Desktop environment: Gnome Wayland 
- Crow Translate version:  2.11.0

**Additional context**

I would like to hide in completely, but I don't know how to achieve it without turning off "Start minimized" setting.

**Comment by Shatur** [comment]
I'm not sure why it happens, but I assume that it's because Gnome doesn't support tray properly.

**Comment by ivan-toriya** [comment]
But all other apps (flatpak's as well) works fine.
![image](https://github.com/crow-translate/crow-translate/assets/43750521/c03ed9e2-3070-4de7-8736-4f4b3dc87e4a)

**Comment by ivan-toriya** [comment]
The approach for now is to fix it using [qt5ct](https://github.com/desktop-app/qt5ct), correct?

**Comment by Shatur** [comment]
Unfortunately, I don't use GNOME or Flatpak.
Ping @gasinvein, maybe you have an idea what could caused it?

**Comment by gasinvein** [comment]
No idea, sorry. It feels like the way Qt apps interact with the AppIndicator extension in Gnome requires a dedicated expert, which I am not.

@ivan-toriya Does this reproduce with a non-flatpak installation of Crow Translate of the same version?

**Comment by ivan-toriya** [comment]
@gasinvein thanks, that actually helped!
I didn't know that I can use Launchpad PPA to install packages on Debian (I though it's for Ubuntu only). I've followed [this guide](https://wiki.debian.org/CreatePackageFromPPA) to do so.
![image](https://github.com/crow-translate/crow-translate/assets/43750521/a3448f54-3151-4c4e-a460-6515b153e3f5)
