### ISSUE TITLE
Wrong Russian menu translate

### ISSUE THREAD

**Issue by RomanAleynikov** [crow-translate/crow-translate#668]
![translate](https://github.com/crow-translate/crow-translate/assets/87813216/e36d52fe-b4dd-41f3-a575-70c5ac4e5c80)
The Russian word on screenshot "прозрачность" is "transparency" English word. But it is not right  because original English word is "opasity" and its Russian translate is "непрозрачность".

**Comment by Shatur** [comment]
Good point, any chance you could submit a PR? You need to edit [this](https://github.com/crow-translate/crow-translate/blob/master/src/settings/settingsdialog.ui) file.

**Comment by RomanAleynikov** [comment]
What is PR?

**Comment by Shatur** [comment]
Pull request.

**Comment by Shatur** [comment]
It's not resolved, I would prefer to keep it open.

**Comment by RomanAleynikov** [comment]
Ok. Just I have little experience using GitHub, because I don't know I have to do now.

**Comment by VolkMilit** [comment]
Fixed in crowdin update.
