### ISSUE TITLE
Please make a "dark mode" option

### ISSUE THREAD

**Issue by DarkameMaster** [crow-translate/crow-translate#669]
I have dark mode enabled on Windows but the app doesn't change the mode, if there was an option available in settings that would be awesome

An alternative that I found is enabling high contrast mode but it makes Windows look uglier :( 

This is not related but I would also suggest to make an option that can instantly translate from the clipboard! That would help a lot

**Comment by b-risk** [comment]
I would like this as well, (I'm on Linux Mint).

**Comment by Shatur** [comment]
Duplicate of #487.
