### ISSUE TITLE
GUI only launches on second try

### ISSUE THREAD

**Issue by tatami4** [crow-translate/crow-translate#67]
First launch only starts the background process. Second launch launches the GUI and "The application is already running" warning. Also happens with global shortcuts.

System: Manjaro KDE
App source: AUR

**Comment by Shatur95** [comment]
Do you have the "Start minimized" setting enabled?

**Comment by Shatur95** [comment]
Do you use git version?

**Comment by tatami4** [comment]
Yes, "Start minimized" was apparently enabled (I dind't even know this app had settings, because there is nothing on the GUI that indicates it).

**Comment by Shatur95** [comment]
This application has a tray icon

**Comment by tatami4** [comment]
Yes, I found it (forgot to mention)

**Comment by Shatur95** [comment]
I will disable this option by default :)

**Comment by lucasmouravarela** [comment]
For some reason, which I don't know, the system tray icon no longer appears. I restalled the windows to see if it came back but not.

**Comment by Shatur95** [comment]
You have this issue only on the latest version? What version of Windows are you using?

**Comment by lucasmouravarela** [comment]
Yes last version, I found it yesterday. I use Windows 10 Home. Weird is before formatting, for a moment I had icon in system tray. I somehow messed up something wrong. But with the formatting I imagine that it doesn't matter anymore.

**Comment by Shatur95** [comment]
@lucasmouravarela, so, you do not see the app in tray, but can access to it with shortcuts?

**Comment by Shatur95** [comment]
@lucasmouravarela, could you try the previous version?

**Comment by lucasmouravarela** [comment]
Yes.

**Comment by Shatur95** [comment]
Let me know if you expecting or not the issue. I need to know in what version it appears.

**Comment by lucasmouravarela** [comment]
I tested version 2.3.1 and the icon came back. Working.

**Comment by Shatur95** [comment]
Thank you, I will I'll try to fix ASAP.

**Comment by Shatur95** [comment]
Done, the issue was in CI. Please, re-download latest version.
