### ISSUE TITLE
qdbus not found with Ctrl+Alt+e shortcut

### ISSUE THREAD

**Issue by victorhck** [crow-translate/crow-translate#675]
**Bug description**

Can't use the Ctrl+Alt+E shortcut due an issue.

**Steps to reproduce**

1. With a higlighted text 
2. Use the shortcut Ctrl+Atl+E
3. See error "qdbus not found"

**Expected behavior**

Should open a window with the higlighted text trasnlated

**Screenshots**

![imagen](https://github.com/crow-translate/crow-translate/assets/1514206/136dd846-bc12-47c0-8f50-b78fac76ab0c)

(the text is in spanish)

**Environment**

- OS: openSUSE Tumbleweed (updated)
- Desktop environment: Plasma 6
- Crow Translate version: 2.10.0
**Additional context**

**Comment by Shatur** [comment]
Hi! The problem in your distrivution, you need to install qdbus. Not an application bug.

**Comment by victorhck** [comment]
Ok. Thanks a lot for your time and effort developing this application.
Greetings!

**Comment by krop** [comment]
> Hi! The problem in your distribution, you need to install qdbus. Not an application bug.

I disagree, it is crow-translate that wrongly assumes qdbus is in $PATH.

To allow coinstallation of different Qt versions, most distributions don't do that.

**Comment by Shatur** [comment]
I can't adapt it for each distro, but you can edit the `.desktop` file:
https://github.com/crow-translate/crow-translate/blob/226221f4decf5bb702f4f624f0c9725c7f650e7e/data/io.crow_translate.CrowTranslate.desktop#L27
It's not a code.
