### ISSUE TITLE
Wrong language detection

### ISSUE THREAD

**Issue by Jairjua** [crow-translate/crow-translate#70]
Portuguese !=  Poland
![image](https://user-images.githubusercontent.com/9156799/67206079-558fe780-f3e7-11e9-8435-ac69968c5570.png)

**Comment by Shatur95** [comment]
Reproduced, I will fix it this evening

**Comment by Shatur95** [comment]
Done. Thank you, the issue was in function `key()` that takes an index of language instead of enum value.
