### ISSUE TITLE
Wrong Mail Address in About

### ISSUE THREAD

**Issue by smaragdus** [crow-translate/crow-translate#71]
The mail address in _About_ is wrong, when one clicks the mail link it opens in the mail client a different mail address (actually the mail address of the developer of a famous open source torrent client), screen:

![Crow Translate 2 2 1 - 2019-02-27 - 003](https://user-images.githubusercontent.com/9025757/67250564-89651e80-f474-11e9-8980-b2cb6f821b5e.png)

To confirm the problem just start [Crow Translate](https://crow-translate.github.io/), open _Settings_, go to _About_, click the mail link and see what mail address opens in the mail client.

**Comment by Shatur95** [comment]
Thanks for the issue! I just looked at how it is implemented in qBittorrent and forgot to change the address :(

**Comment by smaragdus** [comment]
@Shatur95 

Thanks for the quick fix,
