### ISSUE TITLE
Version 2.2.2 Unavailable for Windows

### ISSUE THREAD

**Issue by smaragdus** [crow-translate/crow-translate#72]
The latest [version](https://github.com/crow-translate/crow-translate/releases) of [Crow Translate](https://github.com/crow-translate/crow-translate)- [2.2.2](https://github.com/crow-translate/crow-translate/releases/tag/2.2.2), is not available for download for Windows, screen:

![Crow Translate 2 2 1 - 2019-02-27 - 005](https://user-images.githubusercontent.com/9025757/67252144-5f165f80-f47a-11e9-8a7a-9bbadfbefde1.png)

The latest available version for Windows is **2.2.1**.

However the update check finds new version (**2.2.2**), screen:

![Crow Translate 2 2 1 - 2019-02-27 - 007](https://user-images.githubusercontent.com/9025757/67252128-4e65e980-f47a-11e9-94bb-303c8bc41ca1.png)

Was this a wrong upload or there is a special reason why version **2.2.2** was not released for Windows?

**Comment by Shatur95** [comment]
Wow, thank you, I's my mistake :(
Fixed.

**Comment by smaragdus** [comment]
@Shatur95 

Thank you for the quick response and for uploading version 2.2.2 for Windows. Tonight I will install and test it. I may open one more issue but it would require much more work.

**Comment by Shatur95** [comment]
Feel free to let me know about any bugs :)

**Comment by smaragdus** [comment]
@Shatur95 

I do not know whether this is a bug or my system is faulty but Crow Translate (version 2.2.2) crashes when I exit it so I opened a new issue (#75).
