### ISSUE TITLE
Can't install or update on Windows 10

### ISSUE THREAD

**Issue by franco27** [crow-translate/crow-translate#76]
v 2.2.2 , 2.2.1 also - Win 10

1 / I execute the installation file (the application is closed)
![2019-10-28_11h23_23](https://user-images.githubusercontent.com/31793920/67671295-f0ec0400-f975-11e9-8dfe-eef130a4399c.png)
  or, from the software I run the update
2/ every time there is this error message when the files are copied to the folder
"impossible to write"

3/ I solved this problem by activating the administrator mode of Windows 10 by opening the installation file
I am stuck for the update from the application.
(by opening a software in administrator mode, there is some software that creates another folder with user data and I could notice the loss of my software user settings) (by disabling the administrator mode my user data is retrieved)

I think it would be necessary before the update from the application and the opening of the installation file cause the display of the window to ask to activate the administrator mode (to allow the software to bring changes).
Generally this method is used by the software, I could see it and AntDM uses this method.

I do not know if I can reproduce this problem under Windows 7 or Windows 8 but if my memory does not fail me, with AntDM, it seems to me that with Windows 7 there was not this problem.

**Comment by Shatur95** [comment]
Thanks for the issue. I will try to fix it ASAP.

**Comment by Shatur95** [comment]
Must works now, check installer from GitHub again :)

**Comment by franco27** [comment]
I confirm that it is resolved with the installation file
