### ISSUE TITLE
Invalid or empty cipher list ()

### ISSUE THREAD

**Issue by LinArcX** [crow-translate/crow-translate#80]
Hi. i have void linux that doesn't support openssl and it uses libressl instead. So i clone the repo with all modules:
`git clone --recursive git@github.com:crow-translate/crow-translate.git`

And open the project in qt-creator and build it. It was build successfully, but i had some problems:
1. It only works with bing.
2. When i want to switch to google or yandex it says:
`Invalid or empty cipher list ()`
3. I can't see the icons in main window.

**Comment by Shatur95** [comment]
Hello!
Hm... Google and Yandex uses GET request, and Bing uses POST. But this does not seem to be an application bug. Could you test GET request from [Qt example](https://code.qt.io/cgit/qt/qtbase.git/tree/examples/network/downloadmanager) (also available in "Examples" in QtCreator as "Network Download Manager").

The application uses SVG icons. Do you have `qt5-svg` installed? Also, if you are not using KDE or LXQT, then you may need to install `qt5-styleplugins` for proper looking.

**Comment by VolkMilit** [comment]
Wired guess: google and yandex can't establish secure connection, because your libressl is not up to date. Do you checked for updates? Also: are other Qt application that used network working on this setup?

I found [this](https://bugreports.qt.io/browse/QTBUG-68374), seams like Qt doesn't support libressl.

**Comment by LinArcX** [comment]
@Shatur95 Hi. i tested "Network download manager" and it works without any problem.
Also i isntalled both `qt5-svg` and `qt5-styleplugins` but still have same problem to see icons.

@VolkMilit I tested "Network download manager" in examples section in qt creator and it works perfect.
Also i think it's better to attach the log of program when it try to send request to google or yandex:
https://gist.github.com/LinArcX/0e77c5d6c0c0f08b4b1ddfe52145abc9

**Comment by Shatur95** [comment]
Do you mean that you tried to download something with "Network download manager" example?
Crow used the same mechanism for translation request.

After installing `qt5-styleplugins` and `qt5-svg` you need to set a style. Try `env QT_STYLE_OVERRIDE=gtk2 crow` or `crow -style gtk2` or set the `QT_STYLE_OVERRIDE` as environment variable globally.

**Comment by LinArcX** [comment]
Yes, I downloaded a music with it.

**Comment by VolkMilit** [comment]
Still, this is very strange. Does google and yandex actually works for you in browser? Because this error "Invalid or empty cipher list ()" mean that libressl can't check ssl certificate, so HTTPS will not work. Can you please check for this?

Can you also check which package contains this file: /etc/ssl/certs/ca-certificates.crt ? In Arch Linux this is ca-certificates-utils, and I believe it also contains all ciphers.

**Comment by LinArcX** [comment]
Yes, both: https://translate.google.com/ and https://translate.yandex.com works perfectly in firefox.

Also the package name that contain `ca-certificates.crt` is: [ca-certificate](https://github.com/void-linux/void-packages/blob/9b1c782457df092be9219e61aba023358e9cdb81/srcpkgs/ca-certificates/template)

**Comment by VolkMilit** [comment]
Well, I'm out of ideas.

@Shatur95, maybe put "Need help" label, so someone can help?

**Comment by LinArcX** [comment]
Also i'v tried: https://github.com/crow-translate/QOnlineTranslator To ensure that all things happen in a minimal environment and i also have same problem with yandex and google.

**Comment by Shatur95** [comment]
Can't reproduce the issue. I downloaded the Void Linux LXQT live image, installed it in a virtual machine, updated the system, and built the application. Everything is works. For icons I just installed `papirus-icon-theme`, no environment variables needed. So I think that something wrong with your system configuration.
![изображение](https://user-images.githubusercontent.com/22453358/68210198-b883a000-ffdd-11e9-8d3b-c6a8b1a57b0d.png)

**Comment by LinArcX** [comment]
Interesting... Because i used [qt-offline-installer](https://download.qt.io/archive/qt/5.13/5.13.2/qt-opensource-linux-x64-5.13.2.run)(and i think this is the root of this issue). So i decided to build __crow-translate__ manually with qmake and these dependencies:
```
qt5-qmake
qt5-multimedia-devel
qt5-x11extras-devel
gst-plugins-good1
```
It works!
Also i have some other issues like:
1. When i switch to bing, it can't play sound and throws an error: `Bing engine does not support TTS`
2. Still can't see icons.(I installed [la-captaine-icon](https://github.com/void-linux/void-packages/pull/13256) theme manually)

**Comment by Shatur95** [comment]
Of course you need to install Qt from repos :)

1. Yes, because **Bing engine does not support TTS**.
2. Looks like you not configured Qt-applications look. This is DE-depended and not an app issue too.
