### ISSUE TITLE
Crash on Wayland

### ISSUE THREAD

**Issue by digititus** [crow-translate/crow-translate#84]
Using the Copr repo for Fedora 31.

```
QSocketNotifier: Can only be used with threads started with QThread
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
Segmentation fault (core dumped)
```

Starting crow-translate from CLI coredumps. Can provide full dump if needed.

**Comment by Shatur95** [comment]
Could you try other Qt application? qBittorrent, for example. Is it works?

**Comment by digititus** [comment]
qBittorrent works

**Comment by faezebax** [comment]
> Using the Copr repo for Fedora 31.
> 
> ```
> QSocketNotifier: Can only be used with threads started with QThread
> QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
> Segmentation fault (core dumped)
> ```
> 
> Starting crow-translate from CLI coredumps. Can provide full dump if needed.

I am maintainer of crow-translate for fedora. The workaround for this problem is to change `Exec=crow` in **/usr/share/applications/crow-translate.desktop** to `Exec=env QT_QPA_PLATFORM=xcb /usr/bin/crow`

**Comment by digititus** [comment]
This is my edited usr/share/applications/crow-translate.desktop

```
[Desktop Entry]
Name=Crow Translate
GenericName=Translator
GenericName[ru]=Переводчик
Comment=A simple and lightweight translator that allows to translate and speak the selected text u>
Comment[ru]=Простой и легковесный переводчик, который позволяет переводить и озвучивать выделенный>
Keywords=google;yandex;text-to-speech;
Keywords[ru]=google;yandex;текст в речь;
Exec=env QT_QPA_PLATFORM=xcb /usr/bin/crow
Icon=crow-translate
Terminal=false
StartupNotify=false
Type=Application
Categories=Office;Network;Qt
```
Still crashes.

**Comment by faezebax** [comment]
Did you tested in Xorg session?

**Comment by digititus** [comment]
Xorg is working. Wayland is not

**Comment by Shatur95** [comment]
I already [sent](https://github.com/Skycoder42/QHotkey/pull/26) fix to QHotkey library. I will fix the crash, but shortcuts will now work in Wayland for now. I looking for solution.
