### ISSUE TITLE
Add an option to  remove line breaks

### ISSUE THREAD

**Issue by gxb152** [crow-translate/crow-translate#91]
Is it possible to add an option to  remove line breaks in the source text automatically, these line breaks will affect the result of Google Translate

**Comment by Shatur95** [comment]
Yes, probably good idea.

**Comment by Shatur95** [comment]
Done. Now source text will be [trimmed](https://doc.qt.io/qt-5/qstring.html#trimmed) automatically and you can also enable [simplification](https://doc.qt.io/qt-5/qstring.html#simplified) by an option in translation settings.
