### ISSUE TITLE
Cannot translate more than two sentences at the same time

### ISSUE THREAD

**Issue by gxb152** [crow-translate/crow-translate#93]
**Describe the bug**
I don't know if this is a feature or a bug. I can't translate more than two sentences at the same time, at least when using Google Translate for English to Chinese.

**To Reproduce**
Type "The first sentence. The second sentence.", it only translates "The first sentence.".
Type "The first sentence.The second sentence.", it translates both.

**Expected behavior**
There is a translation I expect in any case(translate both).

**Screenshots**
![Screenshot_20191213_204126](https://user-images.githubusercontent.com/19903807/70801579-38c1d000-1dea-11ea-90b3-6b95d485c5d8.png)
![Screenshot_20191213_204154](https://user-images.githubusercontent.com/19903807/70801585-3b242a00-1dea-11ea-9cd1-c272c1c3970b.png)

**Environment (please complete the following information):**

- OS: Arch Linux
- Desktop environment: KDE

**Comment by Shatur95** [comment]
Could you explain it a bit more?

**Comment by Shatur95** [comment]
Thank you, I will look into it.
