### ISSUE TITLE
Bug in transliteration option

### ISSUE THREAD

**Issue by gxb152** [crow-translate/crow-translate#95]
**Describe the bug**
Translation transliteration is displayed in the window regardless of whether "Enable translation transliteration" is checked.
Source transliteration is not displayed in the window regardless of whether "Enable source transliteration" is checked.

**Screenshots**
![Screenshot_20191221_200148](https://user-images.githubusercontent.com/19903807/71307829-ece8d980-242e-11ea-8224-cd5885aeaed4.png)
![Screenshot_20191221_200442](https://user-images.githubusercontent.com/19903807/71307830-ed817000-242e-11ea-8b8a-641312774fa2.png)

**Environment (please complete the following information):**

- OS: Arch Linux
- Desktop environment: KDE

**Comment by Shatur95** [comment]
Thanks!
