### ISSUE TITLE
toolbar icons cannot be displayed

### ISSUE THREAD

**Issue by imaojun** [crow-translate/crow-translate#96]
**Bug description**
Missing toolbar icons 

![image](https://user-images.githubusercontent.com/28778042/71333275-6b02c880-2574-11ea-80a8-55cd95197b3d.png)

I referenced the solution of another issue, but still can't display the icons normally.
https://github.com/crow-translate/crow-translate/issues/15#issue-384693984

![image](https://user-images.githubusercontent.com/28778042/71333197-1cedc500-2574-11ea-81ea-b8d060674cfb.png)

No matter the value of the environment variable is set to gtk2 or qt5ct. The icon still cannot be displayed.

![image](https://user-images.githubusercontent.com/28778042/71333563-5ffc6800-2575-11ea-8f45-a51f65c1d63c.png)

**Environment**

-   Crow Translate 2.2.3
-    Arch Linux
-   Bspwm

**Comment by Shatur95** [comment]
Do you have `qt5-styleplugins` installed? You need to install it and remove `qt5ct`.
Or you can use qt5ct, but you need to set relevant environment variables as in your second screenshot.
